/**
 * العربية
 */
export default {
    translation: {
        app: { title: "KunQiong Player", subtitle: "Powered by KunQiong AI", custom_software: "برنامج مخصص", login: "تسجيل الدخول", not_logged_in: "زائر", logged_in: "تم الدخول", login_tip: "سجّل الدخول لمزيد من الميزات", login_action: "تسجيل الدخول", redirecting: "جاري التحويل...", login_in_browser: "أكمل تسجيل الدخول في المتصفح.", relogin: "إعادة تسجيل الدخول", login_success_sync: "تم الدخول. جاري المزامنة...", vip_user: "عضو", logout: "تسجيل الخروج", token_label: "الرمز:", welcome_tip: "اسحب الفيديو هنا", loading: "جاري التحميل...", screenshot_path: "مجلد لقطات الشاشة:", global_brightness: "السطوع", reset: "إعادة تعيين", reset_all: "إعادة تعيين الكل", ok: "موافق", cancel: "إلغاء", apply: "تطبيق", unit: { ms: "ملث", s: "ث", times: "x", items: "" } },
        menu: { file: "ملف", open_file: "فتح ملف...", open_folder: "فتح مجلد...", open_url: "فتح رابط...", exit: "خروج", play: "تشغيل", play_pause: "تشغيل/إيقاف", stop: "إيقاف", next: "التالي", prev: "السابق", fast_forward: "تقديم", rewind: "ترجيع", effects: "تأثيرات", splitter: "مقسم", video_decoder: "فك فيديو", audio_decoder: "فك صوت", renderer: "عرض", auto_select: "تلقائي", control: "تحكم", subtitle: "ترجمة", picture_quality: "صورة", audio_adjust: "صوت", settings: "إعدادات", help: "مساعدة", help_doc: "التوثيق", shortcuts: "اختصارات", licenses: "تراخيص الجهات الخارجية", privacy: "الخصوصية", check_update: "التحقق من التحديثات...", feedback: "ملاحظات", about: "حول", language: "اللغة", lang_zh: "简体中文", lang_en: "English" },
        playlist: { title: "قائمة التشغيل", add: "إضافة", clear: "مسح", loop: "تكرار القائمة", loop_list: "تكرار القائمة", loop_list_title: "تكرار القائمة", loop_single: "تكرار واحد", loop_single_title: "تكرار واحد", random: "عشوائي", random_title: "عشوائي", empty: "القائمة فارغة", empty_tip: "انقر \"إضافة\" أو اسحب الملفات", ad_placeholder: "إعلان" },
        picture: { title: "الصورة", ratio: "النسبة", ratio_original: "أصلي", ratio_fill: "ملء", rotation: "دوران", flip_h: "أفقي", flip_v: "عمودي", pan: "تحريك", zoom: "تكبير", presets: { default: "افتراضي", bright: "ساطع", soft: "ناعم", retro: "رجعي" } },
        audio: { title: "الصوت", volume: "مستوى الصوت", channel: "قناة", channel_default: "افتراضي", channel_left: "يسار", channel_right: "يمين", sync: "مزامنة", track: "مسار", track_default: "افتراضي", load_track: "تحميل مسار" },
        subtitle: { title: "الترجمة", main_tab: "رئيسي", sec_tab: "ثانوي", select: "اختيار", hide: "إخفاء", load: "تحميل", enable_sec: "تفعيل الثانوي", style: "نمط", font_yahei: "Microsoft YaHei", font_hei: "SimHei", font_song: "SimSun", font_kai: "KaiTi", sync: "مزامنة", position: "موضع", pos_up: "أعلى", pos_down: "أسفل", pos_left: "يسار", pos_right: "يمين", continue_effect: "تطبيق دائمًا", color_title: "لون", basic_color: "ألوان أساسية", custom_color: "مخصص", cancel: "إلغاء", confirm: "تأكيد" },
        control: { title: "التحكم", left_eye: "العين اليسرى", surround: "محيطي", threed: "وضع 3D", settings: "إعدادات" },
        lefteye: { title: "العين اليسرى", view_angle: "زاوية الرؤية", brightness: "السطوع", contrast: "التباين" },
        surround: { title: "محيطي", mode: "الوضع", mode_off: "إيقاف", mode_stereo: "ستيريو", intensity: "الشدة", bass: "باس" },
        threed: { title: "3D", mode: "الوضع", mode_off: "إيقاف", mode_anaglyph: "أناغليف", mode_sbs: "جنبًا إلى جنب", mode_tb: "أعلى/أسفل", depth: "العمق", eye_dist: "المسافة بين العينين" },
        settings: { title: "إعدادات متقدمة", tabs: { general: "عام", playback: "التشغيل" }, sidebar: { list: "منطقة القائمة", hotkey: "اختصارات", screenshot: "لقطات", file_assoc: "ربط الملفات", playback_basic: "تشغيل أساسي" }, playback: { title: "تشغيل أساسي", step_group: "تقديم/ترجيع", forward_once: "تقديم مرة", rewind_once: "ترجيع مرة", speed_group: "السرعة", speed_once: "السرعة", playlist_group: "القائمة", continue_last: "متابعة آخر قائمة", auto_add: "إضافة مشابهة", clear_on_open: "تفريغ عند الفتح", prompt_cleanup: "تنبيه عند قائمة طويلة" }, hotkey: { title: "اختصارات", header_command: "أمر", header_mouse: "ماوس", header_key: "مفتاح", header_action: "إجراء", disable_swf: "تعطيل لـ SWF", btn_modify: "تعديل", actions: { playPause: "تشغيل/إيقاف", stop: "إيقاف", fastForward: "تقديم", rewind: "ترجيع", speedUp: "تسريع", speedDown: "إبطاء", volumeUp: "رفع الصوت", volumeDown: "خفض الصوت", mute: "كتم", fullscreen: "ملء الشاشة", exitFullscreen: "الخروج من ملء الشاشة" }, mouse_left: "نقرة يسار" }, screenshot: { title: "لقطات الشاشة", path_label: "المجلد", btn_change: "تغيير المجلد", format_label: "التنسيق", tool_label: "أداة", popup_label: "إظهار بعد اللقطة" }, file_assoc: { title: "ربط الملفات", status_checking: "جاري التحقق...", status_is_default: "المشغل الافتراضي", status_not_default: "ليس افتراضيًا", status_check_failed: "فشل التحقق", btn_set_default: "تعيين افتراضي", btn_already_set: "معيّن مسبقًا", btn_select_all: "تحديد الكل", btn_select_none: "لا شيء", btn_restore: "استعادة", always_assoc: "ربط دائمًا", formats: { wmv: "Windows Media Video", real: "Real Media", vcd: "VCD/DVD", quicktime: "QuickTime", other_video: "فيديو آخر", other_audio: "صوت آخر", animation: "رسوم متحركة", playlist: "قائمة", subtitle: "ترجمة" } }, list: { title: "منطقة القائمة", display_group: "العرض", always_expand: "توسيع دائمًا", always_close: "طي دائمًا", remember: "تذكر الحالة", a11y: "إمكانية الوصول", text_auto: "حجم النص تلقائي", text_manual: "يدوي" } },
        context_menu: { play: "تشغيل", pause: "إيقاف", stop: "إيقاف", prev: "السابق", next: "التالي", fullscreen: "ملء الشاشة", exit_fullscreen: "الخروج من ملء الشاشة", screenshot: "لقطة شاشة", picture: "صورة", audio: "صوت", open: "فتح ملف...", properties: "خصائص", settings: "إعدادات" },
        properties: { title: "الخصائص", filename_empty: "لا يوجد فيديو", label_type: "النوع:", label_duration: "المدة:", label_size: "الحجم:", label_location: "الموقع:", section_video: "فيديو", label_resolution: "الدقة:", label_codec: "الترميز:", label_framerate: "إطار/ث:", label_bitrate: "معدل البت:", btn_more: "المزيد", type_video: "فيديو" },
        screenshot_preview: { title: "معاينة اللقطة", label_no_popup: "عدم الإظهار مرة أخرى", btn_save: "حفظ" },
        dlna: { title: "أجهزة DLNA", subtitle: "اختر جهاز الإخراج", searching: "جاري البحث عن أجهزة...", no_device: "لم يتم العثور على جهاز", no_device_hint: "تحديث أو التحقق من الشبكة", select_device_first: "اختر جهازًا أولاً", device_ready: "جاهز", help_guide_title: "دليل DLNA", help_guide_content: "【المتطلبات】\n• الكمبيوتر والتلفزيون على نفس Wi-Fi/LAN.\n• تفعيل DLNA/Cast على التلفزيون.\n\n【الخطوات】\n1. انقر [DLNA] أسفل.\n2. \"تحديث\" للبحث.\n3. اختر التلفزيون و\"اتصال\".\n\n【مساعدة】\n• لا جهاز: جدار ناري أو إعادة تشغيل Cast.\n• تأخير: خفض معدل البت.\n• لا يشغل: استخدم MP4/MKV.", connecting_msg: "الاتصال بـ: {{name}}\n\nيتطلب خادم DLNA. وضع تجريبي.", connecting_title: "اتصال DLNA" },
        update: {
            no_update_title: "التحقق من التحديثات",
            no_update_message: "الإصدار الحالي V{{version}} هو الأحدث",
            no_update_detail: "لم يتم العثور على إصدار أحدث. استمتع باستخدام التطبيق.",
            check_failed_title: "فشل التحقق من التحديثات",
            check_failed_message: "تعذر الاتصال بخادم التحديث: {{error}}",
            check_not_available: "ميزة التحديث غير متاحة في هذا البيئة",
            checking: "جاري التحقق من التحديثات...",
            check_failed_toast: "فشل التحقق من التحديثات، حاول مرة أخرى لاحقًا"
        },
        recent: { title: "الأخيرة", empty: "لا يوجد تشغيل حديث", empty_tip: "ستظهر الفيديوهات المشغّلة هنا", clear_all: "مسح الكل", remove_selected: "إزالة المحدد" },
        favorites: { title: "المفضلة", add_to_favorites: "إضافة إلى المفضلة", my_favorites: "مفضلاتي", empty: "لا توجد مفضلات بعد", empty_tip: "انقر بزر الماوس الأيمن واختر \"إضافة إلى المفضلة\" أثناء التشغيل", no_video: "يرجى تحديد أو تشغيل فيديو أولاً", cannot_save: "تعذرت الإضافة إلى المفضلة", added: "تمت الإضافة إلى المفضلة", remove: "إزالة من المفضلة", invalid_entry: "عنصر مفضلة غير صالح" },
        dialog: { close_confirm: "إغلاق KunQiong Player؟", close_title: "تأكيد الإغلاق", notice: "تنبيه", logout_confirm: "تسجيل الخروج؟", ok: "موافق", cancel: "إلغاء", help_doc_content: "KunQiong Player\n\nاختصارات:\nمسافة - تشغيل/إيقاف\n← / → - ترجيع/تقديم\n↑ / ↓ - الصوت\nF - ملء الشاشة\nM - كتم", shortcuts_content: "مسافة - تشغيل/إيقاف\n← - ترجيع\n→ - تقديم\n↑/↓ - الصوت\nF - ملء الشاشة\nM - كتم\nEsc - الخروج من ملء الشاشة\nCtrl+S - إيقاف", about_content: "KunQiong Player\n\nمشغل فيديو بالذكاء الاصطناعي.\n\n【الميزات】\n• صيغ متعددة\n• فك ترميز بالأجهزة\n• ضبط الصورة/الصوت\n• ترجمة مزدوجة\n• DLNA\n• وضع السينما" }
    }
};
