/**
 * বাংলা
 */
export default {
    translation: {
        app: { title: "KunQiong Player", subtitle: "Powered by KunQiong AI", custom_software: "কাস্টম সফটওয়্যার", login: "লগ ইন", not_logged_in: "অতিথি", logged_in: "লগ ইন হয়েছে", login_tip: "আরও ফিচারের জন্য লগ ইন করুন", login_action: "লগ ইন করুন", redirecting: "রিডাইরেক্ট হচ্ছে...", login_in_browser: "ব্রাউজারে লগ ইন সম্পূর্ণ করুন।", relogin: "আবার লগ ইন", login_success_sync: "লগ ইন হয়েছে। সিঙ্ক হচ্ছে...", vip_user: "সদস্য", logout: "লগ আউট", token_label: "টোকেন:", welcome_tip: "ভিডিও এখানে টেনে আনুন", loading: "লোড হচ্ছে...", screenshot_path: "স্ক্রিনশট ফোল্ডার:", global_brightness: "উজ্জ্বলতা", reset: "রিসেট", reset_all: "সব রিসেট", ok: "ঠিক আছে", cancel: "বাতিল", apply: "প্রয়োগ করুন", unit: { ms: "ms", s: "s", times: "x", items: "" } },
        menu: { file: "ফাইল", open_file: "ফাইল খুলুন...", open_folder: "ফোল্ডার খুলুন...", open_url: "URL খুলুন...", exit: "প্রস্থান", play: "চালান", play_pause: "চালান/বিরতি", stop: "বিরতি", next: "পরবর্তী", prev: "পূর্ববর্তী", fast_forward: "এগিয়ে", rewind: "পিছনে", effects: "ইফেক্ট", splitter: "স্প্লিটার", video_decoder: "ভিডিও ডিকোডার", audio_decoder: "অডিও ডিকোডার", renderer: "রেন্ডারার", auto_select: "অটো", control: "নিয়ন্ত্রণ", subtitle: "সাবটাইটেল", picture_quality: "ছবি", audio_adjust: "অডিও", settings: "সেটিংস", help: "সাহায্য", help_doc: "ডকুমেন্টেশন", shortcuts: "শর্টকাট", licenses: "তৃতীয় পক্ষের লাইসেন্স", privacy: "প্রাইভেসি", check_update: "আপডেট চেক করুন...", feedback: "ফিডব্যাক", about: "সম্পর্কে", language: "ভাষা", lang_zh: "简体中文", lang_en: "English" },
        playlist: { title: "প্লেলিস্ট", add: "যোগ করুন", clear: "মুছুন", loop: "লিস্ট লুপ", loop_list: "লিস্ট লুপ", loop_list_title: "লিস্ট লুপ", loop_single: "একটি লুপ", loop_single_title: "একটি লুপ", random: "র্যান্ডম", random_title: "র্যান্ডম", empty: "লিস্ট খালি", empty_tip: "\"যোগ করুন\" ক্লিক করুন বা ফাইল টেনে আনুন", ad_placeholder: "বিজ্ঞাপন" },
        picture: { title: "ছবি", ratio: "অনুপাত", ratio_original: "অরিজিনাল", ratio_fill: "ভরুন", rotation: "ঘোরান", flip_h: "অনুভূমিক", flip_v: "উল্লম্ব", pan: "প্যান", zoom: "জুম", presets: { default: "ডিফল্ট", bright: "উজ্জ্বল", soft: "নরম", retro: "রেট্রো" } },
        audio: { title: "অডিও", volume: "ভলিউম", channel: "চ্যানেল", channel_default: "ডিফল্ট", channel_left: "বাম", channel_right: "ডান", sync: "সিঙ্ক", track: "ট্র্যাক", track_default: "ডিফল্ট", load_track: "ট্র্যাক লোড করুন" },
        subtitle: { title: "সাবটাইটেল", main_tab: "প্রধান", sec_tab: "সেকেন্ডারি", select: "নির্বাচন", hide: "লুকান", load: "লোড করুন", enable_sec: "সেকেন্ডারি চালু করুন", style: "স্টাইল", font_yahei: "Microsoft YaHei", font_hei: "SimHei", font_song: "SimSun", font_kai: "KaiTi", sync: "সিঙ্ক", position: "অবস্থান", pos_up: "উপরে", pos_down: "নিচে", pos_left: "বাম", pos_right: "ডান", continue_effect: "সবসময় প্রয়োগ করুন", color_title: "রঙ", basic_color: "বেসিক রঙ", custom_color: "কাস্টম", cancel: "বাতিল", confirm: "নিশ্চিত করুন" },
        control: { title: "নিয়ন্ত্রণ", left_eye: "বাম চোখ", surround: "সারাউন্ড", threed: "৩D মোড", settings: "সেটিংস" },
        lefteye: { title: "বাম চোখ", view_angle: "দেখার কোণ", brightness: "উজ্জ্বলতা", contrast: "কনট্রাস্ট" },
        surround: { title: "সারাউন্ড", mode: "মোড", mode_off: "বন্ধ", mode_stereo: "স্টেরিও", intensity: "তীব্রতা", bass: "বেস" },
        threed: { title: "৩D", mode: "মোড", mode_off: "বন্ধ", mode_anaglyph: "অ্যানাগ্লিফ", mode_sbs: "পাশাপাশি", mode_tb: "উপরে/নিচে", depth: "গভীরতা", eye_dist: "চোখের দূরত্ব" },
        settings: { title: "এডভান্সড সেটিংস", tabs: { general: "সাধারণ", playback: "প্লেব্যাক" }, sidebar: { list: "লিস্ট এরিয়া", hotkey: "শর্টকাট", screenshot: "স্ক্রিনশট", file_assoc: "ফাইল অ্যাসোসিয়েশন", playback_basic: "বেসিক প্লেব্যাক" }, playback: { title: "বেসিক প্লেব্যাক", step_group: "এগিয়ে/পিছনে", forward_once: "একবার এগিয়ে", rewind_once: "একবার পিছনে", speed_group: "গতি", speed_once: "গতি", playlist_group: "প্লেলিস্ট", continue_last: "শেষ লিস্ট চালিয়ে যান", auto_add: "অনুরূপ যোগ করুন", clear_on_open: "খোলার সময় মুছুন", prompt_cleanup: "লম্বা লিস্টে ক্লিনআপ প্রস্তাব করুন" }, hotkey: { title: "শর্টকাট", header_command: "কমান্ড", header_mouse: "মাউস", header_key: "কী", header_action: "অ্যাকশন", disable_swf: "SWF এর জন্য বন্ধ", btn_modify: "পরিবর্তন করুন", actions: { playPause: "চালান/বিরতি", stop: "বিরতি", fastForward: "এগিয়ে", rewind: "পিছনে", speedUp: "দ্রুত", speedDown: "ধীর", volumeUp: "ভলিউম +", volumeDown: "ভলিউম -", mute: "মিউট", fullscreen: "ফুলস্ক্রিন", exitFullscreen: "ফুলস্ক্রিন থেকে বেরুন" }, mouse_left: "বাম ক্লিক" }, screenshot: { title: "স্ক্রিনশট", path_label: "ফোল্ডার", btn_change: "ফোল্ডার পরিবর্তন করুন", format_label: "ফরম্যাট", tool_label: "টুল", popup_label: "ক্যাপচারের পর দেখান" }, file_assoc: { title: "ফাইল অ্যাসোসিয়েশন", status_checking: "চেক করা হচ্ছে...", status_is_default: "ডিফল্ট প্লেয়ার", status_not_default: "ডিফল্ট নয়", status_check_failed: "চেক ব্যর্থ", btn_set_default: "ডিফল্ট সেট করুন", btn_already_set: "ইতিমধ্যে সেট", btn_select_all: "সব নির্বাচন", btn_select_none: "কিছুই না", btn_restore: "পুনরুদ্ধার", always_assoc: "সবসময় অ্যাসোসিয়েট করুন", formats: { wmv: "Windows Media Video", real: "Real Media", vcd: "VCD/DVD", quicktime: "QuickTime", other_video: "অন্যান্য ভিডিও", other_audio: "অন্যান্য অডিও", animation: "অ্যানিমেশন", playlist: "প্লেলিস্ট", subtitle: "সাবটাইটেল" } }, list: { title: "লিস্ট এরিয়া", display_group: "ডিসপ্লে", always_expand: "সবসময় প্রসারিত করুন", always_close: "সবসময় সংকুচিত করুন", remember: "অবস্থা মনে রাখুন", a11y: "অ্যাক্সেসিবিলিটি", text_auto: "টেক্সট সাইজ অটো", text_manual: "ম্যানুয়াল" } },
        context_menu: { play: "চালান", pause: "বিরতি", stop: "বিরতি", prev: "পূর্ববর্তী", next: "পরবর্তী", fullscreen: "ফুলস্ক্রিন", exit_fullscreen: "ফুলস্ক্রিন থেকে বেরুন", screenshot: "স্ক্রিনশট", picture: "ছবি", audio: "অডিও", open: "ফাইল খুলুন...", properties: "প্রোপার্টি", settings: "সেটিংস" },
        properties: { title: "প্রোপার্টি", filename_empty: "কোনো ভিডিও নেই", label_type: "টাইপ:", label_duration: "সময়:", label_size: "সাইজ:", label_location: "লোকেশন:", section_video: "ভিডিও", label_resolution: "রেজোলিউশন:", label_codec: "কোডেক:", label_framerate: "FPS:", label_bitrate: "বিটরেট:", btn_more: "আরও", type_video: "ভিডিও" },
        screenshot_preview: { title: "স্ক্রিনশট প্রিভিউ", label_no_popup: "আর দেখাবেন না", btn_save: "সেভ করুন" },
        dlna: { title: "DLNA ডিভাইস", subtitle: "আউটপুট ডিভাইস নির্বাচন করুন", searching: "ডিভাইস খুঁজছে...", no_device: "কোনো ডিভাইস পাওয়া যায়নি", no_device_hint: "রিফ্রেশ বা নেটওয়ার্ক চেক করুন", select_device_first: "প্রথমে ডিভাইস নির্বাচন করুন", device_ready: "প্রস্তুত", help_guide_title: "DLNA গাইড", help_guide_content: "【প্রয়োজনীয়তা】\n• PC এবং TV একই Wi-Fi/LAN এ।\n• TV তে DLNA/Cast চালু করুন।\n\n【ধাপ】\n1. নিচে [DLNA] ক্লিক করুন।\n2. খোঁজার জন্য \"রিফ্রেশ\"।\n3. TV নির্বাচন করে \"কানেক্ট\"।\n\n【সাহায্য】\n• ডিভাইস নেই: ফায়ারওয়াল বা Cast রিস্টার্ট।\n• ল্যাগ: বিটরেট কমান।\n• চালায় না: MP4/MKV ব্যবহার করুন।", connecting_msg: "কানেক্ট হচ্ছে: {{name}}\n\nDLNA সার্ভার দরকার। ডেমো মোড।", connecting_title: "DLNA কানেকশন" },
        update: { no_update_title: "আপডেট পরীক্ষা করুন", no_update_message: "বর্তমান সংস্করণ V{{version}} ইতিমধ্যে সর্বশেষ", no_update_detail: "কোনো নতুন সংস্করণ পাওয়া যায়নি। অ্যাপ ব্যবহারের মজা নিন।", check_failed_title: "আপডেট পরীক্ষা ব্যর্থ", check_failed_message: "আপডেট সার্ভারে সংযোগ করা যাচ্ছে না: {{error}}", check_not_available: "এই পরিবেশে আপডেট বৈশিষ্ট্য উপলব্ধ নয়", checking: "আপডেট পরীক্ষা করা হচ্ছে...", check_failed_toast: "আপডেট পরীক্ষা ব্যর্থ, পরে আবার চেষ্টা করুন" },
        recent: { title: "সাম্প্রতিক", empty: "এখনও সাম্প্রতিক প্লেব্যাক নেই", empty_tip: "চালানো ভিডিওগুলি এখানে দেখা যাবে", clear_all: "সব সাফ করুন", remove_selected: "নির্বাচিত সরান" },
        favorites: { title: "প্রিয়", add_to_favorites: "প্রিয়তে যোগ করুন", my_favorites: "আমার প্রিয়", empty: "এখনও কোনো প্রিয় নেই", empty_tip: "চালানোর সময় রাইট-ক্লিক করে \"প্রিয়তে যোগ করুন\" বেছে নিন", no_video: "প্রথমে একটি ভিডিও নির্বাচন বা চালান", cannot_save: "প্রিয়তে যোগ করা যাচ্ছে না", added: "প্রিয়তে যোগ করা হয়েছে", remove: "প্রিয় থেকে সরান", invalid_entry: "অবৈধ প্রিয় এন্ট্রি" },
        dialog: { close_confirm: "KunQiong Player বন্ধ করবেন?", close_title: "বন্ধ নিশ্চিত করুন", notice: "নোটিশ", logout_confirm: "লগ আউট করবেন?", ok: "ঠিক আছে", cancel: "বাতিল", help_doc_content: "KunQiong Player\n\nশর্টকাট:\nস্পেস - চালান/বিরতি\n← / → - পিছনে/এগিয়ে\n↑ / ↓ - ভলিউম\nF - ফুলস্ক্রিন\nM - মিউট", shortcuts_content: "স্পেস - চালান/বিরতি\n← - পিছনে\n→ - এগিয়ে\n↑/↓ - ভলিউম\nF - ফুলস্ক্রিন\nM - মিউট\nEsc - ফুলস্ক্রিন থেকে বেরুন\nCtrl+S - বিরতি", about_content: "KunQiong Player\n\nAI ভিডিও প্লেয়ার।\n\n【ফিচার】\n• একাধিক ফরম্যাট\n• হার্ডওয়্যার ডিকোডিং\n• ছবি/অডিও অ্যাডজাস্টমেন্ট\n• ডাবল সাবটাইটেল\n• DLNA\n• সিনেমা মোড" }
    }
};
