/**
 * Español
 */
export default {
    translation: {
        app: { title: "KunQiong Player", subtitle: "Powered by KunQiong AI", custom_software: "Software personalizado", login: "Iniciar sesión", not_logged_in: "Invitado", logged_in: "Conectado", login_tip: "Inicia sesión para más funciones", login_action: "Iniciar sesión", redirecting: "Redirigiendo...", login_in_browser: "Completa el inicio de sesión en el navegador.", relogin: "Volver a iniciar sesión", login_success_sync: "Sesión iniciada. Sincronizando...", vip_user: "Miembro", logout: "Cerrar sesión", token_label: "Token:", welcome_tip: "Arrastra archivos de vídeo aquí", loading: "Cargando...", screenshot_path: "Ruta de capturas:", global_brightness: "Brillo", reset: "Restablecer", reset_all: "Restablecer todo", ok: "OK", cancel: "Cancelar", apply: "Aplicar", unit: { ms: "ms", s: "s", times: "x", items: "" } },
        menu: { file: "Archivo", open_file: "Abrir archivo...", open_folder: "Abrir carpeta...", open_url: "Abrir URL...", exit: "Salir", play: "Reproducir", play_pause: "Reproducir/Pausar", stop: "Detener", next: "Siguiente", prev: "Anterior", fast_forward: "Avanzar", rewind: "Retroceder", effects: "Efectos", splitter: "Splitter", video_decoder: "Decodificador de vídeo", audio_decoder: "Decodificador de audio", renderer: "Renderizador", auto_select: "Auto", control: "Control", subtitle: "Subtítulos", picture_quality: "Imagen", audio_adjust: "Audio", settings: "Ajustes", help: "Ayuda", help_doc: "Documentación", shortcuts: "Atajos", licenses: "Licencias de terceros", privacy: "Privacidad", check_update: "Buscar actualizaciones...", feedback: "Comentarios", about: "Acerca de", language: "Idioma", lang_zh: "简体中文", lang_en: "English" },
        playlist: { title: "Lista de reproducción", add: "Añadir", clear: "Borrar", loop: "Repetir lista", loop_list: "Repetir lista", loop_list_title: "Repetir lista", loop_single: "Repetir una", loop_single_title: "Repetir una", random: "Aleatorio", random_title: "Aleatorio", empty: "Lista vacía", empty_tip: "Haz clic en \"Añadir\" o arrastra archivos", ad_placeholder: "Anuncio" },
        picture: { title: "Ajuste de imagen", ratio: "Relación", ratio_original: "Original", ratio_fill: "Rellenar", rotation: "Rotación", flip_h: "Horizontal", flip_v: "Vertical", pan: "Pan", zoom: "Zoom", presets: { default: "Por defecto", bright: "Brillo", soft: "Suave", retro: "Retro" } },
        audio: { title: "Audio", volume: "Volumen", channel: "Canal", channel_default: "Por defecto", channel_left: "Izquierdo", channel_right: "Derecho", sync: "Sincronizar", track: "Pista", track_default: "Por defecto", load_track: "Cargar pista" },
        subtitle: { title: "Subtítulos", main_tab: "Principal", sec_tab: "Secundario", select: "Selección", hide: "Ocultar", load: "Cargar", enable_sec: "Activar secundario", style: "Estilo", font_yahei: "Microsoft YaHei", font_hei: "SimHei", font_song: "SimSun", font_kai: "KaiTi", sync: "Sincronizar", position: "Posición", pos_up: "Arriba", pos_down: "Abajo", pos_left: "Izquierda", pos_right: "Derecha", continue_effect: "Aplicar siempre", color_title: "Color", basic_color: "Colores básicos", custom_color: "Personalizado", cancel: "Cancelar", confirm: "Confirmar" },
        control: { title: "Control", left_eye: "Ojo izquierdo", surround: "Surround", threed: "Modo 3D", settings: "Ajustes" },
        lefteye: { title: "Ojo izquierdo", view_angle: "Ángulo", brightness: "Brillo", contrast: "Contraste" },
        surround: { title: "Surround", mode: "Modo", mode_off: "Apagado", mode_stereo: "Estéreo", intensity: "Intensidad", bass: "Graves" },
        threed: { title: "3D", mode: "Modo", mode_off: "Apagado", mode_anaglyph: "Anáglifo", mode_sbs: "Lado a lado", mode_tb: "Arriba/abajo", depth: "Profundidad", eye_dist: "Distancia ocular" },
        settings: { title: "Ajustes avanzados", tabs: { general: "General", playback: "Reproducción" }, sidebar: { list: "Área de lista", hotkey: "Atajos", screenshot: "Capturas", file_assoc: "Asociar archivos", playback_basic: "Reproducción básica" }, playback: { title: "Reproducción básica", step_group: "Avanzar/Retroceder", forward_once: "Avanzar una vez", rewind_once: "Retroceder una vez", speed_group: "Velocidad", speed_once: "Velocidad", playlist_group: "Lista", continue_last: "Continuar última lista", auto_add: "Añadir similares", clear_on_open: "Vaciar al abrir", prompt_cleanup: "Avisar si lista larga" }, hotkey: { title: "Atajos", header_command: "Comando", header_mouse: "Ratón", header_key: "Tecla", header_action: "Acción", disable_swf: "Desactivar en SWF", btn_modify: "Modificar", actions: { playPause: "Reproducir/Pausar", stop: "Detener", fastForward: "Avanzar", rewind: "Retroceder", speedUp: "Acelerar", speedDown: "Ralentizar", volumeUp: "Subir volumen", volumeDown: "Bajar volumen", mute: "Silencio", fullscreen: "Pantalla completa", exitFullscreen: "Salir de pantalla completa" }, mouse_left: "Clic izquierdo" }, screenshot: { title: "Capturas", path_label: "Ruta", btn_change: "Cambiar ruta", format_label: "Formato", tool_label: "Herramienta", popup_label: "Mostrar tras captura" }, file_assoc: { title: "Asociar archivos", status_checking: "Comprobando...", status_is_default: "Reproductor predeterminado", status_not_default: "No es predeterminado", status_check_failed: "Error al comprobar", btn_set_default: "Establecer predeterminado", btn_already_set: "Ya establecido", btn_select_all: "Seleccionar todo", btn_select_none: "Ninguno", btn_restore: "Restaurar", always_assoc: "Asociar siempre", formats: { wmv: "Windows Media Video", real: "Real Media", vcd: "VCD/DVD", quicktime: "QuickTime", other_video: "Otro vídeo", other_audio: "Otro audio", animation: "Animación", playlist: "Lista", subtitle: "Subtítulos" } }, list: { title: "Área de lista", display_group: "Visualización", always_expand: "Expandir siempre", always_close: "Cerrar siempre", remember: "Recordar estado", a11y: "Accesibilidad", text_auto: "Tamaño de texto auto", text_manual: "Tamaño manual" } },
        context_menu: { play: "Reproducir", pause: "Pausar", stop: "Detener", prev: "Anterior", next: "Siguiente", fullscreen: "Pantalla completa", exit_fullscreen: "Salir de pantalla completa", screenshot: "Captura", pip: "Picture-in-Picture", exit_pip: "Salir de PiP", pip_unsupported: "PiP no soportado en este entorno", pip_no_video: "Añade y reproduce un vídeo primero", picture: "Imagen", audio: "Audio", open: "Abrir archivo...", properties: "Propiedades", settings: "Ajustes" },
        ab_loop: { set_a: "Punto A", set_b: "Punto B", clear: "Borrar A-B", toggle_on: "Bucle A-B", toggle_off: "Salir bucle A-B", no_video: "Reproduce un vídeo primero", b_after_a: "B debe ser después de A", set_ab_first: "Establece A y B primero" },
        recent: { title: "Recientes", empty: "Sin reproducciones recientes", empty_tip: "Los vídeos reproducidos aparecerán aquí", clear_all: "Borrar todo", remove_selected: "Quitar selección" },
        favorites: { title: "Favoritos", add_to_favorites: "Añadir a favoritos", my_favorites: "Mis favoritos", empty: "Sin favoritos", empty_tip: "Clic derecho y «Añadir a favoritos» al reproducir", no_video: "Selecciona o reproduce un vídeo primero", cannot_save: "No se puede añadir a favoritos", added: "Añadido a favoritos", remove: "Quitar de favoritos", invalid_entry: "Entrada inválida" },
        properties: { title: "Propiedades", filename_empty: "Sin vídeo cargado", label_type: "Tipo:", label_duration: "Duración:", label_size: "Tamaño:", label_location: "Ubicación:", section_video: "Vídeo", label_resolution: "Resolución:", label_codec: "Códec:", label_framerate: "FPS:", label_bitrate: "Bitrate:", btn_more: "Más", type_video: "Vídeo" },
        screenshot_preview: { title: "Vista previa", label_no_popup: "No volver a mostrar", btn_save: "Guardar" },
        dlna: { title: "Dispositivos DLNA", subtitle: "Seleccionar dispositivo", searching: "Buscando...", no_device: "No se encontró dispositivo", no_device_hint: "Actualizar o comprobar red", select_device_first: "Selecciona un dispositivo", device_ready: "Listo", help_guide_title: "Guía DLNA", help_guide_content: "【Requisitos】\n• PC y TV en el mismo Wi-Fi/LAN.\n• Activar DLNA/Cast en el TV.\n\n【Pasos】\n1. Clic en [DLNA] abajo.\n2. \"Actualizar\" para buscar.\n3. Elegir TV y \"Conectar\".\n\n【Ayuda】\n• Sin dispositivo: firewall o reiniciar Cast.\n• Retardo: bajar bitrate.\n• No reproduce: usar MP4/MKV.", connecting_msg: "Conectando a: {{name}}\n\nRequiere servidor DLNA. Modo demo.", connecting_title: "Conexión DLNA" },
        update: {
            no_update_title: "Buscar actualizaciones",
            no_update_message: "La versión actual V{{version}} está actualizada",
            no_update_detail: "No se encontró una versión más reciente. Disfruta de la aplicación.",
            check_failed_title: "Error al buscar actualizaciones",
            check_failed_message: "No se pudo conectar con el servidor de actualizaciones: {{error}}",
            check_not_available: "La función de actualización no está disponible en este entorno",
            checking: "Buscando actualizaciones...",
            check_failed_toast: "Error al buscar actualizaciones. Inténtalo de nuevo más tarde"
        },
        dialog: { close_confirm: "¿Cerrar KunQiong Player?", close_title: "Confirmar cierre", notice: "Aviso", logout_confirm: "¿Cerrar sesión?", ok: "OK", cancel: "Cancelar", help_doc_content: "KunQiong Player\n\nAtajos:\nEspacio - Reproducir/Pausar\n← / → - Atrás/Adelante\n↑ / ↓ - Volumen\nF - Pantalla completa\nM - Silencio", shortcuts_content: "Espacio - Reproducir/Pausar\n← - Atrás\n→ - Adelante\n↑/↓ - Volumen\nF - Pantalla completa\nM - Silencio\nEsc - Salir pantalla completa\nCtrl+S - Detener", about_content: "KunQiong Player\n\nReproductor de vídeo con IA.\n\n【Funciones】\n• Múltiples formatos\n• Decodificación por hardware\n• Ajuste de imagen/audio\n• Subtítulos dobles\n• DLNA\n• Modo cine", resume_from: "Reanudar desde {{time}}", resume_prompt: "No terminaste: \"{{name}}\". ¿Reanudar?", resume_title: "Reanudar", resume_yes: "Reanudar", resume_auto_close: "Cerrar en {{seconds}}s", licenses_content: "【Third-Party Components and Licenses】\n\nThis software uses: Electron (MIT), FFmpeg/FFprobe (LGPL/GPL), i18next (MIT), Font Awesome (CC BY 4.0). Full texts on their official sites.", privacy_content: "【Privacy】\n\n• Local playback: no upload of files or history.\n• Login: only data needed for auth/sync.\n• Updates: version check only.\n• Feedback: for support and improvement only. We do not collect viewing history." }
    }
};
