/**
 * Français
 */
export default {
    translation: {
        app: { title: "KunQiong Player", subtitle: "Powered by KunQiong AI", custom_software: "Logiciel personnalisé", login: "Connexion", not_logged_in: "Invité", logged_in: "Connecté", login_tip: "Connectez-vous pour plus de fonctions", login_action: "Connexion", redirecting: "Redirection...", login_in_browser: "Veuillez vous connecter dans le navigateur.", relogin: "Reconnexion", login_success_sync: "Connexion réussie. Synchronisation...", vip_user: "Membre", logout: "Déconnexion", token_label: "Jeton :", welcome_tip: "Déposez des vidéos ici", loading: "Chargement...", screenshot_path: "Chemin des captures :", global_brightness: "Luminosité", reset: "Réinitialiser", reset_all: "Tout réinitialiser", ok: "OK", cancel: "Annuler", apply: "Appliquer", unit: { ms: "ms", s: "s", times: "x", items: "" } },
        menu: { file: "Fichier", open_file: "Ouvrir un fichier...", open_folder: "Ouvrir un dossier...", open_url: "Ouvrir une URL...", exit: "Quitter", play: "Lecture", play_pause: "Lecture/Pause", stop: "Arrêt", next: "Suivant", prev: "Précédent", fast_forward: "Avance rapide", rewind: "Retour rapide", effects: "Effets", splitter: "Splitter", video_decoder: "Décodeur vidéo", audio_decoder: "Décodeur audio", renderer: "Rendu", auto_select: "Auto", control: "Contrôle", subtitle: "Sous-titres", picture_quality: "Image", audio_adjust: "Audio", settings: "Paramètres", help: "Aide", help_doc: "Documentation", shortcuts: "Raccourcis", licenses: "Licences tierces", privacy: "Confidentialité", check_update: "Vérifier les mises à jour...", feedback: "Commentaires", about: "À propos", language: "Langue", lang_zh: "简体中文", lang_en: "English" },
        playlist: { title: "Liste de lecture", add: "Ajouter", clear: "Effacer", loop: "Boucle liste", loop_list: "Boucle liste", loop_list_title: "Boucle liste", loop_single: "Boucle une", loop_single_title: "Boucle une", random: "Aléatoire", random_title: "Aléatoire", empty: "Liste vide", empty_tip: "Cliquez sur « Ajouter » ou déposez des fichiers", ad_placeholder: "Annonce" },
        picture: { title: "Réglage image", ratio: "Ratio", ratio_original: "Original", ratio_fill: "Remplir", rotation: "Rotation", flip_h: "Horizontal", flip_v: "Vertical", pan: "Pan", zoom: "Zoom", presets: { default: "Par défaut", bright: "Lumineux", soft: "Doux", retro: "Rétro" } },
        audio: { title: "Audio", volume: "Volume", channel: "Canal", channel_default: "Par défaut", channel_left: "Gauche", channel_right: "Droite", sync: "Sync", track: "Piste", track_default: "Par défaut", load_track: "Charger piste" },
        subtitle: { title: "Sous-titres", main_tab: "Principal", sec_tab: "Secondaire", select: "Sélection", hide: "Masquer", load: "Charger", enable_sec: "Activer secondaire", style: "Style", font_yahei: "Microsoft YaHei", font_hei: "SimHei", font_song: "SimSun", font_kai: "KaiTi", sync: "Sync", position: "Position", pos_up: "Haut", pos_down: "Bas", pos_left: "Gauche", pos_right: "Droite", continue_effect: "Toujours appliquer", color_title: "Couleur", basic_color: "Couleurs de base", custom_color: "Personnalisé", cancel: "Annuler", confirm: "Confirmer" },
        control: { title: "Contrôle", left_eye: "Œil gauche", surround: "Surround", threed: "Mode 3D", settings: "Paramètres" },
        lefteye: { title: "Œil gauche", view_angle: "Angle", brightness: "Luminosité", contrast: "Contraste" },
        surround: { title: "Surround", mode: "Mode", mode_off: "Désactivé", mode_stereo: "Stéréo", intensity: "Intensité", bass: "Basses" },
        threed: { title: "3D", mode: "Mode", mode_off: "Désactivé", mode_anaglyph: "Anaglyphe", mode_sbs: "Côte à côte", mode_tb: "Haut/bas", depth: "Profondeur", eye_dist: "Écart des yeux" },
        settings: { title: "Paramètres avancés", tabs: { general: "Général", playback: "Lecture" }, sidebar: { list: "Zone liste", hotkey: "Raccourcis", screenshot: "Captures", file_assoc: "Associer fichiers", playback_basic: "Lecture de base" }, playback: { title: "Lecture de base", step_group: "Avance/Retour", forward_once: "Avance une fois", rewind_once: "Retour une fois", speed_group: "Vitesse", speed_once: "Vitesse", playlist_group: "Liste", continue_last: "Reprendre dernière liste", auto_add: "Ajouter fichiers similaires", clear_on_open: "Vider à l'ouverture", prompt_cleanup: "Proposer nettoyage si liste longue" }, hotkey: { title: "Raccourcis", header_command: "Commande", header_mouse: "Souris", header_key: "Touche", header_action: "Action", disable_swf: "Désactiver pour SWF", btn_modify: "Modifier", actions: { playPause: "Lecture/Pause", stop: "Arrêt", fastForward: "Avance", rewind: "Retour", speedUp: "Accélérer", speedDown: "Ralentir", volumeUp: "Volume +", volumeDown: "Volume -", mute: "Muet", fullscreen: "Plein écran", exitFullscreen: "Quitter plein écran" }, mouse_left: "Clic gauche" }, screenshot: { title: "Captures", path_label: "Chemin", btn_change: "Changer chemin", format_label: "Format", tool_label: "Outil", popup_label: "Afficher après capture" }, file_assoc: { title: "Associer fichiers", status_checking: "Vérification...", status_is_default: "Lecteur par défaut", status_not_default: "Pas par défaut", status_check_failed: "Échec vérification", btn_set_default: "Définir par défaut", btn_already_set: "Déjà défini", btn_select_all: "Tout", btn_select_none: "Aucun", btn_restore: "Par défaut", always_assoc: "Toujours associer", formats: { wmv: "Windows Media Video", real: "Real Media", vcd: "VCD/DVD", quicktime: "QuickTime", other_video: "Autre vidéo", other_audio: "Autre audio", animation: "Animation", playlist: "Liste", subtitle: "Sous-titres" } }, list: { title: "Zone liste", display_group: "Affichage", always_expand: "Toujours déplier", always_close: "Toujours replier", remember: "Mémoriser état", a11y: "Accessibilité", text_auto: "Taille texte auto", text_manual: "Taille manuelle" } },
        context_menu: { play: "Lecture", pause: "Pause", stop: "Arrêt", prev: "Précédent", next: "Suivant", fullscreen: "Plein écran", exit_fullscreen: "Quitter plein écran", screenshot: "Capture", pip: "Picture-in-Picture", exit_pip: "Quitter PiP", pip_unsupported: "PiP non pris en charge", pip_no_video: "Veuillez d'abord ajouter et lire une vidéo", picture: "Image", audio: "Audio", open: "Ouvrir fichier...", properties: "Propriétés", settings: "Paramètres" },
        ab_loop: { set_a: "Point A", set_b: "Point B", clear: "Effacer A-B", toggle_on: "Boucle A-B", toggle_off: "Quitter boucle A-B", no_video: "Lisez d'abord une vidéo", b_after_a: "B doit être après A", set_ab_first: "Définir A et B d'abord" },
        recent: { title: "Récent", empty: "Aucune lecture récente", empty_tip: "Les vidéos lues apparaîtront ici", clear_all: "Tout effacer", remove_selected: "Retirer la sélection" },
        favorites: { title: "Favoris", add_to_favorites: "Ajouter aux favoris", my_favorites: "Mes favoris", empty: "Aucun favori", empty_tip: "Clic droit et « Ajouter aux favoris » pendant la lecture", no_video: "Sélectionnez ou lisez une vidéo d'abord", cannot_save: "Impossible d'ajouter aux favoris", added: "Ajouté aux favoris", remove: "Retirer des favoris", invalid_entry: "Entrée invalide" },
        properties: { title: "Propriétés", filename_empty: "Aucune vidéo chargée", label_type: "Type :", label_duration: "Durée :", label_size: "Taille :", label_location: "Emplacement :", section_video: "Vidéo", label_resolution: "Résolution :", label_codec: "Codec :", label_framerate: "FPS :", label_bitrate: "Débit :", btn_more: "Plus", type_video: "Vidéo" },
        screenshot_preview: { title: "Aperçu capture", label_no_popup: "Ne plus afficher", btn_save: "Enregistrer" },
        dlna: { title: "Appareils DLNA", subtitle: "Choisir l'appareil de sortie", searching: "Recherche d'appareils...", no_device: "Aucun appareil trouvé", no_device_hint: "Actualiser ou vérifier le réseau", select_device_first: "Veuillez sélectionner un appareil", device_ready: "Prêt", help_guide_title: "Guide DLNA", help_guide_content: "【Conditions】\n• PC et TV sur le même Wi-Fi/LAN.\n• Activer DLNA/Cast sur la TV.\n\n【Étapes】\n1. Cliquer sur [DLNA] en bas.\n2. « Actualiser » pour rechercher.\n3. Choisir la TV et « Connecter ».\n\n【Aide】\n• Aucun appareil : pare-feu ou redémarrer Cast.\n• Saccades : réduire le débit.\n• Ne lit pas : privilégier MP4/MKV.", connecting_msg: "Connexion à : {{name}}\n\nServeur DLNA requis. Mode démo.", connecting_title: "Connexion DLNA" },
        update: {
            no_update_title: "Rechercher des mises à jour",
            no_update_message: "La version actuelle V{{version}} est à jour",
            no_update_detail: "Aucune version plus récente trouvée. Profitez de l'application.",
            check_failed_title: "Échec de la recherche de mise à jour",
            check_failed_message: "Impossible de se connecter au serveur de mise à jour : {{error}}",
            check_not_available: "La fonction de mise à jour n'est pas disponible dans cet environnement",
            checking: "Recherche des mises à jour...",
            check_failed_toast: "Échec de la recherche de mise à jour. Veuillez réessayer plus tard"
        },
        dialog: { close_confirm: "Quitter KunQiong Player ?", close_title: "Confirmer la fermeture", notice: "Notice", logout_confirm: "Déconnexion ?", ok: "OK", cancel: "Annuler", help_doc_content: "KunQiong Player\n\nRaccourcis :\nEspace - Lecture/Pause\n← / → - Retour/Avance\n↑ / ↓ - Volume\nF - Plein écran\nM - Muet", shortcuts_content: "Espace - Lecture/Pause\n← - Retour\n→ - Avance\n↑/↓ - Volume\nF - Plein écran\nM - Muet\nEsc - Quitter plein écran\nCtrl+S - Arrêt", about_content: "KunQiong Player\n\nLecteur vidéo avec IA.\n\n【Fonctions】\n• Plusieurs formats\n• Décodage matériel\n• Réglage image/audio\n• Sous-titres doubles\n• DLNA\n• Mode cinéma", resume_from: "Repris à {{time}}", resume_prompt: "Dernière fois non terminé : « {{name}} ». Reprendre ?", resume_title: "Reprendre", resume_yes: "Reprendre", resume_auto_close: "Fermeture dans {{seconds}}s", licenses_content: "【Composants et licences tiers】\n\nCe logiciel utilise : Electron (MIT), FFmpeg/FFprobe (LGPL/GPL), i18next (MIT), Font Awesome (CC BY 4.0). Textes complets sur leurs sites.", privacy_content: "【Confidentialité】\n\n• Lecture locale : pas d'envoi de fichiers ni d'historique.\n• Connexion : uniquement les données nécessaires.\n• Mises à jour : vérification de version uniquement.\n• Commentaires : pour support et amélioration uniquement. Nous ne collectons pas l'historique de visionnage." }
    }
};
