/**
 * עברית
 */
export default {
    translation: {
        app: { title: "KunQiong Player", subtitle: "Powered by KunQiong AI", custom_software: "תוכנה מותאמת", login: "התחברות", not_logged_in: "אורח", logged_in: "מחובר", login_tip: "התחבר לפונקציות נוספות", login_action: "התחבר", redirecting: "מפנה...", login_in_browser: "השלם התחברות בדפדפן.", relogin: "התחבר שוב", login_success_sync: "התחברת. מסנכרן...", vip_user: "חבר", logout: "התנתק", token_label: "טוקן:", welcome_tip: "גרור וידאו לכאן", loading: "טוען...", screenshot_path: "תיקיית צילומי מסך:", global_brightness: "בהירות", reset: "איפוס", reset_all: "איפוס הכל", ok: "אישור", cancel: "ביטול", apply: "החל", unit: { ms: "ms", s: "s", times: "x", items: "" } },
        menu: { file: "קובץ", open_file: "פתח קובץ...", open_folder: "פתח תיקייה...", open_url: "פתח URL...", exit: "יציאה", play: "הפעל", play_pause: "הפעל/השהה", stop: "עצור", next: "הבא", prev: "הקודם", fast_forward: "קדימה", rewind: "אחורה", effects: "אפקטים", splitter: "מפצל", video_decoder: "מפענח וידאו", audio_decoder: "מפענח אודיו", renderer: "רנדרר", auto_select: "אוטו", control: "בקרה", subtitle: "כתוביות", picture_quality: "תמונה", audio_adjust: "אודיו", settings: "הגדרות", help: "עזרה", help_doc: "תיעוד", shortcuts: "קיצורי מקלדת", licenses: "רישיונות צד שלישי", privacy: "פרטיות", check_update: "בדוק עדכונים...", feedback: "משוב", about: "אודות", language: "שפה", lang_zh: "简体中文", lang_en: "English" },
        playlist: { title: "רשימת השמעה", add: "הוסף", clear: "נקה", loop: "חזור על רשימה", loop_list: "חזור על רשימה", loop_list_title: "חזור על רשימה", loop_single: "חזור על אחד", loop_single_title: "חזור על אחד", random: "אקראי", random_title: "אקראי", empty: "הרשימה ריקה", empty_tip: "לחץ \"הוסף\" או גרור קבצים", ad_placeholder: "פרסומת" },
        picture: { title: "תמונה", ratio: "יחס", ratio_original: "מקורי", ratio_fill: "מלא", rotation: "סיבוב", flip_h: "אופקי", flip_v: "אנכי", pan: "פאן", zoom: "זום", presets: { default: "ברירת מחדל", bright: "בהיר", soft: "רך", retro: "רטרו" } },
        audio: { title: "אודיו", volume: "עוצמה", channel: "ערוץ", channel_default: "ברירת מחדל", channel_left: "שמאל", channel_right: "ימין", sync: "סנכרון", track: "מסלול", track_default: "ברירת מחדל", load_track: "טען מסלול" },
        subtitle: { title: "כתוביות", main_tab: "ראשי", sec_tab: "משני", select: "בחירה", hide: "הסתר", load: "טען", enable_sec: "הפעל משני", style: "סגנון", font_yahei: "Microsoft YaHei", font_hei: "SimHei", font_song: "SimSun", font_kai: "KaiTi", sync: "סנכרון", position: "מיקום", pos_up: "למעלה", pos_down: "למטה", pos_left: "שמאל", pos_right: "ימין", continue_effect: "החל תמיד", color_title: "צבע", basic_color: "צבעים בסיסיים", custom_color: "מותאם", cancel: "ביטול", confirm: "אישור" },
        control: { title: "בקרה", left_eye: "עין שמאל", surround: "סראונד", threed: "מצב 3D", settings: "הגדרות" },
        lefteye: { title: "עין שמאל", view_angle: "זווית צפייה", brightness: "בהירות", contrast: "ניגודיות" },
        surround: { title: "סראונד", mode: "מצב", mode_off: "כבוי", mode_stereo: "סטריאו", intensity: "עוצמה", bass: "בס" },
        threed: { title: "3D", mode: "מצב", mode_off: "כבוי", mode_anaglyph: "אנאגליף", mode_sbs: "צד אל צד", mode_tb: "למעלה/למטה", depth: "עומק", eye_dist: "מרחק עיניים" },
        settings: { title: "הגדרות מתקדמות", tabs: { general: "כללי", playback: "השמעה" }, sidebar: { list: "אזור רשימה", hotkey: "קיצורי מקלדת", screenshot: "צילומי מסך", file_assoc: "שיוך קבצים", playback_basic: "השמעה בסיסית" }, playback: { title: "השמעה בסיסית", step_group: "קדימה/אחורה", forward_once: "פעם אחת קדימה", rewind_once: "פעם אחת אחורה", speed_group: "מהירות", speed_once: "מהירות", playlist_group: "רשימה", continue_last: "המשך רשימה אחרונה", auto_add: "הוסף דומים", clear_on_open: "נקה בפתיחה", prompt_cleanup: "הצע ניקוי" }, hotkey: { title: "קיצורי מקלדת", header_command: "פקודה", header_mouse: "עכבר", header_key: "מקש", header_action: "פעולה", disable_swf: "כבוי ל-SWF", btn_modify: "שנה", actions: { playPause: "הפעל/השהה", stop: "עצור", fastForward: "קדימה", rewind: "אחורה", speedUp: "האץ", speedDown: "האט", volumeUp: "עוצמה +", volumeDown: "עוצמה -", mute: "השתק", fullscreen: "מסך מלא", exitFullscreen: "צא ממסך מלא" }, mouse_left: "לחיצה שמאל" }, screenshot: { title: "צילומי מסך", path_label: "תיקייה", btn_change: "שנה תיקייה", format_label: "פורמט", tool_label: "כלי", popup_label: "הצג אחרי צילום" }, file_assoc: { title: "שיוך קבצים", status_checking: "בודק...", status_is_default: "נגן ברירת מחדל", status_not_default: "לא ברירת מחדל", status_check_failed: "בדיקה נכשלה", btn_set_default: "הגדר כברירת מחדל", btn_already_set: "כבר הוגדר", btn_select_all: "בחר הכל", btn_select_none: "כלום", btn_restore: "שחזר", always_assoc: "שייך תמיד", formats: { wmv: "Windows Media Video", real: "Real Media", vcd: "VCD/DVD", quicktime: "QuickTime", other_video: "וידאו אחר", other_audio: "אודיו אחר", animation: "אנימציה", playlist: "רשימה", subtitle: "כתוביות" } }, list: { title: "אזור רשימה", display_group: "תצוגה", always_expand: "תמיד הרחב", always_close: "תמיד כווץ", remember: "זכור מצב", a11y: "נגישות", text_auto: "גודל טקסט אוטו", text_manual: "ידני" } },
        context_menu: { play: "הפעל", pause: "השהה", stop: "עצור", prev: "הקודם", next: "הבא", fullscreen: "מסך מלא", exit_fullscreen: "צא ממסך מלא", screenshot: "צילום מסך", picture: "תמונה", audio: "אודיו", open: "פתח קובץ...", properties: "מאפיינים", settings: "הגדרות" },
        properties: { title: "מאפיינים", filename_empty: "אין וידאו", label_type: "סוג:", label_duration: "משך:", label_size: "גודל:", label_location: "מיקום:", section_video: "וידאו", label_resolution: "רזולוציה:", label_codec: "קודק:", label_framerate: "FPS:", label_bitrate: "ביטרייט:", btn_more: "עוד", type_video: "וידאו" },
        screenshot_preview: { title: "תצוגה מקדימה של צילום", label_no_popup: "אל תציג שוב", btn_save: "שמור" },
        dlna: { title: "מכשירי DLNA", subtitle: "בחר מכשיר פלט", searching: "מחפש מכשירים...", no_device: "לא נמצא מכשיר", no_device_hint: "רענן או בדוק רשת", select_device_first: "בחר קודם מכשיר", device_ready: "מוכן", help_guide_title: "מדריך DLNA", help_guide_content: "【דרישות】\n• מחשב וטלוויזיה באותו Wi-Fi/LAN.\n• הפעל DLNA/Cast בטלוויזיה.\n\n【שלבים】\n1. לחץ [DLNA] למטה.\n2. \"רענן\" לחיפוש.\n3. בחר טלוויזיה ו\"התחבר\".\n\n【עזרה】\n• אין מכשיר: חומת אש או הפעל מחדש Cast.\n• השהייה: הורד ביטרייט.\n• לא מנגן: השתמש ב-MP4/MKV.", connecting_msg: "מתחבר ל: {{name}}\n\nנדרש שרת DLNA. מצב דמו.", connecting_title: "חיבור DLNA" },
        update: {
            no_update_title: "בדיקת עדכונים",
            no_update_message: "הגרסה הנוכחית V{{version}} היא העדכנית ביותר",
            no_update_detail: "לא נמצא עדכון חדש. תהנה מהשימוש באפליקציה.",
            check_failed_title: "בדיקת העדכונים נכשלה",
            check_failed_message: "לא ניתן להתחבר לשרת העדכונים: {{error}}",
            check_not_available: "פונקציית העדכון אינה זמינה בסביבה זו",
            checking: "בודק עדכונים...",
            check_failed_toast: "בדיקת העדכונים נכשלה, נסה שוב מאוחר יותר"
        },
        recent: { title: "אחרונים", empty: "אין השמעה אחרונה", empty_tip: "סרטונים שהושמעו יופיעו כאן", clear_all: "נקה הכל", remove_selected: "הסר נבחרים" },
        favorites: { title: "מועדפים", add_to_favorites: "הוסף למועדפים", my_favorites: "המועדפים שלי", empty: "אין עדיין מועדפים", empty_tip: "לחץ ימני ובחר \"הוסף למועדפים\" במהלך ההשמעה", no_video: "בחר או השמע סרטון קודם", cannot_save: "לא ניתן להוסיף למועדפים", added: "נוסף למועדפים", remove: "הסר ממועדפים", invalid_entry: "רשימת מועדפים לא תקינה" },
        dialog: { close_confirm: "לסגור את KunQiong Player?", close_title: "אישור סגירה", notice: "הודעה", logout_confirm: "להתנתק?", ok: "אישור", cancel: "ביטול", help_doc_content: "KunQiong Player\n\nקיצורים:\nרווח - הפעל/השהה\n← / → - אחורה/קדימה\n↑ / ↓ - עוצמה\nF - מסך מלא\nM - השתק", shortcuts_content: "רווח - הפעל/השהה\n← - אחורה\n→ - קדימה\n↑/↓ - עוצמה\nF - מסך מלא\nM - השתק\nEsc - צא ממסך מלא\nCtrl+S - עצור", about_content: "KunQiong Player\n\nנגן וידאו עם AI.\n\n【פונקציות】\n• פורמטים מרובים\n• פענוח חומרה\n• התאמת תמונה/אודיו\n• כתוביות כפולות\n• DLNA\n• מצב קולנוע" }
    }
};
