/**
 * हिन्दी
 */
export default {
    translation: {
        app: { title: "KunQiong Player", subtitle: "Powered by KunQiong AI", custom_software: "कस्टम सॉफ्टवेयर", login: "लॉग इन", not_logged_in: "अतिथि", logged_in: "लॉग इन हो गया", login_tip: "अधिक सुविधाओं के लिए लॉग इन करें", login_action: "लॉग इन करें", redirecting: "रीडायरेक्ट हो रहा है...", login_in_browser: "ब्राउज़र में लॉग इन पूरा करें।", relogin: "फिर लॉग इन करें", login_success_sync: "लॉग इन हुआ। सिंक हो रहा है...", vip_user: "सदस्य", logout: "लॉग आउट", token_label: "टोकन:", welcome_tip: "वीडियो यहाँ खींचें", loading: "लोड हो रहा है...", screenshot_path: "स्क्रीनशॉट फ़ोल्डर:", global_brightness: "चमक", reset: "रीसेट", reset_all: "सब रीसेट", ok: "ठीक", cancel: "रद्द", apply: "लागू करें", unit: { ms: "ms", s: "s", times: "x", items: "" } },
        menu: { file: "फ़ाइल", open_file: "फ़ाइल खोलें...", open_folder: "फ़ोल्डर खोलें...", open_url: "URL खोलें...", exit: "बाहर", play: "चलाएं", play_pause: "चलाएं/रोकें", stop: "रोकें", next: "अगला", prev: "पिछला", fast_forward: "आगे", rewind: "पीछे", effects: "इफेक्ट", splitter: "स्प्लिटर", video_decoder: "वीडियो डिकोडर", audio_decoder: "ऑडियो डिकोडर", renderer: "रेंडरर", auto_select: "ऑटो", control: "नियंत्रण", subtitle: "उपशीर्षक", picture_quality: "चित्र", audio_adjust: "ऑडियो", settings: "सेटिंग्स", help: "सहायता", help_doc: "दस्तावेज़", shortcuts: "शॉर्टकट", licenses: "थर्ड-पार्टी लाइसेंस", privacy: "गोपनीयता", check_update: "अपडेट जांचें...", feedback: "फीडबैक", about: "के बारे में", language: "भाषा", lang_zh: "简体中文", lang_en: "English" },
        playlist: { title: "प्लेलिस्ट", add: "जोड़ें", clear: "साफ़ करें", loop: "लिस्ट दोहराएं", loop_list: "लिस्ट दोहराएं", loop_list_title: "लिस्ट दोहराएं", loop_single: "एक दोहराएं", loop_single_title: "एक दोहराएं", random: "रैंडम", random_title: "रैंडम", empty: "लिस्ट खाली", empty_tip: "\"जोड़ें\" क्लिक करें या फ़ाइलें खींचें", ad_placeholder: "विज्ञापन" },
        picture: { title: "चित्र", ratio: "अनुपात", ratio_original: "मूल", ratio_fill: "भरें", rotation: "घुमाएं", flip_h: "क्षैतिज", flip_v: "ऊर्ध्वाधर", pan: "पैन", zoom: "ज़ूम", presets: { default: "डिफ़ॉल्ट", bright: "चमकीला", soft: "नरम", retro: "रेट्रो" } },
        audio: { title: "ऑडियो", volume: "वॉल्यूम", channel: "चैनल", channel_default: "डिफ़ॉल्ट", channel_left: "बाएं", channel_right: "दाएं", sync: "सिंक", track: "ट्रैक", track_default: "डिफ़ॉल्ट", load_track: "ट्रैक लोड करें" },
        subtitle: { title: "उपशीर्षक", main_tab: "मुख्य", sec_tab: "द्वितीय", select: "चुनें", hide: "छुपाएं", load: "लोड करें", enable_sec: "द्वितीय चालू करें", style: "स्टाइल", font_yahei: "Microsoft YaHei", font_hei: "SimHei", font_song: "SimSun", font_kai: "KaiTi", sync: "सिंक", position: "स्थिति", pos_up: "ऊपर", pos_down: "नीचे", pos_left: "बाएं", pos_right: "दाएं", continue_effect: "हमेशा लागू करें", color_title: "रंग", basic_color: "मूल रंग", custom_color: "कस्टम", cancel: "रद्द", confirm: "पुष्टि" },
        control: { title: "नियंत्रण", left_eye: "बायां आंख", surround: "सराउंड", threed: "3D मोड", settings: "सेटिंग्स" },
        lefteye: { title: "बायां आंख", view_angle: "दृश्य कोण", brightness: "चमक", contrast: "कंट्रास्ट" },
        surround: { title: "सराउंड", mode: "मोड", mode_off: "बंद", mode_stereo: "स्टीरियो", intensity: "तीव्रता", bass: "बास" },
        threed: { title: "3D", mode: "मोड", mode_off: "बंद", mode_anaglyph: "एनाग्लिफ", mode_sbs: "साइड बाय साइड", mode_tb: "ऊपर/नीचे", depth: "गहराई", eye_dist: "आंख दूरी" },
        settings: { title: "उन्नत सेटिंग्स", tabs: { general: "सामान्य", playback: "प्लेबैक" }, sidebar: { list: "लिस्ट क्षेत्र", hotkey: "शॉर्टकट", screenshot: "स्क्रीनशॉट", file_assoc: "फ़ाइल संबद्धता", playback_basic: "बेसिक प्लेबैक" }, playback: { title: "बेसिक प्लेबैक", step_group: "आगे/पीछे", forward_once: "एक बार आगे", rewind_once: "एक बार पीछे", speed_group: "स्पीड", speed_once: "स्पीड", playlist_group: "प्लेलिस्ट", continue_last: "आखिरी लिस्ट जारी रखें", auto_add: "समान जोड़ें", clear_on_open: "खोलने पर साफ़ करें", prompt_cleanup: "लंबी लिस्ट पर सफाई सुझाएं" }, hotkey: { title: "शॉर्टकट", header_command: "कमांड", header_mouse: "माउस", header_key: "कुंजी", header_action: "क्रिया", disable_swf: "SWF के लिए बंद", btn_modify: "बदलें", actions: { playPause: "चलाएं/रोकें", stop: "रोकें", fastForward: "आगे", rewind: "पीछे", speedUp: "तेज़", speedDown: "धीमा", volumeUp: "वॉल्यूम +", volumeDown: "वॉल्यूम -", mute: "म्यूट", fullscreen: "फुलस्क्रीन", exitFullscreen: "फुलस्क्रीन से बाहर" }, mouse_left: "बायां क्लिक" }, screenshot: { title: "स्क्रीनशॉट", path_label: "फ़ोल्डर", btn_change: "फ़ोल्डर बदलें", format_label: "फॉर्मैट", tool_label: "टूल", popup_label: "कैप्चर के बाद दिखाएं" }, file_assoc: { title: "फ़ाइल संबद्धता", status_checking: "जांच हो रही है...", status_is_default: "डिफ़ॉल्ट प्लेयर", status_not_default: "डिफ़ॉल्ट नहीं", status_check_failed: "जांच विफल", btn_set_default: "डिफ़ॉल्ट सेट करें", btn_already_set: "पहले से सेट", btn_select_all: "सभी चुनें", btn_select_none: "कोई नहीं", btn_restore: "पुनर्स्थापित करें", always_assoc: "हमेशा संबद्ध करें", formats: { wmv: "Windows Media Video", real: "Real Media", vcd: "VCD/DVD", quicktime: "QuickTime", other_video: "अन्य वीडियो", other_audio: "अन्य ऑडियो", animation: "एनिमेशन", playlist: "प्लेलिस्ट", subtitle: "उपशीर्षक" } }, list: { title: "लिस्ट क्षेत्र", display_group: "प्रदर्शन", always_expand: "हमेशा विस्तार करें", always_close: "हमेशा संक्षिप्त करें", remember: "स्थिति याद रखें", a11y: "एक्सेसिबिलिटी", text_auto: "टेक्स्ट साइज़ ऑटो", text_manual: "मैनुअल" } },
        context_menu: { play: "चलाएं", pause: "रोकें", stop: "रोकें", prev: "पिछला", next: "अगला", fullscreen: "फुलस्क्रीन", exit_fullscreen: "फुलस्क्रीन से बाहर", screenshot: "स्क्रीनशॉट", picture: "चित्र", audio: "ऑडियो", open: "फ़ाइल खोलें...", properties: "गुण", settings: "सेटिंग्स" },
        properties: { title: "गुण", filename_empty: "कोई वीडियो नहीं", label_type: "प्रकार:", label_duration: "अवधि:", label_size: "आकार:", label_location: "स्थान:", section_video: "वीडियो", label_resolution: "रिज़ॉल्यूशन:", label_codec: "कोडेक:", label_framerate: "FPS:", label_bitrate: "बिटरेट:", btn_more: "अधिक", type_video: "वीडियो" },
        screenshot_preview: { title: "स्क्रीनशॉट पूर्वावलोकन", label_no_popup: "फिर न दिखाएं", btn_save: "सहेजें" },
        dlna: { title: "DLNA उपकरण", subtitle: "आउटपुट उपकरण चुनें", searching: "उपकरण खोज रहा है...", no_device: "कोई उपकरण नहीं मिला", no_device_hint: "रीफ्रेश करें या नेटवर्क जांचें", select_device_first: "पहले उपकरण चुनें", device_ready: "तैयार", help_guide_title: "DLNA गाइड", help_guide_content: "【आवश्यकताएं】\n• PC और TV एक ही Wi-Fi/LAN पर।\n• TV पर DLNA/Cast चालू करें।\n\n【कदम】\n1. नीचे [DLNA] क्लिक करें।\n2. खोजने के लिए \"रीफ्रेश\"।\n3. TV चुनें और \"कनेक्ट\"।\n\n【सहायता】\n• कोई उपकरण नहीं: फ़ायरवॉल या Cast रीस्टार्ट।\n• लैग: बिटरेट कम करें।\n• चलता नहीं: MP4/MKV उपयोग करें।", connecting_msg: "कनेक्ट हो रहा है: {{name}}\n\nDLNA सर्वर आवश्यक। डेमो मोड।", connecting_title: "DLNA कनेक्शन" },
        update: {
            no_update_title: "अपडेट जांचें",
            no_update_message: "वर्तमान संस्करण V{{version}} पहले से ही नवीनतम है",
            no_update_detail: "कोई नया संस्करण नहीं मिला। ऐप का आनंद लें।",
            check_failed_title: "अपडेट जांच विफल",
            check_failed_message: "अपडेट सर्वर से कनेक्ट नहीं हो सका: {{error}}",
            check_not_available: "इस वातावरण में अपडेट सुविधा उपलब्ध नहीं है",
            checking: "अपडेट की जांच की जा रही है...",
            check_failed_toast: "अपडेट जांच विफल, कृपया बाद में पुनः प्रयास करें"
        },
        recent: { title: "हाल ही में", empty: "अभी तक कोई हाल की प्लेबैक नहीं", empty_tip: "बजाए गए वीडियो यहाँ दिखेंगे", clear_all: "सब साफ करें", remove_selected: "चयनित हटाएं" },
        favorites: { title: "पसंदीदा", add_to_favorites: "पसंदीदा में जोड़ें", my_favorites: "मेरे पसंदीदा", empty: "अभी तक कोई पसंदीदा नहीं", empty_tip: "चलाते समय राइट-क्लिक करें और \"पसंदीदा में जोड़ें\" चुनें", no_video: "पहले वीडियो चुनें या चलाएं", cannot_save: "पसंदीदा में जोड़ा नहीं जा सकता", added: "पसंदीदा में जोड़ा गया", remove: "पसंदीदा से हटाएं", invalid_entry: "अमान्य पसंदीदा" },
        dialog: { close_confirm: "KunQiong Player बंद करें?", close_title: "बंद करने की पुष्टि करें", notice: "सूचना", logout_confirm: "लॉग आउट करें?", ok: "ठीक", cancel: "रद्द", help_doc_content: "KunQiong Player\n\nशॉर्टकट:\nस्पेस - चलाएं/रोकें\n← / → - पीछे/आगे\n↑ / ↓ - वॉल्यूम\nF - फुलस्क्रीन\nM - म्यूट", shortcuts_content: "स्पेस - चलाएं/रोकें\n← - पीछे\n→ - आगे\n↑/↓ - वॉल्यूम\nF - फुलस्क्रीन\nM - म्यूट\nEsc - फुलस्क्रीन से बाहर\nCtrl+S - रोकें", about_content: "KunQiong Player\n\nAI वीडियो प्लेयर।\n\n【सुविधाएं】\n• कई फॉर्मैट\n• हार्डवेयर डिकोडिंग\n• चित्र/ऑडियो समायोजन\n• दोहरे उपशीर्षक\n• DLNA\n• सिनेमा मोड" }
    }
};
