/**
 * Bahasa Indonesia
 */
export default {
    translation: {
        app: { title: "KunQiong Player", subtitle: "Powered by KunQiong AI", custom_software: "Perangkat lunak kustom", login: "Masuk", not_logged_in: "Tamu", logged_in: "Sudah masuk", login_tip: "Masuk untuk fitur lebih", login_action: "Masuk", redirecting: "Mengalihkan...", login_in_browser: "Selesaikan login di browser.", relogin: "Masuk lagi", login_success_sync: "Login berhasil. Sinkronisasi...", vip_user: "Anggota", logout: "Keluar", token_label: "Token:", welcome_tip: "Seret video ke sini", loading: "Memuat...", screenshot_path: "Folder tangkapan:", global_brightness: "Kecerahan", reset: "Atur ulang", reset_all: "Atur ulang semua", ok: "OK", cancel: "Batal", apply: "Terapkan", unit: { ms: "ms", s: "s", times: "x", items: "" } },
        menu: { file: "Berkas", open_file: "Buka berkas...", open_folder: "Buka folder...", open_url: "Buka URL...", exit: "Keluar", play: "Putar", play_pause: "Putar/Jeda", stop: "Berhenti", next: "Berikutnya", prev: "Sebelumnya", fast_forward: "Maju", rewind: "Mundur", effects: "Efek", splitter: "Splitter", video_decoder: "Dekoder video", audio_decoder: "Dekoder audio", renderer: "Renderer", auto_select: "Otomatis", control: "Kontrol", subtitle: "Subtitle", picture_quality: "Gambar", audio_adjust: "Audio", settings: "Pengaturan", help: "Bantuan", help_doc: "Dokumentasi", shortcuts: "Pintasan", licenses: "Lisensi pihak ketiga", privacy: "Privasi", check_update: "Periksa pembaruan...", feedback: "Umpan balik", about: "Tentang", language: "Bahasa", lang_zh: "简体中文", lang_en: "English" },
        playlist: { title: "Daftar putar", add: "Tambah", clear: "Hapus", loop: "Ulang daftar", loop_list: "Ulang daftar", loop_list_title: "Ulang daftar", loop_single: "Ulang satu", loop_single_title: "Ulang satu", random: "Acak", random_title: "Acak", empty: "Daftar kosong", empty_tip: "Klik \"Tambah\" atau seret berkas", ad_placeholder: "Iklan" },
        picture: { title: "Sesuaikan gambar", ratio: "Rasio", ratio_original: "Asli", ratio_fill: "Isi", rotation: "Putar", flip_h: "Horizontal", flip_v: "Vertikal", pan: "Pan", zoom: "Zoom", presets: { default: "Default", bright: "Terang", soft: "Lembut", retro: "Retro" } },
        audio: { title: "Audio", volume: "Volume", channel: "Saluran", channel_default: "Default", channel_left: "Kiri", channel_right: "Kanan", sync: "Sinkron", track: "Track", track_default: "Default", load_track: "Muat track" },
        subtitle: { title: "Subtitle", main_tab: "Utama", sec_tab: "Sekunder", select: "Pilihan", hide: "Sembunyikan", load: "Muat", enable_sec: "Aktifkan sekunder", style: "Gaya", font_yahei: "Microsoft YaHei", font_hei: "SimHei", font_song: "SimSun", font_kai: "KaiTi", sync: "Sinkron", position: "Posisi", pos_up: "Atas", pos_down: "Bawah", pos_left: "Kiri", pos_right: "Kanan", continue_effect: "Selalu terapkan", color_title: "Warna", basic_color: "Warna dasar", custom_color: "Kustom", cancel: "Batal", confirm: "Konfirmasi" },
        control: { title: "Kontrol", left_eye: "Mata kiri", surround: "Surround", threed: "Mode 3D", settings: "Pengaturan" },
        lefteye: { title: "Mata kiri", view_angle: "Sudut pandang", brightness: "Kecerahan", contrast: "Kontras" },
        surround: { title: "Surround", mode: "Mode", mode_off: "Mati", mode_stereo: "Stereo", intensity: "Intensitas", bass: "Bass" },
        threed: { title: "3D", mode: "Mode", mode_off: "Mati", mode_anaglyph: "Anaglyph", mode_sbs: "Samping", mode_tb: "Atas/bawah", depth: "Kedalaman", eye_dist: "Jarak mata" },
        settings: { title: "Pengaturan lanjutan", tabs: { general: "Umum", playback: "Pemutaran" }, sidebar: { list: "Area daftar", hotkey: "Pintasan", screenshot: "Tangkapan layar", file_assoc: "Asosiasi berkas", playback_basic: "Pemutaran dasar" }, playback: { title: "Pemutaran dasar", step_group: "Maju/Mundur", forward_once: "Maju sekali", rewind_once: "Mundur sekali", speed_group: "Kecepatan", speed_once: "Kecepatan", playlist_group: "Daftar", continue_last: "Lanjutkan daftar terakhir", auto_add: "Tambah berkas serupa", clear_on_open: "Hapus saat buka", prompt_cleanup: "Ingatkan bersihkan jika panjang" }, hotkey: { title: "Pintasan", header_command: "Perintah", header_mouse: "Mouse", header_key: "Tombol", header_action: "Aksi", disable_swf: "Nonaktifkan untuk SWF", btn_modify: "Ubah", actions: { playPause: "Putar/Jeda", stop: "Berhenti", fastForward: "Maju", rewind: "Mundur", speedUp: "Percepat", speedDown: "Perlambat", volumeUp: "Volume +", volumeDown: "Volume -", mute: "Bisukan", fullscreen: "Layar penuh", exitFullscreen: "Keluar layar penuh" }, mouse_left: "Klik kiri" }, screenshot: { title: "Tangkapan layar", path_label: "Folder", btn_change: "Ubah folder", format_label: "Format", tool_label: "Alat", popup_label: "Tampilkan setelah tangkapan" }, file_assoc: { title: "Asosiasi berkas", status_checking: "Memeriksa...", status_is_default: "Pemutar default", status_not_default: "Bukan default", status_check_failed: "Pemeriksaan gagal", btn_set_default: "Atur default", btn_already_set: "Sudah diatur", btn_select_all: "Pilih semua", btn_select_none: "Tidak ada", btn_restore: "Pulihkan", always_assoc: "Selalu asosiasikan", formats: { wmv: "Windows Media Video", real: "Real Media", vcd: "VCD/DVD", quicktime: "QuickTime", other_video: "Video lain", other_audio: "Audio lain", animation: "Animasi", playlist: "Daftar", subtitle: "Subtitle" } }, list: { title: "Area daftar", display_group: "Tampilan", always_expand: "Selalu bentangkan", always_close: "Selalu tutup", remember: "Ingat status", a11y: "Aksesibilitas", text_auto: "Ukuran teks otomatis", text_manual: "Ukuran manual" } },
        context_menu: { play: "Putar", pause: "Jeda", stop: "Berhenti", prev: "Sebelumnya", next: "Berikutnya", fullscreen: "Layar penuh", exit_fullscreen: "Keluar layar penuh", screenshot: "Tangkapan layar", picture: "Gambar", audio: "Audio", open: "Buka berkas...", properties: "Properti", settings: "Pengaturan" },
        properties: { title: "Properti", filename_empty: "Tidak ada video", label_type: "Tipe:", label_duration: "Durasi:", label_size: "Ukuran:", label_location: "Lokasi:", section_video: "Video", label_resolution: "Resolusi:", label_codec: "Codec:", label_framerate: "FPS:", label_bitrate: "Bitrate:", btn_more: "Lainnya", type_video: "Video" },
        screenshot_preview: { title: "Pratinjau tangkapan", label_no_popup: "Jangan tampilkan lagi", btn_save: "Simpan" },
        dlna: { title: "Perangkat DLNA", subtitle: "Pilih perangkat keluaran", searching: "Mencari perangkat...", no_device: "Tidak ada perangkat ditemukan", no_device_hint: "Segarkan atau periksa jaringan", select_device_first: "Pilih perangkat dulu", device_ready: "Siap", help_guide_title: "Panduan DLNA", help_guide_content: "【Persyaratan】\n• PC dan TV di Wi-Fi/LAN yang sama.\n• Aktifkan DLNA/Cast di TV.\n\n【Langkah】\n1. Klik [DLNA] di bawah.\n2. \"Segarkan\" untuk mencari.\n3. Pilih TV lalu \"Hubungkan\".\n\n【Bantuan】\n• Tidak ada perangkat: periksa firewall atau restart Cast.\n• Lag: turunkan bitrate.\n• Tidak putar: gunakan MP4/MKV.", connecting_msg: "Menghubungkan ke: {{name}}\n\nPerlu server DLNA. Mode demo.", connecting_title: "Koneksi DLNA" },
        update: {
            no_update_title: "Periksa pembaruan",
            no_update_message: "Versi saat ini V{{version}} sudah yang terbaru",
            no_update_detail: "Tidak ditemukan versi yang lebih baru. Selamat menggunakan aplikasi.",
            check_failed_title: "Gagal memeriksa pembaruan",
            check_failed_message: "Tidak dapat terhubung ke server pembaruan: {{error}}",
            check_not_available: "Fitur pembaruan tidak tersedia di lingkungan ini",
            checking: "Memeriksa pembaruan...",
            check_failed_toast: "Gagal memeriksa pembaruan, coba lagi nanti"
        },
        recent: { title: "Terbaru", empty: "Belum ada pemutaran terbaru", empty_tip: "Video yang diputar akan muncul di sini", clear_all: "Hapus semua", remove_selected: "Hapus yang dipilih" },
        favorites: { title: "Favorit", add_to_favorites: "Tambah ke favorit", my_favorites: "Favorit saya", empty: "Belum ada favorit", empty_tip: "Klik kanan dan pilih \"Tambah ke favorit\" saat memutar", no_video: "Pilih atau putar video terlebih dahulu", cannot_save: "Tidak dapat menambah ke favorit", added: "Ditambah ke favorit", remove: "Hapus dari favorit", invalid_entry: "Entri favorit tidak valid" },
        dialog: { close_confirm: "Tutup KunQiong Player?", close_title: "Konfirmasi keluar", notice: "Pemberitahuan", logout_confirm: "Keluar?", ok: "OK", cancel: "Batal", help_doc_content: "KunQiong Player\n\nPintasan:\nSpasi - Putar/Jeda\n← / → - Mundur/Maju\n↑ / ↓ - Volume\nF - Layar penuh\nM - Bisukan", shortcuts_content: "Spasi - Putar/Jeda\n← - Mundur\n→ - Maju\n↑/↓ - Volume\nF - Layar penuh\nM - Bisukan\nEsc - Keluar layar penuh\nCtrl+S - Berhenti", about_content: "KunQiong Player\n\nPemutar video dengan AI.\n\n【Fitur】\n• Banyak format\n• Dekode perangkat keras\n• Sesuaikan gambar/audio\n• Subtitle ganda\n• DLNA\n• Mode bioskop" }
    }
};
