/**
 * Italiano
 */
export default {
    translation: {
        app: { title: "KunQiong Player", subtitle: "Powered by KunQiong AI", custom_software: "Software personalizzato", login: "Accedi", not_logged_in: "Ospite", logged_in: "Connesso", login_tip: "Accedi per più funzioni", login_action: "Accedi", redirecting: "Reindirizzamento...", login_in_browser: "Completa l'accesso nel browser.", relogin: "Riaccedi", login_success_sync: "Accesso effettuato. Sincronizzazione...", vip_user: "Membro", logout: "Esci", token_label: "Token:", welcome_tip: "Trascina i video qui", loading: "Caricamento...", screenshot_path: "Cartella screenshot:", global_brightness: "Luminosità", reset: "Reimposta", reset_all: "Reimposta tutto", ok: "OK", cancel: "Annulla", apply: "Applica", unit: { ms: "ms", s: "s", times: "x", items: "" } },
        menu: { file: "File", open_file: "Apri file...", open_folder: "Apri cartella...", open_url: "Apri URL...", exit: "Esci", play: "Riproduci", play_pause: "Riproduci/Pausa", stop: "Stop", next: "Successivo", prev: "Precedente", fast_forward: "Avanti", rewind: "Indietro", effects: "Effetti", splitter: "Splitter", video_decoder: "Decodificatore video", audio_decoder: "Decodificatore audio", renderer: "Renderer", auto_select: "Auto", control: "Controllo", subtitle: "Sottotitoli", picture_quality: "Immagine", audio_adjust: "Audio", settings: "Impostazioni", help: "Aiuto", help_doc: "Documentazione", shortcuts: "Scorciatoie", licenses: "Licenze terze", privacy: "Privacy", check_update: "Controlla aggiornamenti...", feedback: "Feedback", about: "Informazioni", language: "Lingua", lang_zh: "简体中文", lang_en: "English" },
        playlist: { title: "Playlist", add: "Aggiungi", clear: "Svuota", loop: "Ripeti lista", loop_list: "Ripeti lista", loop_list_title: "Ripeti lista", loop_single: "Ripeti uno", loop_single_title: "Ripeti uno", random: "Casuale", random_title: "Casuale", empty: "Lista vuota", empty_tip: "Clicca \"Aggiungi\" o trascina file", ad_placeholder: "Pubblicità" },
        picture: { title: "Immagine", ratio: "Proporzione", ratio_original: "Originale", ratio_fill: "Riempimento", rotation: "Rotazione", flip_h: "Orizzontale", flip_v: "Verticale", pan: "Pan", zoom: "Zoom", presets: { default: "Predefinito", bright: "Luminoso", soft: "Morbido", retro: "Retro" } },
        audio: { title: "Audio", volume: "Volume", channel: "Canale", channel_default: "Predefinito", channel_left: "Sinistra", channel_right: "Destra", sync: "Sincronizza", track: "Traccia", track_default: "Predefinita", load_track: "Carica traccia" },
        subtitle: { title: "Sottotitoli", main_tab: "Principale", sec_tab: "Secondario", select: "Selezione", hide: "Nascondi", load: "Carica", enable_sec: "Abilita secondario", style: "Stile", font_yahei: "Microsoft YaHei", font_hei: "SimHei", font_song: "SimSun", font_kai: "KaiTi", sync: "Sincronizza", position: "Posizione", pos_up: "Sopra", pos_down: "Sotto", pos_left: "Sinistra", pos_right: "Destra", continue_effect: "Applica sempre", color_title: "Colore", basic_color: "Colori base", custom_color: "Personalizzato", cancel: "Annulla", confirm: "Conferma" },
        control: { title: "Controllo", left_eye: "Occhio sinistro", surround: "Surround", threed: "Modalità 3D", settings: "Impostazioni" },
        lefteye: { title: "Occhio sinistro", view_angle: "Angolo", brightness: "Luminosità", contrast: "Contrasto" },
        surround: { title: "Surround", mode: "Modalità", mode_off: "Spento", mode_stereo: "Stereo", intensity: "Intensità", bass: "Bassi" },
        threed: { title: "3D", mode: "Modalità", mode_off: "Spento", mode_anaglyph: "Anaglifo", mode_sbs: "Affiancato", mode_tb: "Sopra/sotto", depth: "Profondità", eye_dist: "Distanza occhi" },
        settings: { title: "Impostazioni avanzate", tabs: { general: "Generale", playback: "Riproduzione" }, sidebar: { list: "Area lista", hotkey: "Scorciatoie", screenshot: "Screenshot", file_assoc: "Associazione file", playback_basic: "Riproduzione base" }, playback: { title: "Riproduzione base", step_group: "Avanti/Indietro", forward_once: "Avanti una volta", rewind_once: "Indietro una volta", speed_group: "Velocità", speed_once: "Velocità", playlist_group: "Playlist", continue_last: "Continua ultima lista", auto_add: "Aggiungi simili", clear_on_open: "Svuota all'apertura", prompt_cleanup: "Suggerisci pulizia" }, hotkey: { title: "Scorciatoie", header_command: "Comando", header_mouse: "Mouse", header_key: "Tasto", header_action: "Azione", disable_swf: "Disattiva per SWF", btn_modify: "Modifica", actions: { playPause: "Riproduci/Pausa", stop: "Stop", fastForward: "Avanti", rewind: "Indietro", speedUp: "Accelera", speedDown: "Rallenta", volumeUp: "Volume +", volumeDown: "Volume -", mute: "Muto", fullscreen: "Schermo intero", exitFullscreen: "Esci da schermo intero" }, mouse_left: "Clic sinistro" }, screenshot: { title: "Screenshot", path_label: "Cartella", btn_change: "Cambia cartella", format_label: "Formato", tool_label: "Strumento", popup_label: "Mostra dopo screenshot" }, file_assoc: { title: "Associazione file", status_checking: "Verifica...", status_is_default: "Lettore predefinito", status_not_default: "Non predefinito", status_check_failed: "Verifica fallita", btn_set_default: "Imposta predefinito", btn_already_set: "Già impostato", btn_select_all: "Seleziona tutto", btn_select_none: "Nessuno", btn_restore: "Ripristina", always_assoc: "Associa sempre", formats: { wmv: "Windows Media Video", real: "Real Media", vcd: "VCD/DVD", quicktime: "QuickTime", other_video: "Altro video", other_audio: "Altro audio", animation: "Animazione", playlist: "Playlist", subtitle: "Sottotitoli" } }, list: { title: "Area lista", display_group: "Visualizzazione", always_expand: "Espandi sempre", always_close: "Comprimi sempre", remember: "Ricorda stato", a11y: "Accessibilità", text_auto: "Dimensione testo auto", text_manual: "Manuale" } },
        context_menu: { play: "Riproduci", pause: "Pausa", stop: "Stop", prev: "Precedente", next: "Successivo", fullscreen: "Schermo intero", exit_fullscreen: "Esci da schermo intero", screenshot: "Screenshot", pip: "Picture-in-Picture", exit_pip: "Esci da PiP", pip_unsupported: "PiP non supportato", pip_no_video: "Aggiungi e riproduci un video prima", picture: "Immagine", audio: "Audio", open: "Apri file...", properties: "Proprietà", settings: "Impostazioni" },
        ab_loop: { set_a: "Punto A", set_b: "Punto B", clear: "Cancella A-B", toggle_on: "Loop A-B", toggle_off: "Esci loop A-B", no_video: "Riproduci prima un video", b_after_a: "B deve essere dopo A", set_ab_first: "Imposta prima A e B" },
        recent: { title: "Recenti", empty: "Nessuna riproduzione recente", empty_tip: "I video riprodotti appariranno qui", clear_all: "Cancella tutto", remove_selected: "Rimuovi selezione" },
        favorites: { title: "Preferiti", add_to_favorites: "Aggiungi ai preferiti", my_favorites: "I miei preferiti", empty: "Nessun preferito", empty_tip: "Tasto destro e «Aggiungi ai preferiti» durante la riproduzione", no_video: "Seleziona o riproduci un video prima", cannot_save: "Impossibile aggiungere ai preferiti", added: "Aggiunto ai preferiti", remove: "Rimuovi dai preferiti", invalid_entry: "Voce non valida" },
        properties: { title: "Proprietà", filename_empty: "Nessun video", label_type: "Tipo:", label_duration: "Durata:", label_size: "Dimensione:", label_location: "Posizione:", section_video: "Video", label_resolution: "Risoluzione:", label_codec: "Codec:", label_framerate: "FPS:", label_bitrate: "Bitrate:", btn_more: "Altro", type_video: "Video" },
        screenshot_preview: { title: "Anteprima screenshot", label_no_popup: "Non mostrare più", btn_save: "Salva" },
        dlna: { title: "Dispositivi DLNA", subtitle: "Seleziona dispositivo di uscita", searching: "Ricerca dispositivi...", no_device: "Nessun dispositivo trovato", no_device_hint: "Aggiorna o controlla rete", select_device_first: "Seleziona prima un dispositivo", device_ready: "Pronto", help_guide_title: "Guida DLNA", help_guide_content: "【Requisiti】\n• PC e TV sulla stessa rete Wi-Fi/LAN.\n• Attiva DLNA/Cast sulla TV.\n\n【Passi】\n1. Clicca [DLNA] in basso.\n2. \"Aggiorna\" per cercare.\n3. Scegli TV e \"Connetti\".\n\n【Aiuto】\n• Nessun dispositivo: firewall o riavvia Cast.\n• Ritardo: abbassa bitrate.\n• Non riproduce: usa MP4/MKV.", connecting_msg: "Connessione a: {{name}}\n\nRichiesto server DLNA. Modalità demo.", connecting_title: "Connessione DLNA" },
        update: {
            no_update_title: "Verifica aggiornamenti",
            no_update_message: "La versione corrente V{{version}} è già aggiornata",
            no_update_detail: "Nessuna versione più recente trovata. Buon utilizzo dell'app.",
            check_failed_title: "Verifica aggiornamenti non riuscita",
            check_failed_message: "Impossibile connettersi al server di aggiornamento: {{error}}",
            check_not_available: "La funzione di aggiornamento non è disponibile in questo ambiente",
            checking: "Verifica della presenza di aggiornamenti...",
            check_failed_toast: "Verifica aggiornamenti non riuscita, riprova più tardi"
        },
        dialog: { close_confirm: "Chiudere KunQiong Player?", close_title: "Conferma chiusura", notice: "Avviso", logout_confirm: "Uscire?", ok: "OK", cancel: "Annulla", help_doc_content: "KunQiong Player\n\nScorciatoie:\nSpazio - Riproduci/Pausa\n← / → - Indietro/Avanti\n↑ / ↓ - Volume\nF - Schermo intero\nM - Muto", shortcuts_content: "Spazio - Riproduci/Pausa\n← - Indietro\n→ - Avanti\n↑/↓ - Volume\nF - Schermo intero\nM - Muto\nEsc - Esci da schermo intero\nCtrl+S - Stop", about_content: "KunQiong Player\n\nLettore video con AI.\n\n【Funzioni】\n• Formati multipli\n• Decodifica hardware\n• Regolazione immagine/audio\n• Sottotitoli doppi\n• DLNA\n• Modalità cinema", resume_from: "Ripreso da {{time}}", resume_prompt: "Ultima volta non finito: «{{name}}». Riprendere?", resume_title: "Riprendi", resume_yes: "Riprendi", resume_auto_close: "Chiudi tra {{seconds}}s", licenses_content: "【Third-Party Components and Licenses】\n\nThis software uses: Electron (MIT), FFmpeg/FFprobe (LGPL/GPL), i18next (MIT), Font Awesome (CC BY 4.0). Full texts on their official sites.", privacy_content: "【Privacy】\n\n• Local playback: no upload of files or history.\n• Login: only data needed for auth/sync.\n• Updates: version check only.\n• Feedback: for support and improvement only. We do not collect viewing history." }
    }
};
