/**
 * Bahasa Melayu
 */
export default {
    translation: {
        app: { title: "KunQiong Player", subtitle: "Powered by KunQiong AI", custom_software: "Perisian tersuai", login: "Log masuk", not_logged_in: "Tetamu", logged_in: "Telah log masuk", login_tip: "Log masuk untuk lebih banyak fungsi", login_action: "Log masuk", redirecting: "Mengalihkan...", login_in_browser: "Selesaikan log masuk dalam pelayar.", relogin: "Log masuk semula", login_success_sync: "Log masuk berjaya. Menyelaraskan...", vip_user: "Ahli", logout: "Log keluar", token_label: "Token:", welcome_tip: "Seret video ke sini", loading: "Memuatkan...", screenshot_path: "Folder tangkapan:", global_brightness: "Kecerahan", reset: "Set semula", reset_all: "Set semula semua", ok: "OK", cancel: "Batal", apply: "Guna", unit: { ms: "ms", s: "s", times: "x", items: "" } },
        menu: { file: "Fail", open_file: "Buka fail...", open_folder: "Buka folder...", open_url: "Buka URL...", exit: "Keluar", play: "Main", play_pause: "Main/Jeda", stop: "Berhenti", next: "Seterusnya", prev: "Sebelumnya", fast_forward: "Maju", rewind: "Undur", effects: "Kesan", splitter: "Splitter", video_decoder: "Penyahkod video", audio_decoder: "Penyahkod audio", renderer: "Renderer", auto_select: "Auto", control: "Kawalan", subtitle: "Sari kata", picture_quality: "Imej", audio_adjust: "Audio", settings: "Tetapan", help: "Bantuan", help_doc: "Dokumentasi", shortcuts: "Pintasan", licenses: "Lesen pihak ketiga", privacy: "Privasi", check_update: "Semak kemas kini...", feedback: "Maklum balas", about: "Perihal", language: "Bahasa", lang_zh: "简体中文", lang_en: "English" },
        playlist: { title: "Senarai main", add: "Tambah", clear: "Kosongkan", loop: "Ulang senarai", loop_list: "Ulang senarai", loop_list_title: "Ulang senarai", loop_single: "Ulang satu", loop_single_title: "Ulang satu", random: "Rawak", random_title: "Rawak", empty: "Senarai kosong", empty_tip: "Klik \"Tambah\" atau seret fail", ad_placeholder: "Iklan" },
        picture: { title: "Imej", ratio: "Nisbah", ratio_original: "Asal", ratio_fill: "Isi", rotation: "Putaran", flip_h: "Mendatar", flip_v: "Menegak", pan: "Pan", zoom: "Zum", presets: { default: "Lalai", bright: "Terang", soft: "Lembut", retro: "Retro" } },
        audio: { title: "Audio", volume: "Kuantiti", channel: "Saluran", channel_default: "Lalai", channel_left: "Kiri", channel_right: "Kanan", sync: "Segerak", track: "Trek", track_default: "Lalai", load_track: "Muat trek" },
        subtitle: { title: "Sari kata", main_tab: "Utama", sec_tab: "Sekunder", select: "Pilih", hide: "Sembunyikan", load: "Muat", enable_sec: "Dayakan sekunder", style: "Gaya", font_yahei: "Microsoft YaHei", font_hei: "SimHei", font_song: "SimSun", font_kai: "KaiTi", sync: "Segerak", position: "Kedudukan", pos_up: "Atas", pos_down: "Bawah", pos_left: "Kiri", pos_right: "Kanan", continue_effect: "Sentiasa guna", color_title: "Warna", basic_color: "Warna asas", custom_color: "Tersuai", cancel: "Batal", confirm: "Sahkan" },
        control: { title: "Kawalan", left_eye: "Mata kiri", surround: "Surround", threed: "Mod 3D", settings: "Tetapan" },
        lefteye: { title: "Mata kiri", view_angle: "Sudut pandangan", brightness: "Kecerahan", contrast: "Kontras" },
        surround: { title: "Surround", mode: "Mod", mode_off: "Mati", mode_stereo: "Stereo", intensity: "Keamatan", bass: "Bass" },
        threed: { title: "3D", mode: "Mod", mode_off: "Mati", mode_anaglyph: "Anaglyph", mode_sbs: "Sisi ke sisi", mode_tb: "Atas/bawah", depth: "Kedalaman", eye_dist: "Jarak mata" },
        settings: { title: "Tetapan lanjutan", tabs: { general: "Umum", playback: "Main balik" }, sidebar: { list: "Kawasan senarai", hotkey: "Pintasan", screenshot: "Tangkapan skrin", file_assoc: "Perkaitan fail", playback_basic: "Main balik asas" }, playback: { title: "Main balik asas", step_group: "Maju/Undur", forward_once: "Maju sekali", rewind_once: "Undur sekali", speed_group: "Kelajuan", speed_once: "Kelajuan", playlist_group: "Senarai", continue_last: "Sambung senarai terakhir", auto_add: "Tambah serupa", clear_on_open: "Kosongkan bila buka", prompt_cleanup: "Cadang pembersihan" }, hotkey: { title: "Pintasan", header_command: "Arahan", header_mouse: "Tetikus", header_key: "Kekunci", header_action: "Tindakan", disable_swf: "Lumpuhkan untuk SWF", btn_modify: "Ubah", actions: { playPause: "Main/Jeda", stop: "Berhenti", fastForward: "Maju", rewind: "Undur", speedUp: "Laju", speedDown: "Perlahan", volumeUp: "Kuantiti +", volumeDown: "Kuantiti -", mute: "Bisukan", fullscreen: "Skrin penuh", exitFullscreen: "Keluar skrin penuh" }, mouse_left: "Klik kiri" }, screenshot: { title: "Tangkapan skrin", path_label: "Folder", btn_change: "Tukar folder", format_label: "Format", tool_label: "Alat", popup_label: "Tunjuk selepas tangkapan" }, file_assoc: { title: "Perkaitan fail", status_checking: "Memeriksa...", status_is_default: "Pemain lalai", status_not_default: "Bukan lalai", status_check_failed: "Pemeriksaan gagal", btn_set_default: "Set sebagai lalai", btn_already_set: "Sudah diset", btn_select_all: "Pilih semua", btn_select_none: "Tiada", btn_restore: "Pulihkan", always_assoc: "Sentiasa kaitkan", formats: { wmv: "Windows Media Video", real: "Real Media", vcd: "VCD/DVD", quicktime: "QuickTime", other_video: "Video lain", other_audio: "Audio lain", animation: "Animasi", playlist: "Senarai", subtitle: "Sari kata" } }, list: { title: "Kawasan senarai", display_group: "Paparan", always_expand: "Sentiasa kembangkan", always_close: "Sentiasa runtuhkan", remember: "Ingat keadaan", a11y: "Kebolehcapaian", text_auto: "Saiz teks auto", text_manual: "Manual" } },
        context_menu: { play: "Main", pause: "Jeda", stop: "Berhenti", prev: "Sebelumnya", next: "Seterusnya", fullscreen: "Skrin penuh", exit_fullscreen: "Keluar skrin penuh", screenshot: "Tangkapan", picture: "Imej", audio: "Audio", open: "Buka fail...", properties: "Sifat", settings: "Tetapan" },
        properties: { title: "Sifat", filename_empty: "Tiada video", label_type: "Jenis:", label_duration: "Tempoh:", label_size: "Saiz:", label_location: "Lokasi:", section_video: "Video", label_resolution: "Resolusi:", label_codec: "Codec:", label_framerate: "FPS:", label_bitrate: "Bitrate:", btn_more: "Lagi", type_video: "Video" },
        screenshot_preview: { title: "Pratonton tangkapan", label_no_popup: "Jangan tunjuk lagi", btn_save: "Simpan" },
        dlna: { title: "Peranti DLNA", subtitle: "Pilih peranti output", searching: "Mencari peranti...", no_device: "Tiada peranti dijumpai", no_device_hint: "Muat semula atau semak rangkaian", select_device_first: "Pilih peranti dahulu", device_ready: "Sedia", help_guide_title: "Panduan DLNA", help_guide_content: "【Keperluan】\n• PC dan TV dalam Wi-Fi/LAN yang sama.\n• Dayakan DLNA/Cast pada TV.\n\n【Langkah】\n1. Klik [DLNA] di bawah.\n2. \"Muat semula\" untuk cari.\n3. Pilih TV dan \"Sambung\".\n\n【Bantuan】\n• Tiada peranti: firewall atau mulakan semula Cast.\n• Lag: turunkan bitrate.\n• Tidak main: guna MP4/MKV.", connecting_msg: "Menyambung ke: {{name}}\n\nPelayan DLNA diperlukan. Mod demo.", connecting_title: "Sambungan DLNA" },
        update: {
            no_update_title: "Semak kemas kini",
            no_update_message: "Versi semasa V{{version}} sudah yang terkini",
            no_update_detail: "Tiada versi lebih baharu ditemui. Nikmati penggunaan aplikasi.",
            check_failed_title: "Semakan kemas kini gagal",
            check_failed_message: "Tidak dapat menyambung ke pelayan kemas kini: {{error}}",
            check_not_available: "Fungsi kemas kini tidak tersedia dalam persekitaran ini",
            checking: "Menyemak kemas kini...",
            check_failed_toast: "Semakan kemas kini gagal, sila cuba lagi kemudian"
        },
        recent: { title: "Terkini", empty: "Tiada main balik terkini", empty_tip: "Video yang dimainkan akan muncul di sini", clear_all: "Kosongkan semua", remove_selected: "Buang yang dipilih" },
        favorites: { title: "Kegemaran", add_to_favorites: "Tambah ke kegemaran", my_favorites: "Kegemaran saya", empty: "Belum ada kegemaran", empty_tip: "Klik kanan dan pilih \"Tambah ke kegemaran\" semasa main", no_video: "Sila pilih atau main video dahulu", cannot_save: "Tidak boleh tambah ke kegemaran", added: "Ditambah ke kegemaran", remove: "Buang dari kegemaran", invalid_entry: "Entri kegemaran tidak sah" },
        dialog: { close_confirm: "Tutup KunQiong Player?", close_title: "Sahkan penutupan", notice: "Notis", logout_confirm: "Log keluar?", ok: "OK", cancel: "Batal", help_doc_content: "KunQiong Player\n\nPintasan:\nSpace - Main/Jeda\n← / → - Undur/Maju\n↑ / ↓ - Kuantiti\nF - Skrin penuh\nM - Bisukan", shortcuts_content: "Space - Main/Jeda\n← - Undur\n→ - Maju\n↑/↓ - Kuantiti\nF - Skrin penuh\nM - Bisukan\nEsc - Keluar skrin penuh\nCtrl+S - Berhenti", about_content: "KunQiong Player\n\nPemain video dengan AI.\n\n【Fungsi】\n• Pelbagai format\n• Penyahkodan perkakasan\n• Laras imej/audio\n• Sari kata berganda\n• DLNA\n• Mod pawagam" }
    }
};
