/**
 * Nederlands
 */
export default {
    translation: {
        app: { title: "KunQiong Player", subtitle: "Powered by KunQiong AI", custom_software: "Maatwerksoftware", login: "Inloggen", not_logged_in: "Gast", logged_in: "Ingelogd", login_tip: "Log in voor meer functies", login_action: "Inloggen", redirecting: "Doorverwijzen...", login_in_browser: "Log in via de browser.", relogin: "Opnieuw inloggen", login_success_sync: "Ingelogd. Synchroniseren...", vip_user: "Lid", logout: "Uitloggen", token_label: "Token:", welcome_tip: "Sleep video's hierheen", loading: "Laden...", screenshot_path: "Screenshotmap:", global_brightness: "Helderheid", reset: "Resetten", reset_all: "Alles resetten", ok: "OK", cancel: "Annuleren", apply: "Toepassen", unit: { ms: "ms", s: "s", times: "x", items: "" } },
        menu: { file: "Bestand", open_file: "Bestand openen...", open_folder: "Map openen...", open_url: "URL openen...", exit: "Afsluiten", play: "Afspelen", play_pause: "Afspelen/Pauzeren", stop: "Stoppen", next: "Volgende", prev: "Vorige", fast_forward: "Vooruit", rewind: "Terugspoelen", effects: "Effecten", splitter: "Splitter", video_decoder: "Videodecoder", audio_decoder: "Audiodecoder", renderer: "Renderer", auto_select: "Auto", control: "Besturing", subtitle: "Ondertitels", picture_quality: "Beeld", audio_adjust: "Audio", settings: "Instellingen", help: "Help", help_doc: "Documentatie", shortcuts: "Sneltoetsen", licenses: "Licenties van derden", privacy: "Privacy", check_update: "Updates controleren...", feedback: "Feedback", about: "Over", language: "Taal", lang_zh: "简体中文", lang_en: "English" },
        playlist: { title: "Afspeellijst", add: "Toevoegen", clear: "Wissen", loop: "Lijst herhalen", loop_list: "Lijst herhalen", loop_list_title: "Lijst herhalen", loop_single: "Één herhalen", loop_single_title: "Één herhalen", random: "Shuffle", random_title: "Shuffle", empty: "Afspeellijst is leeg", empty_tip: "Klik op \"Toevoegen\" of sleep bestanden", ad_placeholder: "Advertentie" },
        picture: { title: "Beeld", ratio: "Verhouding", ratio_original: "Origineel", ratio_fill: "Vullen", rotation: "Draaien", flip_h: "Horizontaal", flip_v: "Verticaal", pan: "Pan", zoom: "Zoom", presets: { default: "Standaard", bright: "Helder", soft: "Zacht", retro: "Retro" } },
        audio: { title: "Audio", volume: "Volume", channel: "Kanaal", channel_default: "Standaard", channel_left: "Links", channel_right: "Rechts", sync: "Sync", track: "Track", track_default: "Standaard", load_track: "Track laden" },
        subtitle: { title: "Ondertitels", main_tab: "Hoofd", sec_tab: "Secundair", select: "Selectie", hide: "Verbergen", load: "Laden", enable_sec: "Secundair inschakelen", style: "Stijl", font_yahei: "Microsoft YaHei", font_hei: "SimHei", font_song: "SimSun", font_kai: "KaiTi", sync: "Sync", position: "Positie", pos_up: "Boven", pos_down: "Onder", pos_left: "Links", pos_right: "Rechts", continue_effect: "Altijd toepassen", color_title: "Kleur", basic_color: "Basiskleuren", custom_color: "Aangepast", cancel: "Annuleren", confirm: "Bevestigen" },
        control: { title: "Besturing", left_eye: "Linkeroog", surround: "Surround", threed: "3D-modus", settings: "Instellingen" },
        lefteye: { title: "Linkeroog", view_angle: "Kijkhoek", brightness: "Helderheid", contrast: "Contrast" },
        surround: { title: "Surround", mode: "Modus", mode_off: "Uit", mode_stereo: "Stereo", intensity: "Intensiteit", bass: "Bass" },
        threed: { title: "3D", mode: "Modus", mode_off: "Uit", mode_anaglyph: "Anaglyph", mode_sbs: "Zij aan zij", mode_tb: "Boven/onder", depth: "Diepte", eye_dist: "Oogafstand" },
        settings: { title: "Geavanceerde instellingen", tabs: { general: "Algemeen", playback: "Afspelen" }, sidebar: { list: "Lijstgebied", hotkey: "Sneltoetsen", screenshot: "Screenshots", file_assoc: "Bestandskoppeling", playback_basic: "Basis afspelen" }, playback: { title: "Basis afspelen", step_group: "Vooruit/Terug", forward_once: "Eenmaal vooruit", rewind_once: "Eenmaal terug", speed_group: "Snelheid", speed_once: "Snelheid", playlist_group: "Afspeellijst", continue_last: "Laatste lijst voortzetten", auto_add: "Vergelijkbare toevoegen", clear_on_open: "Legen bij openen", prompt_cleanup: "Opruimen bij lange lijst" }, hotkey: { title: "Sneltoetsen", header_command: "Opdracht", header_mouse: "Muis", header_key: "Toets", header_action: "Actie", disable_swf: "Uit voor SWF", btn_modify: "Wijzigen", actions: { playPause: "Afspelen/Pauzeren", stop: "Stoppen", fastForward: "Vooruit", rewind: "Terug", speedUp: "Versnellen", speedDown: "Vertragen", volumeUp: "Volume +", volumeDown: "Volume -", mute: "Dempen", fullscreen: "Volledig scherm", exitFullscreen: "Volledig scherm afsluiten" }, mouse_left: "Linksklik" }, screenshot: { title: "Screenshots", path_label: "Map", btn_change: "Map wijzigen", format_label: "Formaat", tool_label: "Tool", popup_label: "Tonen na screenshot" }, file_assoc: { title: "Bestandskoppeling", status_checking: "Controleren...", status_is_default: "Standaardspeler", status_not_default: "Niet standaard", status_check_failed: "Controle mislukt", btn_set_default: "Als standaard", btn_already_set: "Al ingesteld", btn_select_all: "Alles", btn_select_none: "Geen", btn_restore: "Herstellen", always_assoc: "Altijd koppelen", formats: { wmv: "Windows Media Video", real: "Real Media", vcd: "VCD/DVD", quicktime: "QuickTime", other_video: "Overige video", other_audio: "Overige audio", animation: "Animatie", playlist: "Afspeellijst", subtitle: "Ondertitels" } }, list: { title: "Lijstgebied", display_group: "Weergave", always_expand: "Altijd uitklappen", always_close: "Altijd inklappen", remember: "Status onthouden", a11y: "Toegankelijkheid", text_auto: "Tekstgrootte auto", text_manual: "Handmatig" } },
        context_menu: { play: "Afspelen", pause: "Pauzeren", stop: "Stoppen", prev: "Vorige", next: "Volgende", fullscreen: "Volledig scherm", exit_fullscreen: "Volledig scherm afsluiten", screenshot: "Screenshot", picture: "Beeld", audio: "Audio", open: "Bestand openen...", properties: "Eigenschappen", settings: "Instellingen" },
        properties: { title: "Eigenschappen", filename_empty: "Geen video geladen", label_type: "Type:", label_duration: "Duur:", label_size: "Grootte:", label_location: "Locatie:", section_video: "Video", label_resolution: "Resolutie:", label_codec: "Codec:", label_framerate: "FPS:", label_bitrate: "Bitrate:", btn_more: "Meer", type_video: "Video" },
        screenshot_preview: { title: "Screenshotvoorbeeld", label_no_popup: "Niet meer tonen", btn_save: "Opslaan" },
        dlna: { title: "DLNA-apparaten", subtitle: "Selecteer uitvoerapparaat", searching: "Apparaten zoeken...", no_device: "Geen apparaat gevonden", no_device_hint: "Vernieuwen of netwerk controleren", select_device_first: "Selecteer eerst een apparaat", device_ready: "Gereed", help_guide_title: "DLNA-handleiding", help_guide_content: "【Vereisten】\n• PC en TV op hetzelfde Wi-Fi/LAN.\n• DLNA/Cast inschakelen op TV.\n\n【Stappen】\n1. Klik op [DLNA] onderaan.\n2. \"Vernieuwen\" om te zoeken.\n3. Kies TV en \"Verbinden\".\n\n【Hulp】\n• Geen apparaat: firewall of Cast herstarten.\n• Haperen: bitrate verlagen.\n• Speelt niet: MP4/MKV gebruiken.", connecting_msg: "Verbinden met: {{name}}\n\nDLNA-server nodig. Demomodus.", connecting_title: "DLNA-verbinding" },
        update: {
            no_update_title: "Op updates controleren",
            no_update_message: "De huidige versie V{{version}} is up-to-date",
            no_update_detail: "Geen nieuwere versie gevonden. Veel plezier met de app.",
            check_failed_title: "Controleren op updates mislukt",
            check_failed_message: "Kan geen verbinding maken met de update-server: {{error}}",
            check_not_available: "De updatefunctie is in deze omgeving niet beschikbaar",
            checking: "Bezig met controleren op updates...",
            check_failed_toast: "Controleren op updates mislukt, probeer het later opnieuw"
        },
        recent: { title: "Recent", empty: "Geen recente afspeelgeschiedenis", empty_tip: "Afgespeelde video's verschijnen hier", clear_all: "Alles wissen", remove_selected: "Geselecteerde verwijderen" },
        favorites: { title: "Favorieten", add_to_favorites: "Toevoegen aan favorieten", my_favorites: "Mijn favorieten", empty: "Nog geen favorieten", empty_tip: "Rechtermuisknop en kies \"Toevoegen aan favorieten\" tijdens afspelen", no_video: "Selecteer of speel eerst een video af", cannot_save: "Kan niet aan favorieten toevoegen", added: "Toegevoegd aan favorieten", remove: "Verwijderen uit favorieten", invalid_entry: "Ongeldige favoriet" },
        dialog: { close_confirm: "KunQiong Player sluiten?", close_title: "Afsluiten bevestigen", notice: "Melding", logout_confirm: "Uitloggen?", ok: "OK", cancel: "Annuleren", help_doc_content: "KunQiong Player\n\nSneltoetsen:\nSpatie - Afspelen/Pauzeren\n← / → - Terug/Vooruit\n↑ / ↓ - Volume\nF - Volledig scherm\nM - Dempen", shortcuts_content: "Spatie - Afspelen/Pauzeren\n← - Terug\n→ - Vooruit\n↑/↓ - Volume\nF - Volledig scherm\nM - Dempen\nEsc - Volledig scherm afsluiten\nCtrl+S - Stoppen", about_content: "KunQiong Player\n\nVideospeler met AI.\n\n【Functies】\n• Meerdere formaten\n• Hardware-decodering\n• Beeld/audio-aanpassing\n• Dubbele ondertitels\n• DLNA\n• Bioscoopmodus" }
    }
};
