/**
 * Polski
 */
export default {
    translation: {
        app: { title: "KunQiong Player", subtitle: "Powered by KunQiong AI", custom_software: "Oprogramowanie na zamówienie", login: "Zaloguj", not_logged_in: "Gość", logged_in: "Zalogowano", login_tip: "Zaloguj się, aby uzyskać więcej funkcji", login_action: "Zaloguj się", redirecting: "Przekierowywanie...", login_in_browser: "Dokończ logowanie w przeglądarce.", relogin: "Zaloguj ponownie", login_success_sync: "Zalogowano. Synchronizacja...", vip_user: "Członek", logout: "Wyloguj", token_label: "Token:", welcome_tip: "Przeciągnij wideo tutaj", loading: "Ładowanie...", screenshot_path: "Folder zrzutów:", global_brightness: "Jasność", reset: "Resetuj", reset_all: "Resetuj wszystko", ok: "OK", cancel: "Anuluj", apply: "Zastosuj", unit: { ms: "ms", s: "s", times: "x", items: "" } },
        menu: { file: "Plik", open_file: "Otwórz plik...", open_folder: "Otwórz folder...", open_url: "Otwórz URL...", exit: "Zakończ", play: "Odtwarzaj", play_pause: "Odtwarzaj/Wstrzymaj", stop: "Zatrzymaj", next: "Następny", prev: "Poprzedni", fast_forward: "Do przodu", rewind: "Do tyłu", effects: "Efekty", splitter: "Splitter", video_decoder: "Dekoder wideo", audio_decoder: "Dekoder audio", renderer: "Renderer", auto_select: "Auto", control: "Sterowanie", subtitle: "Napisy", picture_quality: "Obraz", audio_adjust: "Dźwięk", settings: "Ustawienia", help: "Pomoc", help_doc: "Dokumentacja", shortcuts: "Skróty", licenses: "Licencje stron trzecich", privacy: "Prywatność", check_update: "Sprawdź aktualizacje...", feedback: "Opinie", about: "O programie", language: "Język", lang_zh: "简体中文", lang_en: "English" },
        playlist: { title: "Lista odtwarzania", add: "Dodaj", clear: "Wyczyść", loop: "Zapętlenie listy", loop_list: "Zapętlenie listy", loop_list_title: "Zapętlenie listy", loop_single: "Zapętlenie jednego", loop_single_title: "Zapętlenie jednego", random: "Losowo", random_title: "Losowo", empty: "Lista pusta", empty_tip: "Kliknij \"Dodaj\" lub przeciągnij pliki", ad_placeholder: "Reklama" },
        picture: { title: "Obraz", ratio: "Proporcje", ratio_original: "Oryginał", ratio_fill: "Wypełnij", rotation: "Obrót", flip_h: "Poziomo", flip_v: "Pionowo", pan: "Pan", zoom: "Powiększenie", presets: { default: "Domyślny", bright: "Jasny", soft: "Miękki", retro: "Retro" } },
        audio: { title: "Dźwięk", volume: "Głośność", channel: "Kanał", channel_default: "Domyślny", channel_left: "Lewy", channel_right: "Prawy", sync: "Synchronizacja", track: "Ścieżka", track_default: "Domyślna", load_track: "Załaduj ścieżkę" },
        subtitle: { title: "Napisy", main_tab: "Główne", sec_tab: "Dodatkowe", select: "Wybierz", hide: "Ukryj", load: "Załaduj", enable_sec: "Włącz dodatkowe", style: "Styl", font_yahei: "Microsoft YaHei", font_hei: "SimHei", font_song: "SimSun", font_kai: "KaiTi", sync: "Synchronizacja", position: "Pozycja", pos_up: "Góra", pos_down: "Dół", pos_left: "Lewo", pos_right: "Prawo", continue_effect: "Zawsze stosuj", color_title: "Kolor", basic_color: "Kolory podstawowe", custom_color: "Niestandardowy", cancel: "Anuluj", confirm: "Potwierdź" },
        control: { title: "Sterowanie", left_eye: "Lewe oko", surround: "Surround", threed: "Tryb 3D", settings: "Ustawienia" },
        lefteye: { title: "Lewe oko", view_angle: "Kąt widzenia", brightness: "Jasność", contrast: "Kontrast" },
        surround: { title: "Surround", mode: "Tryb", mode_off: "Wyłącz", mode_stereo: "Stereo", intensity: "Intensywność", bass: "Bas" },
        threed: { title: "3D", mode: "Tryb", mode_off: "Wyłącz", mode_anaglyph: "Anaglyf", mode_sbs: "Obok siebie", mode_tb: "Góra/dół", depth: "Głębokość", eye_dist: "Odstęp oczu" },
        settings: { title: "Ustawienia zaawansowane", tabs: { general: "Ogólne", playback: "Odtwarzanie" }, sidebar: { list: "Obszar listy", hotkey: "Skróty", screenshot: "Zrzuty ekranu", file_assoc: "Skojarzenia plików", playback_basic: "Podstawowe odtwarzanie" }, playback: { title: "Podstawowe odtwarzanie", step_group: "Do przodu/tyłu", forward_once: "Do przodu raz", rewind_once: "Do tyłu raz", speed_group: "Prędkość", speed_once: "Prędkość", playlist_group: "Lista", continue_last: "Kontynuuj ostatnią listę", auto_add: "Dodawaj podobne", clear_on_open: "Czyść przy otwarciu", prompt_cleanup: "Zaproponuj czyszczenie" }, hotkey: { title: "Skróty", header_command: "Polecenie", header_mouse: "Mysz", header_key: "Klawisz", header_action: "Akcja", disable_swf: "Wyłącz dla SWF", btn_modify: "Zmień", actions: { playPause: "Odtwarzaj/Wstrzymaj", stop: "Zatrzymaj", fastForward: "Do przodu", rewind: "Do tyłu", speedUp: "Przyspiesz", speedDown: "Zwolnij", volumeUp: "Głośniej", volumeDown: "Ciszej", mute: "Wycisz", fullscreen: "Pełny ekran", exitFullscreen: "Wyjdź z pełnego ekranu" }, mouse_left: "Klik lewy" }, screenshot: { title: "Zrzuty ekranu", path_label: "Folder", btn_change: "Zmień folder", format_label: "Format", tool_label: "Narzędzie", popup_label: "Pokaż po zrzucie" }, file_assoc: { title: "Skojarzenia plików", status_checking: "Sprawdzanie...", status_is_default: "Domyślny odtwarzacz", status_not_default: "Nie domyślny", status_check_failed: "Sprawdzenie nie powiodło się", btn_set_default: "Ustaw jako domyślny", btn_already_set: "Ustawiono", btn_select_all: "Zaznacz wszystko", btn_select_none: "Odznacz", btn_restore: "Przywróć", always_assoc: "Zawsze kojarz", formats: { wmv: "Windows Media Video", real: "Real Media", vcd: "VCD/DVD", quicktime: "QuickTime", other_video: "Inne wideo", other_audio: "Inne audio", animation: "Animacja", playlist: "Lista", subtitle: "Napisy" } }, list: { title: "Obszar listy", display_group: "Wyświetlanie", always_expand: "Zawsze rozwijaj", always_close: "Zawsze zwijaj", remember: "Zapamiętaj stan", a11y: "Ułatwienia dostępu", text_auto: "Rozmiar tekstu auto", text_manual: "Ręczny" } },
        context_menu: { play: "Odtwarzaj", pause: "Wstrzymaj", stop: "Zatrzymaj", prev: "Poprzedni", next: "Następny", fullscreen: "Pełny ekran", exit_fullscreen: "Wyjdź z pełnego ekranu", screenshot: "Zrzut ekranu", picture: "Obraz", audio: "Dźwięk", open: "Otwórz plik...", properties: "Właściwości", settings: "Ustawienia" },
        properties: { title: "Właściwości", filename_empty: "Brak wideo", label_type: "Typ:", label_duration: "Czas:", label_size: "Rozmiar:", label_location: "Lokalizacja:", section_video: "Wideo", label_resolution: "Rozdzielczość:", label_codec: "Kodek:", label_framerate: "FPS:", label_bitrate: "Bitrate:", btn_more: "Więcej", type_video: "Wideo" },
        screenshot_preview: { title: "Podgląd zrzutu", label_no_popup: "Nie pokazuj ponownie", btn_save: "Zapisz" },
        dlna: { title: "Urządzenia DLNA", subtitle: "Wybierz urządzenie wyjściowe", searching: "Szukam urządzeń...", no_device: "Nie znaleziono urządzenia", no_device_hint: "Odśwież lub sprawdź sieć", select_device_first: "Najpierw wybierz urządzenie", device_ready: "Gotowe", help_guide_title: "Przewodnik DLNA", help_guide_content: "【Wymagania】\n• PC i TV w tej samej sieci Wi-Fi/LAN.\n• Włącz DLNA/Cast na TV.\n\n【Kroki】\n1. Kliknij [DLNA] na dole.\n2. Odśwież, aby wyszukać.\n3. Wybierz TV i Połącz.\n\n【Pomoc】\n• Brak urządzeń: zapora lub restart Cast.\n• Zacinanie: obniż bitrate.\n• Nie odtwarza: użyj MP4/MKV.", connecting_msg: "Łączenie z: {{name}}\n\nWymagany serwer DLNA. Tryb demo.", connecting_title: "Połączenie DLNA" },
        update: {
            no_update_title: "Sprawdź aktualizacje",
            no_update_message: "Bieżąca wersja V{{version}} jest aktualna",
            no_update_detail: "Nie znaleziono nowszej wersji. Miłego korzystania z aplikacji.",
            check_failed_title: "Sprawdzenie aktualizacji nie powiodło się",
            check_failed_message: "Nie można połączyć się z serwerem aktualizacji: {{error}}",
            check_not_available: "Funkcja aktualizacji jest niedostępna w tym środowisku",
            checking: "Sprawdzanie aktualizacji...",
            check_failed_toast: "Sprawdzenie aktualizacji nie powiodło się, spróbuj ponownie później"
        },
        recent: { title: "Ostatnie", empty: "Brak ostatniego odtwarzania", empty_tip: "Odtworzone filmy pojawią się tutaj", clear_all: "Wyczyść wszystko", remove_selected: "Usuń zaznaczone" },
        favorites: { title: "Ulubione", add_to_favorites: "Dodaj do ulubionych", my_favorites: "Moje ulubione", empty: "Brak ulubionych", empty_tip: "Kliknij prawym przyciskiem i wybierz „Dodaj do ulubionych” podczas odtwarzania", no_video: "Najpierw wybierz lub odtwórz wideo", cannot_save: "Nie można dodać do ulubionych", added: "Dodano do ulubionych", remove: "Usuń z ulubionych", invalid_entry: "Nieprawidłowy wpis" },
        dialog: { close_confirm: "Zamknąć KunQiong Player?", close_title: "Potwierdź zakończenie", notice: "Powiadomienie", logout_confirm: "Wylogować?", ok: "OK", cancel: "Anuluj", help_doc_content: "KunQiong Player\n\nSkróty:\nSpacja - Odtwarzaj/Wstrzymaj\n← / → - Wstecz/Do przodu\n↑ / ↓ - Głośność\nF - Pełny ekran\nM - Wycisz", shortcuts_content: "Spacja - Odtwarzaj/Wstrzymaj\n← - Wstecz\n→ - Do przodu\n↑/↓ - Głośność\nF - Pełny ekran\nM - Wycisz\nEsc - Wyjdź z pełnego ekranu\nCtrl+S - Zatrzymaj", about_content: "KunQiong Player\n\nOdtwarzacz wideo z AI.\n\n【Funkcje】\n• Wiele formatów\n• Dekodowanie sprzętowe\n• Regulacja obrazu/dźwięku\n• Podwójne napisy\n• DLNA\n• Tryb kina" }
    }
};
