/**
 * Português
 */
export default {
    translation: {
        app: { title: "KunQiong Player", subtitle: "Powered by KunQiong AI", custom_software: "Software personalizado", login: "Entrar", not_logged_in: "Convidado", logged_in: "Conectado", login_tip: "Entre para mais funções", login_action: "Entrar", redirecting: "Redirecionando...", login_in_browser: "Conclua o login no navegador.", relogin: "Entrar novamente", login_success_sync: "Login realizado. Sincronizando...", vip_user: "Membro", logout: "Sair", token_label: "Token:", welcome_tip: "Arraste vídeos para aqui", loading: "A carregar...", screenshot_path: "Pasta de capturas:", global_brightness: "Brilho", reset: "Repor", reset_all: "Repor tudo", ok: "OK", cancel: "Cancelar", apply: "Aplicar", unit: { ms: "ms", s: "s", times: "x", items: "" } },
        menu: { file: "Ficheiro", open_file: "Abrir ficheiro...", open_folder: "Abrir pasta...", open_url: "Abrir URL...", exit: "Sair", play: "Reproduzir", play_pause: "Reproduzir/Pausar", stop: "Parar", next: "Seguinte", prev: "Anterior", fast_forward: "Avançar", rewind: "Retroceder", effects: "Efeitos", splitter: "Splitter", video_decoder: "Descodificador de vídeo", audio_decoder: "Descodificador de áudio", renderer: "Renderizador", auto_select: "Auto", control: "Controlo", subtitle: "Legendas", picture_quality: "Imagem", audio_adjust: "Áudio", settings: "Definições", help: "Ajuda", help_doc: "Documentação", shortcuts: "Atalhos", licenses: "Licenças de terceiros", privacy: "Privacidade", check_update: "Verificar atualizações...", feedback: "Comentários", about: "Acerca", language: "Idioma", lang_zh: "简体中文", lang_en: "English" },
        playlist: { title: "Lista de reprodução", add: "Adicionar", clear: "Limpar", loop: "Repetir lista", loop_list: "Repetir lista", loop_list_title: "Repetir lista", loop_single: "Repetir uma", loop_single_title: "Repetir uma", random: "Aleatório", random_title: "Aleatório", empty: "Lista vazia", empty_tip: "Clique em \"Adicionar\" ou arraste ficheiros", ad_placeholder: "Anúncio" },
        picture: { title: "Ajuste de imagem", ratio: "Proporção", ratio_original: "Original", ratio_fill: "Preencher", rotation: "Rotaçao", flip_h: "Horizontal", flip_v: "Vertical", pan: "Pan", zoom: "Zoom", presets: { default: "Predefinido", bright: "Brilhante", soft: "Suave", retro: "Retro" } },
        audio: { title: "Áudio", volume: "Volume", channel: "Canal", channel_default: "Predefinido", channel_left: "Esquerdo", channel_right: "Direito", sync: "Sincronizar", track: "Faixa", track_default: "Predefinido", load_track: "Carregar faixa" },
        subtitle: { title: "Legendas", main_tab: "Principal", sec_tab: "Secundário", select: "Seleção", hide: "Ocultar", load: "Carregar", enable_sec: "Ativar secundário", style: "Estilo", font_yahei: "Microsoft YaHei", font_hei: "SimHei", font_song: "SimSun", font_kai: "KaiTi", sync: "Sincronizar", position: "Posição", pos_up: "Cima", pos_down: "Baixo", pos_left: "Esquerda", pos_right: "Direita", continue_effect: "Aplicar sempre", color_title: "Cor", basic_color: "Cores básicas", custom_color: "Personalizado", cancel: "Cancelar", confirm: "Confirmar" },
        control: { title: "Controlo", left_eye: "Olho esquerdo", surround: "Surround", threed: "Modo 3D", settings: "Definições" },
        lefteye: { title: "Olho esquerdo", view_angle: "Ângulo", brightness: "Brilho", contrast: "Contraste" },
        surround: { title: "Surround", mode: "Modo", mode_off: "Desligado", mode_stereo: "Estéreo", intensity: "Intensidade", bass: "Graves" },
        threed: { title: "3D", mode: "Modo", mode_off: "Desligado", mode_anaglyph: "Anáglifo", mode_sbs: "Lado a lado", mode_tb: "Cima/baixo", depth: "Profundidade", eye_dist: "Distância ocular" },
        settings: { title: "Definições avançadas", tabs: { general: "Geral", playback: "Reprodução" }, sidebar: { list: "Área da lista", hotkey: "Atalhos", screenshot: "Capturas", file_assoc: "Associar ficheiros", playback_basic: "Reprodução básica" }, playback: { title: "Reprodução básica", step_group: "Avançar/Retroceder", forward_once: "Avançar uma vez", rewind_once: "Retroceder uma vez", speed_group: "Velocidade", speed_once: "Velocidade", playlist_group: "Lista", continue_last: "Continuar última lista", auto_add: "Adicionar semelhantes", clear_on_open: "Limpar ao abrir", prompt_cleanup: "Sugerir limpeza se lista longa" }, hotkey: { title: "Atalhos", header_command: "Comando", header_mouse: "Rato", header_key: "Tecla", header_action: "Ação", disable_swf: "Desativar para SWF", btn_modify: "Modificar", actions: { playPause: "Reproduzir/Pausar", stop: "Parar", fastForward: "Avançar", rewind: "Retroceder", speedUp: "Acelerar", speedDown: "Desacelerar", volumeUp: "Volume +", volumeDown: "Volume -", mute: "Silêncio", fullscreen: "Ecrã inteiro", exitFullscreen: "Sair do ecrã inteiro" }, mouse_left: "Clique esquerdo" }, screenshot: { title: "Capturas", path_label: "Pasta", btn_change: "Mudar pasta", format_label: "Formato", tool_label: "Ferramenta", popup_label: "Mostrar após captura" }, file_assoc: { title: "Associar ficheiros", status_checking: "A verificar...", status_is_default: "Leitor predefinido", status_not_default: "Não é predefinido", status_check_failed: "Falha na verificação", btn_set_default: "Definir predefinido", btn_already_set: "Já definido", btn_select_all: "Selecionar tudo", btn_select_none: "Nenhum", btn_restore: "Restaurar", always_assoc: "Associar sempre", formats: { wmv: "Windows Media Video", real: "Real Media", vcd: "VCD/DVD", quicktime: "QuickTime", other_video: "Outro vídeo", other_audio: "Outro áudio", animation: "Animação", playlist: "Lista", subtitle: "Legendas" } }, list: { title: "Área da lista", display_group: "Visualização", always_expand: "Expandir sempre", always_close: "Fechar sempre", remember: "Lembrar estado", a11y: "Acessibilidade", text_auto: "Tamanho de texto auto", text_manual: "Tamanho manual" } },
        context_menu: { play: "Reproduzir", pause: "Pausar", stop: "Parar", prev: "Anterior", next: "Seguinte", fullscreen: "Ecrã inteiro", exit_fullscreen: "Sair do ecrã inteiro", screenshot: "Captura", pip: "Picture-in-Picture", exit_pip: "Sair de PiP", pip_unsupported: "PiP não suportado", pip_no_video: "Adicione e reproduza um vídeo primeiro", picture: "Imagem", audio: "Áudio", open: "Abrir ficheiro...", properties: "Propriedades", settings: "Definições" },
        ab_loop: { set_a: "Ponto A", set_b: "Ponto B", clear: "Limpar A-B", toggle_on: "Ciclo A-B", toggle_off: "Sair do ciclo A-B", no_video: "Reproduza um vídeo primeiro", b_after_a: "B deve ser após A", set_ab_first: "Defina A e B primeiro" },
        recent: { title: "Recentes", empty: "Sem reproduções recentes", empty_tip: "Os vídeos reproduzidos aparecerão aqui", clear_all: "Limpar tudo", remove_selected: "Remover seleção" },
        favorites: { title: "Favoritos", add_to_favorites: "Adicionar aos favoritos", my_favorites: "Os meus favoritos", empty: "Sem favoritos", empty_tip: "Clique direito e «Adicionar aos favoritos» durante a reprodução", no_video: "Selecione ou reproduza um vídeo primeiro", cannot_save: "Não é possível adicionar aos favoritos", added: "Adicionado aos favoritos", remove: "Remover dos favoritos", invalid_entry: "Entrada inválida" },
        properties: { title: "Propriedades", filename_empty: "Nenhum vídeo carregado", label_type: "Tipo:", label_duration: "Duração:", label_size: "Tamanho:", label_location: "Localização:", section_video: "Vídeo", label_resolution: "Resolução:", label_codec: "Codec:", label_framerate: "FPS:", label_bitrate: "Bitrate:", btn_more: "Mais", type_video: "Vídeo" },
        screenshot_preview: { title: "Pré-visualizar captura", label_no_popup: "Não mostrar novamente", btn_save: "Guardar" },
        dlna: { title: "Dispositivos DLNA", subtitle: "Selecionar dispositivo de saída", searching: "A procurar dispositivos...", no_device: "Nenhum dispositivo encontrado", no_device_hint: "Atualizar ou verificar rede", select_device_first: "Selecione um dispositivo", device_ready: "Pronto", help_guide_title: "Guia DLNA", help_guide_content: "【Requisitos】\n• PC e TV na mesma Wi-Fi/LAN.\n• Ativar DLNA/Cast na TV.\n\n【Passos】\n1. Clicar em [DLNA] em baixo.\n2. \"Atualizar\" para procurar.\n3. Escolher TV e \"Ligar\".\n\n【Ajuda】\n• Sem dispositivo: firewall ou reiniciar Cast.\n• Atrasos: reduzir bitrate.\n• Não reproduz: usar MP4/MKV.", connecting_msg: "A ligar a: {{name}}\n\nRequer servidor DLNA. Modo demonstração.", connecting_title: "Ligação DLNA" },
        update: {
            no_update_title: "Procurar atualizações",
            no_update_message: "A versão atual V{{version}} já é a mais recente",
            no_update_detail: "Nenhuma versão mais recente encontrada. Aproveite a aplicação.",
            check_failed_title: "Falha ao procurar atualizações",
            check_failed_message: "Não foi possível ligar ao servidor de atualizações: {{error}}",
            check_not_available: "A função de atualização não está disponível neste ambiente",
            checking: "A procurar atualizações...",
            check_failed_toast: "Falha ao procurar atualizações. Tente novamente mais tarde"
        },
        dialog: { close_confirm: "Fechar KunQiong Player?", close_title: "Confirmar saída", notice: "Aviso", logout_confirm: "Terminar sessão?", ok: "OK", cancel: "Cancelar", help_doc_content: "KunQiong Player\n\nAtalhos:\nEspaço - Reproduzir/Pausar\n← / → - Retroceder/Avançar\n↑ / ↓ - Volume\nF - Ecrã inteiro\nM - Silêncio", shortcuts_content: "Espaço - Reproduzir/Pausar\n← - Retroceder\n→ - Avançar\n↑/↓ - Volume\nF - Ecrã inteiro\nM - Silêncio\nEsc - Sair do ecrã inteiro\nCtrl+S - Parar", about_content: "KunQiong Player\n\nLeitor de vídeo com IA.\n\n【Funções】\n• Vários formatos\n• Descodificação por hardware\n• Ajuste de imagem/áudio\n• Legendas duplas\n• DLNA\n• Modo cinema", resume_from: "Retomado de {{time}}", resume_prompt: "Da última vez não terminou: «{{name}}». Retomar?", resume_title: "Retomar", resume_yes: "Retomar", resume_auto_close: "Fechar em {{seconds}}s", licenses_content: "【Componentes e licenças de terceiros】\n\nEste software usa: Electron (MIT), FFmpeg/FFprobe (LGPL/GPL), i18next (MIT), Font Awesome (CC BY 4.0). Textos completos nos sites oficiais.", privacy_content: "【Privacidade】\n\n• Reprodução local: sem envio de ficheiros ou histórico.\n• Login: apenas dados necessários para auth/sincronização.\n• Atualizações: apenas verificação de versão.\n• Comentários: apenas para suporte e melhoria. Não recolhemos histórico de visualização." }
    }
};
