/**
 * Русский
 */
export default {
    translation: {
        app: { title: "KunQiong Player", subtitle: "Powered by KunQiong AI", custom_software: "Индивидуальное ПО", login: "Вход", not_logged_in: "Гость", logged_in: "Вход выполнен", login_tip: "Войдите для доступа к функциям", login_action: "Войти", redirecting: "Перенаправление...", login_in_browser: "Завершите вход в браузере.", relogin: "Войти снова", login_success_sync: "Вход выполнен. Синхронизация...", vip_user: "Участник", logout: "Выход", token_label: "Токен:", welcome_tip: "Перетащите видео сюда", loading: "Загрузка...", screenshot_path: "Папка снимков:", global_brightness: "Яркость", reset: "Сброс", reset_all: "Сбросить всё", ok: "OK", cancel: "Отмена", apply: "Применить", unit: { ms: "мс", s: "с", times: "x", items: "" } },
        menu: { file: "Файл", open_file: "Открыть файл...", open_folder: "Открыть папку...", open_url: "Открыть URL...", exit: "Выход", play: "Воспроизведение", play_pause: "Воспр./Пауза", stop: "Стоп", next: "Далее", prev: "Назад", fast_forward: "Вперёд", rewind: "Назад", effects: "Эффекты", splitter: "Сплиттер", video_decoder: "Видеодекодер", audio_decoder: "Аудиодекодер", renderer: "Рендер", auto_select: "Авто", control: "Управление", subtitle: "Субтитры", picture_quality: "Изображение", audio_adjust: "Аудио", settings: "Настройки", help: "Справка", help_doc: "Документация", shortcuts: "Горячие клавиши", licenses: "Лицензии сторонних компонентов", privacy: "Конфиденциальность", check_update: "Проверить обновления...", feedback: "Обратная связь", about: "О программе", language: "Язык", lang_zh: "简体中文", lang_en: "English" },
        playlist: { title: "Плейлист", add: "Добавить", clear: "Очистить", loop: "Повтор списка", loop_list: "Повтор списка", loop_list_title: "Повтор списка", loop_single: "Повтор одного", loop_single_title: "Повтор одного", random: "Случайно", random_title: "Случайно", empty: "Плейлист пуст", empty_tip: "Нажмите «Добавить» или перетащите файлы", ad_placeholder: "Реклама" },
        picture: { title: "Изображение", ratio: "Соотношение", ratio_original: "Исходное", ratio_fill: "Заполнить", rotation: "Поворот", flip_h: "По горизонтали", flip_v: "По вертикали", pan: "Панорама", zoom: "Масштаб", presets: { default: "По умолчанию", bright: "Яркий", soft: "Мягкий", retro: "Ретро" } },
        audio: { title: "Аудио", volume: "Громкость", channel: "Канал", channel_default: "По умолчанию", channel_left: "Левый", channel_right: "Правый", sync: "Синхр.", track: "Дорожка", track_default: "По умолчанию", load_track: "Загрузить" },
        subtitle: { title: "Субтитры", main_tab: "Основные", sec_tab: "Вторые", select: "Выбор", hide: "Скрыть", load: "Загрузить", enable_sec: "Включить вторые", style: "Стиль", font_yahei: "Microsoft YaHei", font_hei: "SimHei", font_song: "SimSun", font_kai: "KaiTi", sync: "Синхр.", position: "Положение", pos_up: "Вверх", pos_down: "Вниз", pos_left: "Влево", pos_right: "Вправо", continue_effect: "Всегда применять", color_title: "Цвет", basic_color: "Основные цвета", custom_color: "Свой", cancel: "Отмена", confirm: "ОК" },
        control: { title: "Управление", left_eye: "Левый глаз", surround: "Объёмный звук", threed: "3D режим", settings: "Настройки" },
        lefteye: { title: "Левый глаз", view_angle: "Угол", brightness: "Яркость", contrast: "Контраст" },
        surround: { title: "Объёмный звук", mode: "Режим", mode_off: "Выкл.", mode_stereo: "Стерео", intensity: "Интенсивность", bass: "Низкие" },
        threed: { title: "3D", mode: "Режим", mode_off: "Выкл.", mode_anaglyph: "Анаглиф", mode_sbs: "Бок о бок", mode_tb: "Верх/низ", depth: "Глубина", eye_dist: "Расстояние глаз" },
        settings: { title: "Доп. настройки", tabs: { general: "Общие", playback: "Воспроизведение" }, sidebar: { list: "Область списка", hotkey: "Горячие клавиши", screenshot: "Снимки", file_assoc: "Связи файлов", playback_basic: "Базовое воспр." }, playback: { title: "Базовое воспр.", step_group: "Вперёд/Назад", forward_once: "Вперёд раз", rewind_once: "Назад раз", speed_group: "Скорость", speed_once: "Скорость", playlist_group: "Плейлист", continue_last: "Продолжить список", auto_add: "Добавлять похожие", clear_on_open: "Очищать при открытии", prompt_cleanup: "Предложить очистку" }, hotkey: { title: "Горячие клавиши", header_command: "Команда", header_mouse: "Мышь", header_key: "Клавиша", header_action: "Действие", disable_swf: "Откл. для SWF", btn_modify: "Изменить", actions: { playPause: "Воспр./Пауза", stop: "Стоп", fastForward: "Вперёд", rewind: "Назад", speedUp: "Быстрее", speedDown: "Медленнее", volumeUp: "Громче", volumeDown: "Тише", mute: "Без звука", fullscreen: "Полный экран", exitFullscreen: "Выйти из полного экрана" }, mouse_left: "ЛКМ" }, screenshot: { title: "Снимки", path_label: "Папка", btn_change: "Изменить", format_label: "Формат", tool_label: "Инструмент", popup_label: "Показывать после снимка" }, file_assoc: { title: "Связи файлов", status_checking: "Проверка...", status_is_default: "Плеер по умолчанию", status_not_default: "Не по умолчанию", status_check_failed: "Ошибка проверки", btn_set_default: "По умолчанию", btn_already_set: "Установлено", btn_select_all: "Все", btn_select_none: "Нет", btn_restore: "Восстановить", always_assoc: "Всегда связывать", formats: { wmv: "Windows Media Video", real: "Real Media", vcd: "VCD/DVD", quicktime: "QuickTime", other_video: "Другое видео", other_audio: "Другое аудио", animation: "Анимация", playlist: "Плейлист", subtitle: "Субтитры" } }, list: { title: "Область списка", display_group: "Отображение", always_expand: "Разворачивать", always_close: "Сворачивать", remember: "Запомнить", a11y: "Доступность", text_auto: "Размер текста авто", text_manual: "Вручную" } },
        context_menu: { play: "Воспроизведение", pause: "Пауза", stop: "Стоп", prev: "Назад", next: "Далее", fullscreen: "Полный экран", exit_fullscreen: "Выйти", screenshot: "Снимок", picture: "Изображение", audio: "Аудио", open: "Открыть файл...", properties: "Свойства", settings: "Настройки" },
        properties: { title: "Свойства", filename_empty: "Нет видео", label_type: "Тип:", label_duration: "Длительность:", label_size: "Размер:", label_location: "Расположение:", section_video: "Видео", label_resolution: "Разрешение:", label_codec: "Кодек:", label_framerate: "Кадры/с:", label_bitrate: "Битрейт:", btn_more: "Подробнее", type_video: "Видео" },
        screenshot_preview: { title: "Просмотр снимка", label_no_popup: "Больше не показывать", btn_save: "Сохранить" },
        dlna: { title: "Устройства DLNA", subtitle: "Выберите устройство", searching: "Поиск устройств...", no_device: "Устройства не найдены", no_device_hint: "Обновите или проверьте сеть", select_device_first: "Сначала выберите устройство", device_ready: "Готово", help_guide_title: "Руководство DLNA", help_guide_content: "【Условия】\n• ПК и ТВ в одной сети Wi-Fi/LAN.\n• Включить DLNA/Cast на ТВ.\n\n【Шаги】\n1. Нажмите [DLNA] внизу.\n2. «Обновить» для поиска.\n3. Выберите ТВ и «Подключить».\n\n【Помощь】\n• Нет устройств: брандмауэр или перезапуск Cast.\n• Задержки: уменьшить битрейт.\n• Не воспроизводит: MP4/MKV.", connecting_msg: "Подключение к: {{name}}\n\nНужен сервер DLNA. Режим демо.", connecting_title: "Подключение DLNA" },
        update: {
            no_update_title: "Проверка обновлений",
            no_update_message: "Текущая версия V{{version}} является актуальной",
            no_update_detail: "Более новая версия не найдена. Приятного пользования приложением.",
            check_failed_title: "Не удалось проверить обновления",
            check_failed_message: "Не удалось подключиться к серверу обновлений: {{error}}",
            check_not_available: "Функция обновления недоступна в данной среде",
            checking: "Проверка обновлений...",
            check_failed_toast: "Ошибка проверки обновлений. Попробуйте позже"
        },
        recent: { title: "Недавние", empty: "Нет недавнего воспроизведения", empty_tip: "Воспроизведённые видео появятся здесь", clear_all: "Очистить всё", remove_selected: "Удалить выбранные" },
        favorites: { title: "Избранное", add_to_favorites: "Добавить в избранное", my_favorites: "Моё избранное", empty: "Пока нет избранного", empty_tip: "Щёлкните правой кнопкой и выберите «Добавить в избранное» при воспроизведении", no_video: "Сначала выберите или воспроизведите видео", cannot_save: "Не удалось добавить в избранное", added: "Добавлено в избранное", remove: "Удалить из избранного", invalid_entry: "Недопустимая запись" },
        dialog: { close_confirm: "Закрыть KunQiong Player?", close_title: "Подтверждение", notice: "Уведомление", logout_confirm: "Выйти?", ok: "OK", cancel: "Отмена", help_doc_content: "KunQiong Player\n\nГорячие клавиши:\nПробел - Воспр./Пауза\n← / → - Назад/Вперёд\n↑ / ↓ - Громкость\nF - Полный экран\nM - Без звука", shortcuts_content: "Пробел - Воспр./Пауза\n← - Назад\n→ - Вперёд\n↑/↓ - Громкость\nF - Полный экран\nM - Без звука\nEsc - Выйти из полного экрана\nCtrl+S - Стоп", about_content: "KunQiong Player\n\nВидеоплеер с ИИ.\n\n【Функции】\n• Много форматов\n• Аппаратное декодирование\n• Настройка изображения/звука\n• Двойные субтитры\n• DLNA\n• Режим кино" }
    }
};
