/**
 * Kiswahili
 */
export default {
    translation: {
        app: { title: "KunQiong Player", subtitle: "Powered by KunQiong AI", custom_software: "Programu maalum", login: "Ingia", not_logged_in: "Mgeni", logged_in: "Umeingia", login_tip: "Ingia kwa vitendo zaidi", login_action: "Ingia", redirecting: "Inaelekeza...", login_in_browser: "Kamilisha kuingia kwenye kivinjari.", relogin: "Ingia tena", login_success_sync: "Umeingia. Inalinganisha...", vip_user: "Mwanachama", logout: "Toka", token_label: "Tokeni:", welcome_tip: "Buruta video hapa", loading: "Inapakia...", screenshot_path: "Folda ya picha ya skrini:", global_brightness: "Mwangaza", reset: "Weka upya", reset_all: "Weka upya yote", ok: "Sawa", cancel: "Ghairi", apply: "Tumia", unit: { ms: "ms", s: "s", times: "x", items: "" } },
        menu: { file: "Faili", open_file: "Fungua faili...", open_folder: "Fungua folda...", open_url: "Fungua URL...", exit: "Toka", play: "Cheza", play_pause: "Cheza/Sitisha", stop: "Simama", next: "Ifuatayo", prev: "Iliyotangulia", fast_forward: "Mbele", rewind: "Nyuma", effects: "Athari", splitter: "Splitter", video_decoder: "Dikoda ya video", audio_decoder: "Dikoda ya sauti", renderer: "Renderer", auto_select: "Otomatiki", control: "Udhibiti", subtitle: "Manukuu", picture_quality: "Picha", audio_adjust: "Sauti", settings: "Mipangilio", help: "Msaada", help_doc: "Nyaraka", shortcuts: "Njia za mkato", licenses: "Leseni za wahusika wengine", privacy: "Faragha", check_update: "Angalia masasisho...", feedback: "Maoni", about: "Kuhusu", language: "Lugha", lang_zh: "简体中文", lang_en: "English" },
        playlist: { title: "Orodha ya kucheza", add: "Ongeza", clear: "Futa", loop: "Rudia orodha", loop_list: "Rudia orodha", loop_list_title: "Rudia orodha", loop_single: "Rudia moja", loop_single_title: "Rudia moja", random: "Nasibu", random_title: "Nasibu", empty: "Orodha tupu", empty_tip: "Bofya \"Ongeza\" au buruta faili", ad_placeholder: "Tangazo" },
        picture: { title: "Picha", ratio: "Uwiano", ratio_original: "Asili", ratio_fill: "Jaza", rotation: "Zungusha", flip_h: "Usawa", flip_v: "Wima", pan: "Pan", zoom: "Kuza", presets: { default: "Chaguo-msingi", bright: "Angavu", soft: "Laini", retro: "Retro" } },
        audio: { title: "Sauti", volume: "Kiasi", channel: "Kituo", channel_default: "Chaguo-msingi", channel_left: "Kushoto", channel_right: "Kulia", sync: "Linganisha", track: "Wimbo", track_default: "Chaguo-msingi", load_track: "Pakia wimbo" },
        subtitle: { title: "Manukuu", main_tab: "Kuu", sec_tab: "Pili", select: "Chagua", hide: "Ficha", load: "Pakia", enable_sec: "Washa pili", style: "Mtindo", font_yahei: "Microsoft YaHei", font_hei: "SimHei", font_song: "SimSun", font_kai: "KaiTi", sync: "Linganisha", position: "Mahali", pos_up: "Juu", pos_down: "Chini", pos_left: "Kushoto", pos_right: "Kulia", continue_effect: "Tumia kila wakati", color_title: "Rangi", basic_color: "Rangi za msingi", custom_color: "Maalum", cancel: "Ghairi", confirm: "Thibitisha" },
        control: { title: "Udhibiti", left_eye: "Jicho la kushoto", surround: "Surround", threed: "Hali ya 3D", settings: "Mipangilio" },
        lefteye: { title: "Jicho la kushoto", view_angle: "Pembe ya kuona", brightness: "Mwangaza", contrast: "Tofauti" },
        surround: { title: "Surround", mode: "Hali", mode_off: "Zima", mode_stereo: "Stereo", intensity: "Ukali", bass: "Bass" },
        threed: { title: "3D", mode: "Hali", mode_off: "Zima", mode_anaglyph: "Anaglyph", mode_sbs: "Kando kwa kando", mode_tb: "Juu/chini", depth: "Kina", eye_dist: "Umbali wa macho" },
        settings: { title: "Mipangilio ya hali ya juu", tabs: { general: "Jumla", playback: "Kucheza" }, sidebar: { list: "Eneo la orodha", hotkey: "Njia za mkato", screenshot: "Picha za skrini", file_assoc: "Uunganishaji wa faili", playback_basic: "Kucheza kimsingi" }, playback: { title: "Kucheza kimsingi", step_group: "Mbele/Nyuma", forward_once: "Mbele mara moja", rewind_once: "Nyuma mara moja", speed_group: "Kasi", speed_once: "Kasi", playlist_group: "Orodha", continue_last: "Endelea orodha ya mwisho", auto_add: "Ongeza sawa", clear_on_open: "Futa unapofungua", prompt_cleanup: " Pendekeza usafishaji" }, hotkey: { title: "Njia za mkato", header_command: "Amri", header_mouse: "Kipanya", header_key: "Kitufe", header_action: "Kitendo", disable_swf: "Zima kwa SWF", btn_modify: "Badilisha", actions: { playPause: "Cheza/Sitisha", stop: "Simama", fastForward: "Mbele", rewind: "Nyuma", speedUp: "Haraka", speedDown: "Polepole", volumeUp: "Kiasi +", volumeDown: "Kiasi -", mute: "Zima sauti", fullscreen: "Skrini kamili", exitFullscreen: "Toka skrini kamili" }, mouse_left: "Bonyeza kushoto" }, screenshot: { title: "Picha za skrini", path_label: "Folda", btn_change: "Badilisha folda", format_label: "Muundo", tool_label: "Zana", popup_label: "Onyesha baada ya kukamata" }, file_assoc: { title: "Uunganishaji wa faili", status_checking: "Inakagua...", status_is_default: "Kichezeshi chaguo-msingi", status_not_default: "Si chaguo-msingi", status_check_failed: "Ukaguzi umeshindwa", btn_set_default: "Weka chaguo-msingi", btn_already_set: "Tayari imewekwa", btn_select_all: "Chagua yote", btn_select_none: "Hakuna", btn_restore: "Rejesha", always_assoc: "Unganisha kila wakati", formats: { wmv: "Windows Media Video", real: "Real Media", vcd: "VCD/DVD", quicktime: "QuickTime", other_video: "Video nyingine", other_audio: "Sauti nyingine", animation: "Uhuishaji", playlist: "Orodha", subtitle: "Manukuu" } }, list: { title: "Eneo la orodha", display_group: "Onyesho", always_expand: "Panua kila wakati", always_close: "Kunjua kila wakati", remember: "Kumbuka hali", a11y: "Ufikiaji", text_auto: "Ukubwa wa maandishi otomatiki", text_manual: "Mkono" } },
        context_menu: { play: "Cheza", pause: "Sitisha", stop: "Simama", prev: "Iliyotangulia", next: "Ifuatayo", fullscreen: "Skrini kamili", exit_fullscreen: "Toka skrini kamili", screenshot: "Picha ya skrini", picture: "Picha", audio: "Sauti", open: "Fungua faili...", properties: "Mali", settings: "Mipangilio" },
        properties: { title: "Mali", filename_empty: "Hakuna video", label_type: "Aina:", label_duration: "Muda:", label_size: "Ukubwa:", label_location: "Mahali:", section_video: "Video", label_resolution: "Azimio:", label_codec: "Codec:", label_framerate: "FPS:", label_bitrate: "Bitrate:", btn_more: "Zaidi", type_video: "Video" },
        screenshot_preview: { title: "Onyesho la picha ya skrini", label_no_popup: "Usionyeshe tena", btn_save: "Hifadhi" },
        dlna: { title: "Vifaa vya DLNA", subtitle: "Chagua kifaa cha pato", searching: "Inatafuta vifaa...", no_device: "Hakuna kifaa kilichopatikana", no_device_hint: "Onyesha upya au angalia mtandao", select_device_first: "Chagua kifaa kwanza", device_ready: "Tayari", help_guide_title: "Mwongozo wa DLNA", help_guide_content: "【Mahitaji】\n• PC na TV kwenye Wi-Fi/LAN sawa.\n• Washa DLNA/Cast kwenye TV.\n\n【Hatua】\n1. Bofya [DLNA] chini.\n2. \"Onyesha upya\" kutafuta.\n3. Chagua TV na \"Unganisha\".\n\n【Msaada】\n• Hakuna kifaa: firewall au kuanza upya Cast.\n• Chelewesho: punguza bitrate.\n• Haichezi: tumia MP4/MKV.", connecting_msg: "Inaunganisha na: {{name}}\n\nSeva ya DLNA inahitajika. Hali ya demo.", connecting_title: "Muunganisho wa DLNA" },
        update: {
            no_update_title: "Angalia masasisho",
            no_update_message: "Toleo la sasa V{{version}} ndilo jipya zaidi",
            no_update_detail: "Hakuna toleo jipya lililopatikana. Furahia kutumia programu.",
            check_failed_title: "Imeshindwa kuangalia masasisho",
            check_failed_message: "Imeshindwa kuunganishwa na seva ya masasisho: {{error}}",
            check_not_available: "Kipengele cha masasisho hakipatikani katika mazingira haya",
            checking: "Inaangalia masasisho...",
            check_failed_toast: "Imeshindwa kuangalia masasisho, tafadhali jaribu tena baadaye"
        },
        recent: { title: "Hivi karibuni", empty: "Hakuna uchezaji wa hivi karibuni", empty_tip: "Video zilizochezwa zitaonekana hapa", clear_all: "Futa zote", remove_selected: "Ondoa zilizochaguliwa" },
        favorites: { title: "Unazopenda", add_to_favorites: "Ongeza kwenye unazopenda", my_favorites: "Unazopenda zangu", empty: "Bado hakuna unazopenda", empty_tip: "Bonyeza kitufe cha kulia na chagua \"Ongeza kwenye unazopenda\" wakati wa kucheza", no_video: "Tafadhali chagua au cheza video kwanza", cannot_save: "Haiwezi kuongezwa kwenye unazopenda", added: "Imeongezwa kwenye unazopenda", remove: "Ondoa kwenye unazopenda", invalid_entry: "Ingizo batili" },
        dialog: { close_confirm: "Funga KunQiong Player?", close_title: "Thibitisha kufunga", notice: "Arifa", logout_confirm: "Toka?", ok: "Sawa", cancel: "Ghairi", help_doc_content: "KunQiong Player\n\nNjia za mkato:\nNafasi - Cheza/Sitisha\n← / → - Nyuma/Mbele\n↑ / ↓ - Kiasi\nF - Skrini kamili\nM - Zima sauti", shortcuts_content: "Nafasi - Cheza/Sitisha\n← - Nyuma\n→ - Mbele\n↑/↓ - Kiasi\nF - Skrini kamili\nM - Zima sauti\nEsc - Toka skrini kamili\nCtrl+S - Simama", about_content: "KunQiong Player\n\nKichezeshi cha video chenye AI.\n\n【Vitendo】\n• Miundo mingi\n• Ufumbuaji wa vifaa\n• Marekebisho ya picha/sauti\n• Manukuu mara mbili\n• DLNA\n• Hali ya sinema" }
    }
};
