/**
 * தமிழ்
 */
export default {
    translation: {
        app: { title: "KunQiong Player", subtitle: "Powered by KunQiong AI", custom_software: "தனிப்பயன் மென்பொருள்", login: "உள்நுழை", not_logged_in: "விருந்தினர்", logged_in: "உள்நுழைந்துள்ளார்", login_tip: "மேலும் செயல்பாடுகளுக்கு உள்நுழையுங்கள்", login_action: "உள்நுழை", redirecting: "திருப்பி அனுப்புகிறது...", login_in_browser: "உலாவியில் உள்நுழைவை முடிக்கவும்.", relogin: "மீண்டும் உள்நுழை", login_success_sync: "உள்நுழைந்தது. ஒத்திசைக்கிறது...", vip_user: "உறுப்பினர்", logout: "வெளியேறு", token_label: "டோக்கன்:", welcome_tip: "வீடியோவை இங்கே இழுக்கவும்", loading: "ஏற்றுகிறது...", screenshot_path: "திரைப்பிடிப்பு அடைவு:", global_brightness: "பிரகாசம்", reset: "மீட்டமை", reset_all: "அனைத்தும் மீட்டமை", ok: "சரி", cancel: "ரத்து", apply: "பயன்படுத்து", unit: { ms: "ms", s: "s", times: "x", items: "" } },
        menu: { file: "கோப்பு", open_file: "கோப்பைத் திற...", open_folder: "அடைவைத் திற...", open_url: "URL திற...", exit: "வெளியேறு", play: "இயக்கு", play_pause: "இயக்கு/இடைநிறுத்து", stop: "நிறுத்து", next: "அடுத்தது", prev: "முந்தையது", fast_forward: "முன்னோக்கி", rewind: "பின்னோக்கி", effects: "விளைவுகள்", splitter: "பிரிப்பான்", video_decoder: "வீடியோ டிகோடர்", audio_decoder: "ஆடியோ டிகோடர்", renderer: "ரெண்டரர்", auto_select: "தானியங்கி", control: "கட்டுப்பாடு", subtitle: "வசன வரிகள்", picture_quality: "படம்", audio_adjust: "ஆடியோ", settings: "அமைப்புகள்", help: "உதவி", help_doc: "ஆவணம்", shortcuts: "குறுக்குவழிகள்", licenses: "மூன்றாம் தரப்பு உரிமங்கள்", privacy: "தனியுரிமை", check_update: "புதுப்பிப்புகள் சரிபார்...", feedback: "கருத்து", about: "பற்றி", language: "மொழி", lang_zh: "简体中文", lang_en: "English" },
        playlist: { title: "பிளேலிஸ்ட்", add: "சேர்", clear: "அழி", loop: "பட்டியலை மீண்டும்", loop_list: "பட்டியலை மீண்டும்", loop_list_title: "பட்டியலை மீண்டும்", loop_single: "ஒன்றை மீண்டும்", loop_single_title: "ஒன்றை மீண்டும்", random: "சீரற்ற", random_title: "சீரற்ற", empty: "பட்டியல் காலி", empty_tip: "\"சேர்\" கிளிக் செய்யவும் அல்லது கோப்புகளை இழுக்கவும்", ad_placeholder: "விளம்பரம்" },
        picture: { title: "படம்", ratio: "விகிதம்", ratio_original: "அசல்", ratio_fill: "நிரப்பு", rotation: "சுழற்சி", flip_h: "கிடைமட்ட", flip_v: "செங்குத்து", pan: "பான்", zoom: "ஜூம்", presets: { default: "இயல்புநிலை", bright: "பிரகாசமான", soft: "மென்மையான", retro: "ரெட்ரோ" } },
        audio: { title: "ஆடியோ", volume: "ஒலி அளவு", channel: "சேனல்", channel_default: "இயல்புநிலை", channel_left: "இடது", channel_right: "வலது", sync: "ஒத்திசை", track: "டிராக்", track_default: "இயல்புநிலை", load_track: "டிராக் ஏற்று" },
        subtitle: { title: "வசன வரிகள்", main_tab: "முதன்மை", sec_tab: "இரண்டாம்", select: "தேர்ந்தெடு", hide: "மறை", load: "ஏற்று", enable_sec: "இரண்டாம் இயக்கு", style: "பாணி", font_yahei: "Microsoft YaHei", font_hei: "SimHei", font_song: "SimSun", font_kai: "KaiTi", sync: "ஒத்திசை", position: "இடம்", pos_up: "மேல்", pos_down: "கீழ்", pos_left: "இடது", pos_right: "வலது", continue_effect: "எப்போதும் பயன்படுத்து", color_title: "நிறம்", basic_color: "அடிப்படை நிறங்கள்", custom_color: "தனிப்பயன்", cancel: "ரத்து", confirm: "உறுதி" },
        control: { title: "கட்டுப்பாடு", left_eye: "இடது கண்", surround: "சுற்றுச்சூழல்", threed: "3D மோட்", settings: "அமைப்புகள்" },
        lefteye: { title: "இடது கண்", view_angle: "காட்சி கோணம்", brightness: "பிரகாசம்", contrast: "மாறுபாடு" },
        surround: { title: "சுற்றுச்சூழல்", mode: "மோட்", mode_off: "அணை", mode_stereo: "ஸ்டீரியோ", intensity: "தீவிரம்", bass: "பாஸ்" },
        threed: { title: "3D", mode: "மோட்", mode_off: "அணை", mode_anaglyph: "அனாக்ளிஃப்", mode_sbs: "பக்கத்தில்", mode_tb: "மேல்/கீழ்", depth: "ஆழம்", eye_dist: "கண் தூரம்" },
        settings: { title: "மேம்பட்ட அமைப்புகள்", tabs: { general: "பொது", playback: "பிளேபேக்" }, sidebar: { list: "பட்டியல் பகுதி", hotkey: "குறுக்குவழிகள்", screenshot: "திரைப்பிடிப்புகள்", file_assoc: "கோப்பு இணைப்பு", playback_basic: "அடிப்படை பிளேபேக்" }, playback: { title: "அடிப்படை பிளேபேக்", step_group: "முன்னோக்கி/பின்னோக்கி", forward_once: "ஒருமுறை முன்னோக்கி", rewind_once: "ஒருமுறை பின்னோக்கி", speed_group: "வேகம்", speed_once: "வேகம்", playlist_group: "பிளேலிஸ்ட்", continue_last: "கடைசி பட்டியலைத் தொடர்", auto_add: "ஒத்தவற்றைச் சேர்", clear_on_open: "திறக்கும்போது அழி", prompt_cleanup: "நீண்ட பட்டியலில் சுத்தம் பரிந்துரை" }, hotkey: { title: "குறுக்குவழிகள்", header_command: "கட்டளை", header_mouse: "சுட்டி", header_key: "விசை", header_action: "செயல்", disable_swf: "SWFக்கு அணை", btn_modify: "மாற்று", actions: { playPause: "இயக்கு/இடைநிறுத்து", stop: "நிறுத்து", fastForward: "முன்னோக்கி", rewind: "பின்னோக்கி", speedUp: "வேகமாக", speedDown: "மெதுவாக", volumeUp: "ஒலி +", volumeDown: "ஒலி -", mute: "ஒலிமூடு", fullscreen: "முழுத்திரை", exitFullscreen: "முழுத்திரையிலிருந்து வெளியேறு" }, mouse_left: "இடது கிளிக்" }, screenshot: { title: "திரைப்பிடிப்புகள்", path_label: "அடைவு", btn_change: "அடைவு மாற்று", format_label: "வடிவம்", tool_label: "கருவி", popup_label: "பிடித்த பிறகு காட்டு" }, file_assoc: { title: "கோப்பு இணைப்பு", status_checking: "சரிபார்க்கிறது...", status_is_default: "இயல்புநிலை பிளேயர்", status_not_default: "இயல்புநிலை அல்ல", status_check_failed: "சரிபார்ப்பு தோல்வி", btn_set_default: "இயல்புநிலையாக அமை", btn_already_set: "ஏற்கனவே அமைக்கப்பட்டது", btn_select_all: "அனைத்தும் தேர்ந்தெடு", btn_select_none: "எதுவுமில்லை", btn_restore: "மீட்டமை", always_assoc: "எப்போதும் இணை", formats: { wmv: "Windows Media Video", real: "Real Media", vcd: "VCD/DVD", quicktime: "QuickTime", other_video: "மற்ற வீடியோ", other_audio: "மற்ற ஆடியோ", animation: "அனிமேஷன்", playlist: "பிளேலிஸ்ட்", subtitle: "வசன வரிகள்" } }, list: { title: "பட்டியல் பகுதி", display_group: "காட்சி", always_expand: "எப்போதும் விரிவாக்கு", always_close: "எப்போதும் சுருக்கு", remember: "நிலை நினைவில் வை", a11y: "அணுகல்தன்மை", text_auto: "உரை அளவு தானியங்கி", text_manual: "கைமுறை" } },
        context_menu: { play: "இயக்கு", pause: "இடைநிறுத்து", stop: "நிறுத்து", prev: "முந்தையது", next: "அடுத்தது", fullscreen: "முழுத்திரை", exit_fullscreen: "முழுத்திரையிலிருந்து வெளியேறு", screenshot: "திரைப்பிடிப்பு", picture: "படம்", audio: "ஆடியோ", open: "கோப்பைத் திற...", properties: "பண்புகள்", settings: "அமைப்புகள்" },
        properties: { title: "பண்புகள்", filename_empty: "வீடியோ இல்லை", label_type: "வகை:", label_duration: "காலம்:", label_size: "அளவு:", label_location: "இடம்:", section_video: "வீடியோ", label_resolution: "ரெசல்யூஷன்:", label_codec: "கோடெக்:", label_framerate: "FPS:", label_bitrate: "பிட்ரேட்:", btn_more: "மேலும்", type_video: "வீடியோ" },
        screenshot_preview: { title: "திரைப்பிடிப்பு முன்னோட்டம்", label_no_popup: "மீண்டும் காட்டாதே", btn_save: "சேமி" },
        dlna: { title: "DLNA சாதனங்கள்", subtitle: "வெளியீட்டு சாதனத்தைத் தேர்ந்தெடு", searching: "சாதனங்களைத் தேடுகிறது...", no_device: "சாதனம் கிடைக்கவில்லை", no_device_hint: "புதுப்பி அல்லது வலையைச் சரிபார்", select_device_first: "முதலில் சாதனத்தைத் தேர்ந்தெடு", device_ready: "தயார்", help_guide_title: "DLNA வழிகாட்டி", help_guide_content: "【தேவைகள்】\n• PC மற்றும் TV ஒரே Wi-Fi/LAN இல்.\n• TV இல் DLNA/Cast இயக்கு.\n\n【படிகள்】\n1. கீழே [DLNA] கிளிக் செய்யவும்.\n2. தேட \"புதுப்பி\".\n3. TV தேர்ந்தெடுத்து \"இணை\".\n\n【உதவி】\n• சாதனம் இல்லை: ஃபயர்வால் அல்லது Cast மீண்டும் துவக்கு.\n• பின்னடைவு: பிட்ரேட்டைக் குறை.\n• இயக்கவில்லை: MP4/MKV பயன்படுத்து.", connecting_msg: "இணைக்கிறது: {{name}}\n\nDLNA சர்வர் தேவை. டெமோ மோட்.", connecting_title: "DLNA இணைப்பு" },
        update: {
            no_update_title: "புதுப்பிப்பை சரிபார்",
            no_update_message: "தற்போதைய பதிப்பு V{{version}} ஏற்கனவே சமீபத்தியது",
            no_update_detail: "புதிய பதிப்பு எதுவும் கிடைக்கவில்லை. பயன்பாட்டைப் பயன்படுத்தி மகிழுங்கள்.",
            check_failed_title: "புதுப்பிப்பை சரிபார்ப்பதில் தோல்வி",
            check_failed_message: "புதுப்பிப்பு சேவையகத்துடன் இணைக்க முடியவில்லை: {{error}}",
            check_not_available: "இந்த சூழலில் புதுப்பிப்பு அம்சம் கிடைக்கவில்லை",
            checking: "புதுப்பிப்பை சரிபார்க்கிறது...",
            check_failed_toast: "புதுப்பிப்பை சரிபார்ப்பதில் தோல்வி, பின்னர் மீண்டும் முயற்சிக்கவும்"
        },
        recent: { title: "சமீபத்திய", empty: "இன்னும் சமீபத்திய இசைப்பு இல்லை", empty_tip: "இசைக்கப்பட்ட வீடியோக்கள் இங்கே தோன்றும்", clear_all: "அனைத்தையும் அழி", remove_selected: "தேர்ந்தெடுத்தவற்றை அகற்று" },
        favorites: { title: "பிடித்தவை", add_to_favorites: "பிடித்தவற்றில் சேர்", my_favorites: "என் பிடித்தவை", empty: "இன்னும் பிடித்தவை இல்லை", empty_tip: "இசைக்கும்போது வலது கிளிக் செய்து \"பிடித்தவற்றில் சேர்\" தேர்ந்தெடுக்கவும்", no_video: "முதலில் வீடியோ தேர்ந்தெடுக்கவும் அல்லது இசைக்கவும்", cannot_save: "பிடித்தவற்றில் சேர்க்க முடியவில்லை", added: "பிடித்தவற்றில் சேர்க்கப்பட்டது", remove: "பிடித்தவற்றிலிருந்து அகற்று", invalid_entry: "தவறான பிடித்த பதிவு" },
        dialog: { close_confirm: "KunQiong Player மூடவா?", close_title: "மூடுதலை உறுதிசெய்", notice: "அறிவிப்பு", logout_confirm: "வெளியேறவா?", ok: "சரி", cancel: "ரத்து", help_doc_content: "KunQiong Player\n\nகுறுக்குவழிகள்:\nஸ்பேஸ் - இயக்கு/இடைநிறுத்து\n← / → - பின்னோக்கி/முன்னோக்கி\n↑ / ↓ - ஒலி\nF - முழுத்திரை\nM - ஒலிமூடு", shortcuts_content: "ஸ்பேஸ் - இயக்கு/இடைநிறுத்து\n← - பின்னோக்கி\n→ - முன்னோக்கி\n↑/↓ - ஒலி\nF - முழுத்திரை\nM - ஒலிமூடு\nEsc - முழுத்திரையிலிருந்து வெளியேறு\nCtrl+S - நிறுத்து", about_content: "KunQiong Player\n\nAI வீடியோ பிளேயர்.\n\n【செயல்பாடுகள்】\n• பல வடிவங்கள்\n• ஹார்ட்வேர் டிகோடிங்\n• படம்/ஆடியோ சரிசெய்தல்\n• இரட்டை வசன வரிகள்\n• DLNA\n• சினிமா மோட்" }
    }
};
