/**
 * ไทย
 */
export default {
    translation: {
        app: { title: "KunQiong Player", subtitle: "Powered by KunQiong AI", custom_software: "ซอฟต์แวร์ตามสั่ง", login: "เข้าสู่ระบบ", not_logged_in: "ผู้ใช้ทั่วไป", logged_in: "เข้าสู่แล้ว", login_tip: "เข้าสู่ระบบเพื่อฟีเจอร์เพิ่มเติม", login_action: "เข้าสู่ระบบ", redirecting: "กำลังเปลี่ยนเส้นทาง...", login_in_browser: "กรุณาเข้าสู่ระบบในเบราว์เซอร์", relogin: "เข้าสู่ระบบอีกครั้ง", login_success_sync: "เข้าสู่สำเร็จ กำลังซิงค์...", vip_user: "สมาชิก", logout: "ออกจากระบบ", token_label: "โทเค็น:", welcome_tip: "ลากวิดีโอมาวางที่นี่", loading: "กำลังโหลด...", screenshot_path: "โฟลเดอร์ภาพ:", global_brightness: "ความสว่าง", reset: "รีเซ็ต", reset_all: "รีเซ็ตทั้งหมด", ok: "ตกลง", cancel: "ยกเลิก", apply: "นำไปใช้", unit: { ms: "ms", s: "วินาที", times: "x", items: "" } },
        menu: { file: "ไฟล์", open_file: "เปิดไฟล์...", open_folder: "เปิดโฟลเดอร์...", open_url: "เปิด URL...", exit: "ออก", play: "เล่น", play_pause: "เล่น/หยุดชั่วคราว", stop: "หยุด", next: "ถัดไป", prev: "ก่อนหน้า", fast_forward: "เร่ง", rewind: "ย้อน", effects: "เอฟเฟกต์", splitter: "สปลิตเตอร์", video_decoder: "ตัวถอดรหัสวิดีโอ", audio_decoder: "ตัวถอดรหัสเสียง", renderer: "เรนเดอร์เรอร์", auto_select: "อัตโนมัติ", control: "ควบคุม", subtitle: "คำบรรยาย", picture_quality: "ภาพ", audio_adjust: "เสียง", settings: "การตั้งค่า", help: "ช่วยเหลือ", help_doc: "เอกสาร", shortcuts: "ทางลัด", licenses: "ไลเซนส์ของบุคคลที่สาม", privacy: "ความเป็นส่วนตัว", check_update: "ตรวจสอบอัปเดต...", feedback: "ความคิดเห็น", about: "เกี่ยวกับ", language: "ภาษา", lang_zh: "简体中文", lang_en: "English" },
        playlist: { title: "เพลย์ลิสต์", add: "เพิ่ม", clear: "ล้าง", loop: "วนรายการ", loop_list: "วนรายการ", loop_list_title: "วนรายการ", loop_single: "วนหนึ่ง", loop_single_title: "วนหนึ่ง", random: "สุ่ม", random_title: "สุ่ม", empty: "เพลย์ลิสต์ว่าง", empty_tip: "คลิก \"เพิ่ม\" หรือลากไฟล์มา", ad_placeholder: "โฆษณา" },
        picture: { title: "ปรับภาพ", ratio: "อัตราส่วน", ratio_original: "ต้นฉบับ", ratio_fill: "เติม", rotation: "หมุน", flip_h: "แนวนอน", flip_v: "แนวตั้ง", pan: "แพน", zoom: "ซูม", presets: { default: "ค่าเริ่มต้น", bright: "สว่าง", soft: "นุ่ม", retro: "เรโทร" } },
        audio: { title: "เสียง", volume: "ระดับเสียง", channel: "ช่อง", channel_default: "ค่าเริ่มต้น", channel_left: "ซ้าย", channel_right: "ขวา", sync: "ซิงค์", track: "แทร็ก", track_default: "ค่าเริ่มต้น", load_track: "โหลดแทร็ก" },
        subtitle: { title: "คำบรรยาย", main_tab: "หลัก", sec_tab: "รอง", select: "เลือก", hide: "ซ่อน", load: "โหลด", enable_sec: "เปิดรอง", style: "สไตล์", font_yahei: "Microsoft YaHei", font_hei: "SimHei", font_song: "SimSun", font_kai: "KaiTi", sync: "ซิงค์", position: "ตำแหน่ง", pos_up: "บน", pos_down: "ล่าง", pos_left: "ซ้าย", pos_right: "ขวา", continue_effect: "ใช้เสมอ", color_title: "สี", basic_color: "สีพื้นฐาน", custom_color: "กำหนดเอง", cancel: "ยกเลิก", confirm: "ยืนยัน" },
        control: { title: "ควบคุม", left_eye: "ตาซ้าย", surround: "เซอร์ราวด์", threed: "โหมด 3D", settings: "การตั้งค่า" },
        lefteye: { title: "ตาซ้าย", view_angle: "มุมมอง", brightness: "ความสว่าง", contrast: "ความคมชัด" },
        surround: { title: "เซอร์ราวด์", mode: "โหมด", mode_off: "ปิด", mode_stereo: "สเตอริโอ", intensity: "ความเข้ม", bass: "เบส" },
        threed: { title: "3D", mode: "โหมด", mode_off: "ปิด", mode_anaglyph: "อานาไกลฟ์", mode_sbs: "ข้างกัน", mode_tb: "บน/ล่าง", depth: "ความลึก", eye_dist: "ระยะตา" },
        settings: { title: "การตั้งค่าขั้นสูง", tabs: { general: "ทั่วไป", playback: "การเล่น" }, sidebar: { list: "พื้นที่รายการ", hotkey: "ทางลัด", screenshot: "ภาพหน้าจอ", file_assoc: "เชื่อมโยงไฟล์", playback_basic: "การเล่นพื้นฐาน" }, playback: { title: "การเล่นพื้นฐาน", step_group: "เร่ง/ย้อน", forward_once: "เร่งครั้งเดียว", rewind_once: "ย้อนครั้งเดียว", speed_group: "ความเร็ว", speed_once: "ความเร็ว", playlist_group: "เพลย์ลิสต์", continue_last: "เล่นรายการล่าสุดต่อ", auto_add: "เพิ่มไฟล์คล้ายกัน", clear_on_open: "ล้างเมื่อเปิด", prompt_cleanup: "แจ้งล้างเมื่อรายการยาว" }, hotkey: { title: "ทางลัด", header_command: "คำสั่ง", header_mouse: "เมาส์", header_key: "ปุ่ม", header_action: "การกระทำ", disable_swf: "ปิดสำหรับ SWF", btn_modify: "แก้ไข", actions: { playPause: "เล่น/หยุด", stop: "หยุด", fastForward: "เร่ง", rewind: "ย้อน", speedUp: "เร็วขึ้น", speedDown: "ช้าลง", volumeUp: "เสียงขึ้น", volumeDown: "เสียงลง", mute: "ปิดเสียง", fullscreen: "เต็มจอ", exitFullscreen: "ออกเต็มจอ" }, mouse_left: "คลิกซ้าย" }, screenshot: { title: "ภาพหน้าจอ", path_label: "โฟลเดอร์", btn_change: "เปลี่ยนโฟลเดอร์", format_label: "รูปแบบ", tool_label: "เครื่องมือ", popup_label: "แสดงหลังถ่าย" }, file_assoc: { title: "เชื่อมโยงไฟล์", status_checking: "กำลังตรวจ...", status_is_default: "เป็นตัวเล่นค่าเริ่มต้น", status_not_default: "ไม่ใช่ค่าเริ่มต้น", status_check_failed: "ตรวจสอบล้มเหลว", btn_set_default: "ตั้งเป็นค่าเริ่มต้น", btn_already_set: "ตั้งแล้ว", btn_select_all: "เลือกทั้งหมด", btn_select_none: "ไม่เลือก", btn_restore: "คืนค่า", always_assoc: "เชื่อมโยงเสมอ", formats: { wmv: "Windows Media Video", real: "Real Media", vcd: "VCD/DVD", quicktime: "QuickTime", other_video: "วิดีโออื่น", other_audio: "เสียงอื่น", animation: "แอนิเมชัน", playlist: "เพลย์ลิสต์", subtitle: "คำบรรยาย" } }, list: { title: "พื้นที่รายการ", display_group: "การแสดงผล", always_expand: "ขยายเสมอ", always_close: "ปิดเสมอ", remember: "จำสถานะ", a11y: "การเข้าถึง", text_auto: "ขนาดตัวอักษรอัตโนมัติ", text_manual: "ขนาดมือ" } },
        context_menu: { play: "เล่น", pause: "หยุดชั่วคราว", stop: "หยุด", prev: "ก่อนหน้า", next: "ถัดไป", fullscreen: "เต็มจอ", exit_fullscreen: "ออกเต็มจอ", screenshot: "ภาพหน้าจอ", picture: "ภาพ", audio: "เสียง", open: "เปิดไฟล์...", properties: "คุณสมบัติ", settings: "การตั้งค่า" },
        properties: { title: "คุณสมบัติ", filename_empty: "ไม่มีวิดีโอ", label_type: "ประเภท:", label_duration: "ระยะเวลา:", label_size: "ขนาด:", label_location: "ที่อยู่:", section_video: "วิดีโอ", label_resolution: "ความละเอียด:", label_codec: "ตัวแปลงรหัส:", label_framerate: "FPS:", label_bitrate: "บิตเรต:", btn_more: "เพิ่มเติม", type_video: "วิดีโอ" },
        screenshot_preview: { title: "ดูตัวอย่างภาพ", label_no_popup: "ไม่แสดงอีก", btn_save: "บันทึก" },
        dlna: { title: "อุปกรณ์ DLNA", subtitle: "เลือกอุปกรณ์ส่งออก", searching: "กำลังค้นหาอุปกรณ์...", no_device: "ไม่พบอุปกรณ์", no_device_hint: "รีเฟรชหรือตรวจสอบเครือข่าย", select_device_first: "กรุณาเลือกอุปกรณ์", device_ready: "พร้อม", help_guide_title: "คู่มือ DLNA", help_guide_content: "【ข้อกำหนด】\n• PC และ TV อยู่ใน Wi-Fi/LAN เดียวกัน\n• เปิด DLNA/Cast บน TV\n\n【ขั้นตอน】\n1. กด [DLNA] ด้านล่าง\n2. \"รีเฟรช\" เพื่อค้นหา\n3. เลือก TV แล้ว \"เชื่อมต่อ\"\n\n【ช่วยเหลือ】\n• ไม่มีอุปกรณ์: ตรวจไฟร์วอลล์หรือรีสตาร์ท Cast\n• ค้าง: ลดบิตเรต\n• ไม่เล่น: ใช้ MP4/MKV", connecting_msg: "กำลังเชื่อมต่อ: {{name}}\n\nต้องใช้เซิร์ฟเวอร์ DLNA โหมดสาธิต", connecting_title: "การเชื่อมต่อ DLNA" },
        update: {
            no_update_title: "ตรวจสอบการอัปเดต",
            no_update_message: "เวอร์ชันปัจจุบัน V{{version}} เป็นเวอร์ชันล่าสุดแล้ว",
            no_update_detail: "ไม่พบเวอร์ชันใหม่กว่า เพลิดเพลินกับการใช้งานแอปได้เลย",
            check_failed_title: "ตรวจสอบการอัปเดตล้มเหลว",
            check_failed_message: "ไม่สามารถเชื่อมต่อกับเซิร์ฟเวอร์อัปเดตได้: {{error}}",
            check_not_available: "ฟีเจอร์อัปเดตไม่พร้อมใช้งานในสภาพแวดล้อมนี้",
            checking: "กำลังตรวจสอบการอัปเดต...",
            check_failed_toast: "ตรวจสอบการอัปเดตล้มเหลว โปรดลองอีกครั้งภายหลัง"
        },
        recent: { title: "ล่าสุด", empty: "ยังไม่มีรายการเล่นล่าสุด", empty_tip: "วิดีโอที่เล่นจะแสดงที่นี่", clear_all: "ล้างทั้งหมด", remove_selected: "ลบที่เลือก" },
        favorites: { title: "รายการโปรด", add_to_favorites: "เพิ่มในรายการโปรด", my_favorites: "รายการโปรดของฉัน", empty: "ยังไม่มีรายการโปรด", empty_tip: "คลิกขวาและเลือก \"เพิ่มในรายการโปรด\" ขณะเล่น", no_video: "กรุณาเลือกหรือเล่นวิดีโอก่อน", cannot_save: "เพิ่มในรายการโปรดไม่ได้", added: "เพิ่มในรายการโปรดแล้ว", remove: "ลบออกจากรายการโปรด", invalid_entry: "รายการโปรดไม่ถูกต้อง" },
        dialog: { close_confirm: "ปิด KunQiong Player?", close_title: "ยืนยันการออก", notice: "แจ้งเตือน", logout_confirm: "ออกจากระบบ?", ok: "ตกลง", cancel: "ยกเลิก", help_doc_content: "KunQiong Player\n\nทางลัด:\nSpace - เล่น/หยุด\n← / → - ย้อน/เร่ง\n↑ / ↓ - เสียง\nF - เต็มจอ\nM - ปิดเสียง", shortcuts_content: "Space - เล่น/หยุด\n← - ย้อน\n→ - เร่ง\n↑/↓ - เสียง\nF - เต็มจอ\nM - ปิดเสียง\nEsc - ออกเต็มจอ\nCtrl+S - หยุด", about_content: "KunQiong Player\n\nเครื่องเล่นวิดีโอด้วย AI\n\n【ฟีเจอร์】\n• รองรับหลายรูปแบบ\n• ถอดรหัสด้วยฮาร์ดแวร์\n• ปรับภาพ/เสียง\n• คำบรรยายคู่\n• DLNA\n• โหมดโรงภาพยนตร์" }
    }
};
