/**
 * Tagalog
 */
export default {
    translation: {
        app: { title: "KunQiong Player", subtitle: "Powered by KunQiong AI", custom_software: "Pasadyang software", login: "Mag-log in", not_logged_in: "Bisita", logged_in: "Naka-log in", login_tip: "Mag-log in para sa mas maraming function", login_action: "Mag-log in", redirecting: "Nagre-redirect...", login_in_browser: "Kumpletuhin ang log in sa browser.", relogin: "Mag-log in muli", login_success_sync: "Naka-log in. Nagse-sync...", vip_user: "Kasapi", logout: "Mag-log out", token_label: "Token:", welcome_tip: "I-drag ang video dito", loading: "Naglo-load...", screenshot_path: "Folder ng screenshot:", global_brightness: "Liwanag", reset: "I-reset", reset_all: "I-reset lahat", ok: "OK", cancel: "Kanselahin", apply: "Ilapat", unit: { ms: "ms", s: "s", times: "x", items: "" } },
        menu: { file: "File", open_file: "Buksan ang file...", open_folder: "Buksan ang folder...", open_url: "Buksan ang URL...", exit: "Lumabas", play: "I-play", play_pause: "I-play/I-pause", stop: "I-stop", next: "Susunod", prev: "Nakaraan", fast_forward: "Pasulong", rewind: "Paatras", effects: "Mga effect", splitter: "Splitter", video_decoder: "Video decoder", audio_decoder: "Audio decoder", renderer: "Renderer", auto_select: "Auto", control: "Kontrol", subtitle: "Subtitle", picture_quality: "Larawan", audio_adjust: "Audio", settings: "Mga setting", help: "Tulong", help_doc: "Dokumentasyon", shortcuts: "Shortcut", licenses: "Mga lisensya ng third-party", privacy: "Privacy", check_update: "Suriin ang update...", feedback: "Feedback", about: "Tungkol", language: "Wika", lang_zh: "简体中文", lang_en: "English" },
        playlist: { title: "Playlist", add: "Idagdag", clear: "Burahin", loop: "Ulitin ang listahan", loop_list: "Ulitin ang listahan", loop_list_title: "Ulitin ang listahan", loop_single: "Ulitin ang isa", loop_single_title: "Ulitin ang isa", random: "Random", random_title: "Random", empty: "Walang laman ang listahan", empty_tip: "I-click \"Idagdag\" o i-drag ang mga file", ad_placeholder: "Ad" },
        picture: { title: "Larawan", ratio: "Ratio", ratio_original: "Orihinal", ratio_fill: "Punuin", rotation: "I-rotate", flip_h: "Pahalang", flip_v: "Patayo", pan: "Pan", zoom: "Zoom", presets: { default: "Default", bright: "Maliwanag", soft: "Malambot", retro: "Retro" } },
        audio: { title: "Audio", volume: "Volume", channel: "Channel", channel_default: "Default", channel_left: "Kaliwa", channel_right: "Kanan", sync: "Sync", track: "Track", track_default: "Default", load_track: "I-load ang track" },
        subtitle: { title: "Subtitle", main_tab: "Pangunahin", sec_tab: "Pangalawa", select: "Piliin", hide: "Itago", load: "I-load", enable_sec: "I-enable ang pangalawa", style: "Estilo", font_yahei: "Microsoft YaHei", font_hei: "SimHei", font_song: "SimSun", font_kai: "KaiTi", sync: "Sync", position: "Posisyon", pos_up: "Itaas", pos_down: "Ibaba", pos_left: "Kaliwa", pos_right: "Kanan", continue_effect: "Laging ilapat", color_title: "Kulay", basic_color: "Mga pangunahing kulay", custom_color: "Pasadyang", cancel: "Kanselahin", confirm: "Kumpirmahin" },
        control: { title: "Kontrol", left_eye: "Kaliwang mata", surround: "Surround", threed: "3D mode", settings: "Mga setting" },
        lefteye: { title: "Kaliwang mata", view_angle: "Angulo ng view", brightness: "Liwanag", contrast: "Kontrast" },
        surround: { title: "Surround", mode: "Mode", mode_off: "Off", mode_stereo: "Stereo", intensity: "Intensity", bass: "Bass" },
        threed: { title: "3D", mode: "Mode", mode_off: "Off", mode_anaglyph: "Anaglyph", mode_sbs: "Side by side", mode_tb: "Itaas/ibaba", depth: "Lalim", eye_dist: "Distansya ng mata" },
        settings: { title: "Advanced na setting", tabs: { general: "Pangkalahatan", playback: "Playback" }, sidebar: { list: "Lugar ng listahan", hotkey: "Shortcut", screenshot: "Screenshot", file_assoc: "File association", playback_basic: "Basic playback" }, playback: { title: "Basic playback", step_group: "Pasulong/Paatras", forward_once: "Isang beses pasulong", rewind_once: "Isang beses paatras", speed_group: "Bilis", speed_once: "Bilis", playlist_group: "Playlist", continue_last: "Ipagpatuloy ang huling listahan", auto_add: "Idagdag ang katulad", clear_on_open: "Burahin kapag binuksan", prompt_cleanup: "Magmungkahi ng cleanup" }, hotkey: { title: "Shortcut", header_command: "Command", header_mouse: "Mouse", header_key: "Key", header_action: "Aksyon", disable_swf: "I-disable para sa SWF", btn_modify: "Baguhin", actions: { playPause: "I-play/I-pause", stop: "I-stop", fastForward: "Pasulong", rewind: "Paatras", speedUp: "Bilisan", speedDown: "Bagalan", volumeUp: "Volume +", volumeDown: "Volume -", mute: "I-mute", fullscreen: "Fullscreen", exitFullscreen: "Lumabas sa fullscreen" }, mouse_left: "Left click" }, screenshot: { title: "Screenshot", path_label: "Folder", btn_change: "Baguhin ang folder", format_label: "Format", tool_label: "Tool", popup_label: "Ipakita pagkatapos i-capture" }, file_assoc: { title: "File association", status_checking: "Sinusuri...", status_is_default: "Default player", status_not_default: "Hindi default", status_check_failed: "Nabigo ang pagsuri", btn_set_default: "Itakda bilang default", btn_already_set: "Nakatakda na", btn_select_all: "Piliin lahat", btn_select_none: "Wala", btn_restore: "I-restore", always_assoc: "Laging i-associate", formats: { wmv: "Windows Media Video", real: "Real Media", vcd: "VCD/DVD", quicktime: "QuickTime", other_video: "Iba pang video", other_audio: "Iba pang audio", animation: "Animation", playlist: "Playlist", subtitle: "Subtitle" } }, list: { title: "Lugar ng listahan", display_group: "Display", always_expand: "Laging i-expand", always_close: "Laging i-collapse", remember: "Tandaan ang estado", a11y: "Accessibility", text_auto: "Laki ng text auto", text_manual: "Manual" } },
        context_menu: { play: "I-play", pause: "I-pause", stop: "I-stop", prev: "Nakaraan", next: "Susunod", fullscreen: "Fullscreen", exit_fullscreen: "Lumabas sa fullscreen", screenshot: "Screenshot", picture: "Larawan", audio: "Audio", open: "Buksan ang file...", properties: "Mga property", settings: "Mga setting" },
        properties: { title: "Mga property", filename_empty: "Walang video", label_type: "Uri:", label_duration: "Tagal:", label_size: "Laki:", label_location: "Lokasyon:", section_video: "Video", label_resolution: "Resolution:", label_codec: "Codec:", label_framerate: "FPS:", label_bitrate: "Bitrate:", btn_more: "Higit pa", type_video: "Video" },
        screenshot_preview: { title: "Preview ng screenshot", label_no_popup: "Huwag na ipakita", btn_save: "I-save" },
        dlna: { title: "Mga device na DLNA", subtitle: "Piliin ang output device", searching: "Naghahanap ng device...", no_device: "Walang nahanap na device", no_device_hint: "I-refresh o suriin ang network", select_device_first: "Pumili muna ng device", device_ready: "Handa", help_guide_title: "Gabay sa DLNA", help_guide_content: "【Mga kailangan】\n• PC at TV sa parehong Wi-Fi/LAN.\n• I-enable ang DLNA/Cast sa TV.\n\n【Mga hakbang】\n1. I-click ang [DLNA] sa ibaba.\n2. \"Refresh\" para maghanap.\n3. Piliin ang TV at \"Connect\".\n\n【Tulong】\n• Walang device: firewall o i-restart ang Cast.\n• Lag: babaan ang bitrate.\n• Hindi nagpe-play: gumamit ng MP4/MKV.", connecting_msg: "Kumokonekta sa: {{name}}\n\nKailangan ng DLNA server. Demo mode.", connecting_title: "Koneksyon ng DLNA" },
        update: { no_update_title: "Suriin ang update", no_update_message: "Ang kasalukuyang bersyon V{{version}} ay pinakabago na", no_update_detail: "Walang nahanap na mas bagong bersyon. Magsaya sa app.", check_failed_title: "Nabigo ang pagsuri ng update", check_failed_message: "Hindi makakonekta sa update server: {{error}}", check_not_available: "Hindi available ang update sa kapaligirang ito", checking: "Sinusuri ang update...", check_failed_toast: "Nabigo ang pagsuri ng update, subukan mamaya" },
        recent: { title: "Kamakailan", empty: "Walang kamakailang playback", empty_tip: "Lalabas dito ang mga napanood na video", clear_all: "Burahin lahat", remove_selected: "Alisin ang napili" },
        favorites: { title: "Mga paborito", add_to_favorites: "Idagdag sa mga paborito", my_favorites: "Aking mga paborito", empty: "Wala pang paborito", empty_tip: "Right-click at piliin \"Idagdag sa mga paborito\" habang nagpe-play", no_video: "Pumili o mag-play muna ng video", cannot_save: "Hindi maidagdag sa mga paborito", added: "Naidagdag sa mga paborito", remove: "Alisin sa mga paborito", invalid_entry: "Hindi wastong paborito" },
        dialog: { close_confirm: "Isara ang KunQiong Player?", close_title: "Kumpirmahin ang pagsara", notice: "Paalala", logout_confirm: "Mag-log out?", ok: "OK", cancel: "Kanselahin", help_doc_content: "KunQiong Player\n\nShortcut:\nSpace - I-play/I-pause\n← / → - Paatras/Pasulong\n↑ / ↓ - Volume\nF - Fullscreen\nM - I-mute", shortcuts_content: "Space - I-play/I-pause\n← - Paatras\n→ - Pasulong\n↑/↓ - Volume\nF - Fullscreen\nM - I-mute\nEsc - Lumabas sa fullscreen\nCtrl+S - I-stop", about_content: "KunQiong Player\n\nVideo player na may AI.\n\n【Mga function】\n• Maraming format\n• Hardware decoding\n• Larawan/audio adjustment\n• Doble na subtitle\n• DLNA\n• Cinema mode" }
    }
};
