/**
 * Türkçe
 */
export default {
    translation: {
        app: { title: "KunQiong Player", subtitle: "Powered by KunQiong AI", custom_software: "Özel yazılım", login: "Giriş", not_logged_in: "Misafir", logged_in: "Giriş yapıldı", login_tip: "Daha fazla özellik için giriş yapın", login_action: "Giriş yap", redirecting: "Yönlendiriliyor...", login_in_browser: "Lütfen tarayıcıda giriş yapın.", relogin: "Tekrar giriş", login_success_sync: "Giriş başarılı. Senkronize ediliyor...", vip_user: "Üye", logout: "Çıkış", token_label: "Token:", welcome_tip: "Video dosyalarını buraya sürükleyin", loading: "Yükleniyor...", screenshot_path: "Ekran görüntüsü klasörü:", global_brightness: "Parlaklık", reset: "Sıfırla", reset_all: "Tümünü sıfırla", ok: "Tamam", cancel: "İptal", apply: "Uygula", unit: { ms: "ms", s: "s", times: "x", items: "" } },
        menu: { file: "Dosya", open_file: "Dosya aç...", open_folder: "Klasör aç...", open_url: "URL aç...", exit: "Çıkış", play: "Oynat", play_pause: "Oynat/Duraklat", stop: "Durdur", next: "Sonraki", prev: "Önceki", fast_forward: "İleri", rewind: "Geri", effects: "Efektler", splitter: "Splitter", video_decoder: "Video çözücü", audio_decoder: "Ses çözücü", renderer: "Renderer", auto_select: "Otomatik", control: "Kontrol", subtitle: "Altyazı", picture_quality: "Görüntü", audio_adjust: "Ses", settings: "Ayarlar", help: "Yardım", help_doc: "Dokümantasyon", shortcuts: "Kısayollar", licenses: "Üçüncü taraf lisansları", privacy: "Gizlilik", check_update: "Güncellemeleri kontrol et...", feedback: "Geri bildirim", about: "Hakkında", language: "Dil", lang_zh: "简体中文", lang_en: "English" },
        playlist: { title: "Çalma listesi", add: "Ekle", clear: "Temizle", loop: "Listeyi tekrarla", loop_list: "Listeyi tekrarla", loop_list_title: "Listeyi tekrarla", loop_single: "Tekrarla", loop_single_title: "Tekrarla", random: "Karıştır", random_title: "Karıştır", empty: "Liste boş", empty_tip: "\"Ekle\"ye tıklayın veya dosya sürükleyin", ad_placeholder: "Reklam" },
        picture: { title: "Görüntü", ratio: "Oran", ratio_original: "Orijinal", ratio_fill: "Doldur", rotation: "Döndür", flip_h: "Yatay", flip_v: "Dikey", pan: "Pan", zoom: "Yakınlaştır", presets: { default: "Varsayılan", bright: "Parlak", soft: "Yumuşak", retro: "Retro" } },
        audio: { title: "Ses", volume: "Ses düzeyi", channel: "Kanal", channel_default: "Varsayılan", channel_left: "Sol", channel_right: "Sağ", sync: "Senkron", track: "Parça", track_default: "Varsayılan", load_track: "Parça yükle" },
        subtitle: { title: "Altyazı", main_tab: "Ana", sec_tab: "İkincil", select: "Seç", hide: "Gizle", load: "Yükle", enable_sec: "İkincili etkinleştir", style: "Stil", font_yahei: "Microsoft YaHei", font_hei: "SimHei", font_song: "SimSun", font_kai: "KaiTi", sync: "Senkron", position: "Konum", pos_up: "Yukarı", pos_down: "Aşağı", pos_left: "Sol", pos_right: "Sağ", continue_effect: "Her zaman uygula", color_title: "Renk", basic_color: "Temel renkler", custom_color: "Özel", cancel: "İptal", confirm: "Onayla" },
        control: { title: "Kontrol", left_eye: "Sol göz", surround: "Surround", threed: "3D modu", settings: "Ayarlar" },
        lefteye: { title: "Sol göz", view_angle: "Görüş açısı", brightness: "Parlaklık", contrast: "Kontrast" },
        surround: { title: "Surround", mode: "Mod", mode_off: "Kapalı", mode_stereo: "Stereo", intensity: "Yoğunluk", bass: "Bas" },
        threed: { title: "3D", mode: "Mod", mode_off: "Kapalı", mode_anaglyph: "Anaglif", mode_sbs: "Yan yana", mode_tb: "Üst/alt", depth: "Derinlik", eye_dist: "Göz mesafesi" },
        settings: { title: "Gelişmiş ayarlar", tabs: { general: "Genel", playback: "Oynatma" }, sidebar: { list: "Liste alanı", hotkey: "Kısayollar", screenshot: "Ekran görüntüleri", file_assoc: "Dosya ilişkilendirme", playback_basic: "Temel oynatma" }, playback: { title: "Temel oynatma", step_group: "İleri/Geri", forward_once: "Bir kez ileri", rewind_once: "Bir kez geri", speed_group: "Hız", speed_once: "Hız", playlist_group: "Çalma listesi", continue_last: "Son listeyi sürdür", auto_add: "Benzerleri ekle", clear_on_open: "Açarken temizle", prompt_cleanup: "Uzun listede temizlik öner" }, hotkey: { title: "Kısayollar", header_command: "Komut", header_mouse: "Fare", header_key: "Tuş", header_action: "Eylem", disable_swf: "SWF için devre dışı", btn_modify: "Değiştir", actions: { playPause: "Oynat/Duraklat", stop: "Durdur", fastForward: "İleri", rewind: "Geri", speedUp: "Hızlandır", speedDown: "Yavaşlat", volumeUp: "Ses +", volumeDown: "Ses -", mute: "Sessiz", fullscreen: "Tam ekran", exitFullscreen: "Tam ekrandan çık" }, mouse_left: "Sol tık" }, screenshot: { title: "Ekran görüntüleri", path_label: "Klasör", btn_change: "Klasörü değiştir", format_label: "Biçim", tool_label: "Araç", popup_label: "Yakaladıktan sonra göster" }, file_assoc: { title: "Dosya ilişkilendirme", status_checking: "Kontrol ediliyor...", status_is_default: "Varsayılan oynatıcı", status_not_default: "Varsayılan değil", status_check_failed: "Kontrol başarısız", btn_set_default: "Varsayılan yap", btn_already_set: "Zaten ayarlı", btn_select_all: "Tümünü seç", btn_select_none: "Hiçbiri", btn_restore: "Geri yükle", always_assoc: "Her zaman ilişkilendir", formats: { wmv: "Windows Media Video", real: "Real Media", vcd: "VCD/DVD", quicktime: "QuickTime", other_video: "Diğer video", other_audio: "Diğer ses", animation: "Animasyon", playlist: "Çalma listesi", subtitle: "Altyazı" } }, list: { title: "Liste alanı", display_group: "Görüntüleme", always_expand: "Her zaman genişlet", always_close: "Her zaman daralt", remember: "Durumu hatırla", a11y: "Erişilebilirlik", text_auto: "Metin boyutu otomatik", text_manual: "Manuel" } },
        context_menu: { play: "Oynat", pause: "Duraklat", stop: "Durdur", prev: "Önceki", next: "Sonraki", fullscreen: "Tam ekran", exit_fullscreen: "Tam ekrandan çık", screenshot: "Ekran görüntüsü", picture: "Görüntü", audio: "Ses", open: "Dosya aç...", properties: "Özellikler", settings: "Ayarlar" },
        properties: { title: "Özellikler", filename_empty: "Video yok", label_type: "Tür:", label_duration: "Süre:", label_size: "Boyut:", label_location: "Konum:", section_video: "Video", label_resolution: "Çözünürlük:", label_codec: "Codec:", label_framerate: "FPS:", label_bitrate: "Bit hızı:", btn_more: "Daha fazla", type_video: "Video" },
        screenshot_preview: { title: "Ekran görüntüsü önizleme", label_no_popup: "Bir daha gösterme", btn_save: "Kaydet" },
        dlna: { title: "DLNA cihazları", subtitle: "Çıkış cihazı seçin", searching: "Cihaz aranıyor...", no_device: "Cihaz bulunamadı", no_device_hint: "Yenile veya ağı kontrol et", select_device_first: "Önce bir cihaz seçin", device_ready: "Hazır", help_guide_title: "DLNA kılavuzu", help_guide_content: "【Gereksinimler】\n• PC ve TV aynı Wi-Fi/LAN'de.\n• TV'de DLNA/Cast açın.\n\n【Adımlar】\n1. Altta [DLNA]'ya tıklayın.\n2. Aramak için \"Yenile\".\n3. TV seçin ve \"Bağlan\".\n\n【Yardım】\n• Cihaz yok: güvenlik duvarı veya Cast'i yeniden başlatın.\n• Takılma: bit hızını düşürün.\n• Oynatmıyor: MP4/MKV kullanın.", connecting_msg: "Bağlanıyor: {{name}}\n\nDLNA sunucusu gerekli. Demo modu.", connecting_title: "DLNA bağlantısı" },
        update: {
            no_update_title: "Güncellemeleri denetle",
            no_update_message: "Geçerli sürüm V{{version}} günceldir",
            no_update_detail: "Daha yeni bir sürüm bulunamadı. Uygulamayı keyifle kullanın.",
            check_failed_title: "Güncelleme denetimi başarısız",
            check_failed_message: "Güncelleme sunucusuna bağlanılamıyor: {{error}}",
            check_not_available: "Bu ortamda güncelleme özelliği kullanılamıyor",
            checking: "Güncellemeler denetleniyor...",
            check_failed_toast: "Güncelleme denetimi başarısız, lütfen daha sonra tekrar deneyin"
        },
        recent: { title: "Son", empty: "Henüz son oynatma yok", empty_tip: "Oynatılan videolar burada görünecek", clear_all: "Tümünü temizle", remove_selected: "Seçilenleri kaldır" },
        favorites: { title: "Favoriler", add_to_favorites: "Favorilere ekle", my_favorites: "Favorilerim", empty: "Henüz favori yok", empty_tip: "Oynatırken sağ tıklayıp \"Favorilere ekle\" seçin", no_video: "Önce bir video seçin veya oynatın", cannot_save: "Favorilere eklenemiyor", added: "Favorilere eklendi", remove: "Favorilerden kaldır", invalid_entry: "Geçersiz favori" },
        dialog: { close_confirm: "KunQiong Player kapatılsın mı?", close_title: "Çıkışı onayla", notice: "Bildirim", logout_confirm: "Çıkış yapılsın mı?", ok: "Tamam", cancel: "İptal", help_doc_content: "KunQiong Player\n\nKısayollar:\nBoşluk - Oynat/Duraklat\n← / → - Geri/İleri\n↑ / ↓ - Ses\nF - Tam ekran\nM - Sessiz", shortcuts_content: "Boşluk - Oynat/Duraklat\n← - Geri\n→ - İleri\n↑/↓ - Ses\nF - Tam ekran\nM - Sessiz\nEsc - Tam ekrandan çık\nCtrl+S - Durdur", about_content: "KunQiong Player\n\nAI destekli video oynatıcı.\n\n【Özellikler】\n• Birden fazla format\n• Donanım çözümleme\n• Görüntü/ses ayarı\n• Çift altyazı\n• DLNA\n• Sinema modu" }
    }
};
