/**
 * Українська
 */
export default {
    translation: {
        app: { title: "KunQiong Player", subtitle: "Powered by KunQiong AI", custom_software: "Індивідуальне ПЗ", login: "Увійти", not_logged_in: "Гість", logged_in: "Увійшли", login_tip: "Увійдіть для більше функцій", login_action: "Увійти", redirecting: "Перенаправлення...", login_in_browser: "Завершіть вхід у браузері.", relogin: "Увійти знову", login_success_sync: "Вхід виконано. Синхронізація...", vip_user: "Учасник", logout: "Вийти", token_label: "Токен:", welcome_tip: "Перетягніть відео сюди", loading: "Завантаження...", screenshot_path: "Папка знімків:", global_brightness: "Яскравість", reset: "Скинути", reset_all: "Скинути все", ok: "OK", cancel: "Скасувати", apply: "Застосувати", unit: { ms: "мс", s: "с", times: "x", items: "" } },
        menu: { file: "Файл", open_file: "Відкрити файл...", open_folder: "Відкрити папку...", open_url: "Відкрити URL...", exit: "Вихід", play: "Відтворення", play_pause: "Відтв./Пауза", stop: "Стоп", next: "Далі", prev: "Назад", fast_forward: "Вперед", rewind: "Назад", effects: "Ефекти", splitter: "Спліттер", video_decoder: "Відеодекодер", audio_decoder: "Аудіодекодер", renderer: "Рендер", auto_select: "Авто", control: "Керування", subtitle: "Субтитри", picture_quality: "Зображення", audio_adjust: "Аудіо", settings: "Налаштування", help: "Допомога", help_doc: "Документація", shortcuts: "Гарячі клавіші", licenses: "Ліцензії сторонніх", privacy: "Конфіденційність", check_update: "Перевірити оновлення...", feedback: "Відгук", about: "Про програму", language: "Мова", lang_zh: "简体中文", lang_en: "English" },
        playlist: { title: "Список відтворення", add: "Додати", clear: "Очистити", loop: "Повтор списку", loop_list: "Повтор списку", loop_list_title: "Повтор списку", loop_single: "Повтор одного", loop_single_title: "Повтор одного", random: "Випадково", random_title: "Випадково", empty: "Список порожній", empty_tip: "Натисніть «Додати» або перетягніть файли", ad_placeholder: "Реклама" },
        picture: { title: "Зображення", ratio: "Співвідношення", ratio_original: "Оригінал", ratio_fill: "Заповнити", rotation: "Поворот", flip_h: "По горизонталі", flip_v: "По вертикалі", pan: "Панорама", zoom: "Масштаб", presets: { default: "За замовчуванням", bright: "Яскравий", soft: "М'який", retro: "Ретро" } },
        audio: { title: "Аудіо", volume: "Гучність", channel: "Канал", channel_default: "За замовчуванням", channel_left: "Лівий", channel_right: "Правий", sync: "Синхр.", track: "Доріжка", track_default: "За замовчуванням", load_track: "Завантажити" },
        subtitle: { title: "Субтитри", main_tab: "Основні", sec_tab: "Другі", select: "Вибір", hide: "Сховати", load: "Завантажити", enable_sec: "Увімкнути другі", style: "Стиль", font_yahei: "Microsoft YaHei", font_hei: "SimHei", font_song: "SimSun", font_kai: "KaiTi", sync: "Синхр.", position: "Положення", pos_up: "Вгору", pos_down: "Вниз", pos_left: "Вліво", pos_right: "Вправо", continue_effect: "Завжди застосовувати", color_title: "Колір", basic_color: "Основні кольори", custom_color: "Свій", cancel: "Скасувати", confirm: "ОК" },
        control: { title: "Керування", left_eye: "Ліве око", surround: "Об'ємний звук", threed: "3D режим", settings: "Налаштування" },
        lefteye: { title: "Ліве око", view_angle: "Кут", brightness: "Яскравість", contrast: "Контраст" },
        surround: { title: "Об'ємний звук", mode: "Режим", mode_off: "Вимк.", mode_stereo: "Стерео", intensity: "Інтенсивність", bass: "Низькі" },
        threed: { title: "3D", mode: "Режим", mode_off: "Вимк.", mode_anaglyph: "Анагліф", mode_sbs: "Пліч-о-пліч", mode_tb: "Верх/низ", depth: "Глибина", eye_dist: "Відстань очей" },
        settings: { title: "Додаткові налаштування", tabs: { general: "Загальні", playback: "Відтворення" }, sidebar: { list: "Область списку", hotkey: "Гарячі клавіші", screenshot: "Знімки", file_assoc: "Зв'язки файлів", playback_basic: "Базове відтв." }, playback: { title: "Базове відтворення", step_group: "Вперед/Назад", forward_once: "Вперед раз", rewind_once: "Назад раз", speed_group: "Швидкість", speed_once: "Швидкість", playlist_group: "Список", continue_last: "Продовжити список", auto_add: "Додавати подібні", clear_on_open: "Очищати при відкритті", prompt_cleanup: "Запропонувати очистку" }, hotkey: { title: "Гарячі клавіші", header_command: "Команда", header_mouse: "Миша", header_key: "Клавіша", header_action: "Дія", disable_swf: "Вимк. для SWF", btn_modify: "Змінити", actions: { playPause: "Відтв./Пауза", stop: "Стоп", fastForward: "Вперед", rewind: "Назад", speedUp: "Швидше", speedDown: "Повільніше", volumeUp: "Голосніше", volumeDown: "Тихіше", mute: "Без звуку", fullscreen: "Повний екран", exitFullscreen: "Вийти з повного екрана" }, mouse_left: "ЛКМ" }, screenshot: { title: "Знімки", path_label: "Папка", btn_change: "Змінити", format_label: "Формат", tool_label: "Інструмент", popup_label: "Показувати після знімка" }, file_assoc: { title: "Зв'язки файлів", status_checking: "Перевірка...", status_is_default: "Плеєр за замовчуванням", status_not_default: "Не за замовчуванням", status_check_failed: "Помилка перевірки", btn_set_default: "За замовчуванням", btn_already_set: "Встановлено", btn_select_all: "Усі", btn_select_none: "Ні", btn_restore: "Відновити", always_assoc: "Завжди зв'язувати", formats: { wmv: "Windows Media Video", real: "Real Media", vcd: "VCD/DVD", quicktime: "QuickTime", other_video: "Інше відео", other_audio: "Інше аудіо", animation: "Анімація", playlist: "Список", subtitle: "Субтитри" } }, list: { title: "Область списку", display_group: "Відображення", always_expand: "Розгортати", always_close: "Згортати", remember: "Запам'ятати", a11y: "Доступність", text_auto: "Розмір тексту авто", text_manual: "Вручну" } },
        context_menu: { play: "Відтворення", pause: "Пауза", stop: "Стоп", prev: "Назад", next: "Далі", fullscreen: "Повний екран", exit_fullscreen: "Вийти", screenshot: "Знімок", picture: "Зображення", audio: "Аудіо", open: "Відкрити файл...", properties: "Властивості", settings: "Налаштування" },
        properties: { title: "Властивості", filename_empty: "Немає відео", label_type: "Тип:", label_duration: "Тривалість:", label_size: "Розмір:", label_location: "Розташування:", section_video: "Відео", label_resolution: "Роздільність:", label_codec: "Кодек:", label_framerate: "Кадр/с:", label_bitrate: "Бітрейт:", btn_more: "Детальніше", type_video: "Відео" },
        screenshot_preview: { title: "Перегляд знімка", label_no_popup: "Більше не показувати", btn_save: "Зберегти" },
        dlna: { title: "Пристрої DLNA", subtitle: "Виберіть пристрій", searching: "Пошук пристроїв...", no_device: "Пристрої не знайдено", no_device_hint: "Оновити або перевірити мережу", select_device_first: "Спочатку виберіть пристрій", device_ready: "Готово", help_guide_title: "Керівництво DLNA", help_guide_content: "【Умови】\n• ПК і ТБ в одній мережі Wi-Fi/LAN.\n• Увімкніть DLNA/Cast на ТБ.\n\n【Кроки】\n1. Натисніть [DLNA] внизу.\n2. «Оновити» для пошуку.\n3. Виберіть ТБ і «Підключити».\n\n【Допомога】\n• Немає пристроїв: фаєрвол або перезапуск Cast.\n• Затримки: зменшити бітрейт.\n• Не відтворює: MP4/MKV.", connecting_msg: "Підключення до: {{name}}\n\nПотрібен сервер DLNA. Режим демо.", connecting_title: "Підключення DLNA" },
        update: {
            no_update_title: "Перевірити оновлення",
            no_update_message: "Поточна версія V{{version}} є актуальною",
            no_update_detail: "Новіша версія не знайдена. Приємного користування додатком.",
            check_failed_title: "Не вдалося перевірити оновлення",
            check_failed_message: "Неможливо під’єднатися до сервера оновлень: {{error}}",
            check_not_available: "Функція оновлення недоступна в цьому середовищі",
            checking: "Перевірка наявності оновлень...",
            check_failed_toast: "Помилка перевірки оновлень. Спробуйте пізніше"
        },
        recent: { title: "Нещодавно", empty: "Немає нещодавнього відтворення", empty_tip: "Відтворені відео з’являться тут", clear_all: "Очистити все", remove_selected: "Видалити вибрані" },
        favorites: { title: "Обране", add_to_favorites: "Додати в обране", my_favorites: "Моє обране", empty: "Поки немає обраного", empty_tip: "Під час відтворення клацніть правою кнопкою та виберіть «Додати в обране»", no_video: "Спочатку виберіть або відтворіть відео", cannot_save: "Не вдалося додати в обране", added: "Додано в обране", remove: "Видалити з обраного", invalid_entry: "Недійсне обране" },
        dialog: { close_confirm: "Закрити KunQiong Player?", close_title: "Підтвердження", notice: "Сповіщення", logout_confirm: "Вийти?", ok: "OK", cancel: "Скасувати", help_doc_content: "KunQiong Player\n\nГарячі клавіші:\nПробіл - Відтв./Пауза\n← / → - Назад/Вперед\n↑ / ↓ - Гучність\nF - Повний екран\nM - Без звуку", shortcuts_content: "Пробіл - Відтв./Пауза\n← - Назад\n→ - Вперед\n↑/↓ - Гучність\nF - Повний екран\nM - Без звуку\nEsc - Вийти з повного екрана\nCtrl+S - Стоп", about_content: "KunQiong Player\n\nВідеоплеєр з ШІ.\n\n【Функції】\n• Багато форматів\n• Апаратне декодування\n• Налаштування зображення/звуку\n• Подвійні субтитри\n• DLNA\n• Режим кіно" }
    }
};
