/**
 * اردو
 */
export default {
    translation: {
        app: { title: "KunQiong Player", subtitle: "Powered by KunQiong AI", custom_software: "حسب ضرورت سافٹ ویئر", login: "لاگ ان", not_logged_in: "مہمان", logged_in: "لاگ ان ہو گیا", login_tip: "مزید فنکشنز کے لیے لاگ ان کریں", login_action: "لاگ ان کریں", redirecting: "ری ڈائریکٹ ہو رہا ہے...", login_in_browser: "براؤزر میں لاگ ان مکمل کریں۔", relogin: "دوبارہ لاگ ان", login_success_sync: "لاگ ان ہوا۔ ہم آہنگ ہو رہا ہے...", vip_user: "رکن", logout: "لاگ آؤٹ", token_label: "ٹوکن:", welcome_tip: "ویڈیو یہاں ڈریگ کریں", loading: "لوڈ ہو رہا ہے...", screenshot_path: "اسکرین شاٹ فولڈر:", global_brightness: "چمک", reset: "ری سیٹ", reset_all: "سب ری سیٹ", ok: "ٹھیک", cancel: "منسوخ", apply: "لاگو کریں", unit: { ms: "ms", s: "s", times: "x", items: "" } },
        menu: { file: "فائل", open_file: "فائل کھولیں...", open_folder: "فولڈر کھولیں...", open_url: "URL کھولیں...", exit: "باہر", play: "چلائیں", play_pause: "چلائیں/روکیں", stop: "روکیں", next: "اگلا", prev: "پچھلا", fast_forward: "آگے", rewind: "پیچھے", effects: "ایفیکٹس", splitter: "سپلٹر", video_decoder: "ویڈیو ڈیکوڈر", audio_decoder: "آڈیو ڈیکوڈر", renderer: "رینڈرر", auto_select: "آٹو", control: "کنٹرول", subtitle: "سب ٹائٹل", picture_quality: "تصویر", audio_adjust: "آڈیو", settings: "ترتیبات", help: "مدد", help_doc: "دستاویزات", shortcuts: "شارٹ کٹ", licenses: "تھرڈ پارٹی لائسنس", privacy: "پرائیویسی", check_update: "اپڈیٹ چیک کریں...", feedback: "رائے", about: "کے بارے میں", language: "زبان", lang_zh: "简体中文", lang_en: "English" },
        playlist: { title: "پلے لسٹ", add: "شامل کریں", clear: "صاف کریں", loop: "لسٹ دہرائیں", loop_list: "لسٹ دہرائیں", loop_list_title: "لسٹ دہرائیں", loop_single: "ایک دہرائیں", loop_single_title: "ایک دہرائیں", random: "بے ترتیب", random_title: "بے ترتیب", empty: "لسٹ خالی", empty_tip: "\"شامل کریں\" کلک کریں یا فائلیں ڈریگ کریں", ad_placeholder: "اشتہار" },
        picture: { title: "تصویر", ratio: "تناسب", ratio_original: "اصل", ratio_fill: "بھریں", rotation: "گھمائیں", flip_h: "افقی", flip_v: "عمودی", pan: "پین", zoom: "زوم", presets: { default: "ڈیفالٹ", bright: "روشن", soft: "نرم", retro: "ریٹرو" } },
        audio: { title: "آڈیو", volume: "والیوم", channel: "چینل", channel_default: "ڈیفالٹ", channel_left: "بائیں", channel_right: "دائیں", sync: "ہم آہنگ", track: "ٹریک", track_default: "ڈیفالٹ", load_track: "ٹریک لوڈ کریں" },
        subtitle: { title: "سب ٹائٹل", main_tab: "بنیادی", sec_tab: "ثانوی", select: "منتخب کریں", hide: "چھپائیں", load: "لوڈ کریں", enable_sec: "ثانوی چالو کریں", style: "سٹائل", font_yahei: "Microsoft YaHei", font_hei: "SimHei", font_song: "SimSun", font_kai: "KaiTi", sync: "ہم آہنگ", position: "پوزیشن", pos_up: "اوپر", pos_down: "نیچے", pos_left: "بائیں", pos_right: "دائیں", continue_effect: "ہمیشہ لاگو کریں", color_title: "رنگ", basic_color: "بنیادی رنگ", custom_color: "حسب ضرورت", cancel: "منسوخ", confirm: "تصدیق" },
        control: { title: "کنٹرول", left_eye: "بایاں آنکھ", surround: "سراؤنڈ", threed: "3D موڈ", settings: "ترتیبات" },
        lefteye: { title: "بایاں آنکھ", view_angle: "ویو اینگل", brightness: "چمک", contrast: "کنٹراسٹ" },
        surround: { title: "سراؤنڈ", mode: "موڈ", mode_off: "بند", mode_stereo: "سٹیریو", intensity: "شدت", bass: "باس" },
        threed: { title: "3D", mode: "موڈ", mode_off: "بند", mode_anaglyph: "ایناگلف", mode_sbs: "سائڈ بائی سائڈ", mode_tb: "اوپر/نیچے", depth: "گہرائی", eye_dist: "آنکھوں کا فاصلہ" },
        settings: { title: "جدید ترتیبات", tabs: { general: "عام", playback: "پلے بیک" }, sidebar: { list: "لسٹ ایریا", hotkey: "شارٹ کٹ", screenshot: "اسکرین شاٹس", file_assoc: "فائل ایسوسی ایشن", playback_basic: "بنیادی پلے بیک" }, playback: { title: "بنیادی پلے بیک", step_group: "آگے/پیچھے", forward_once: "ایک بار آگے", rewind_once: "ایک بار پیچھے", speed_group: "رفتار", speed_once: "رفتار", playlist_group: "پلے لسٹ", continue_last: "آخری لسٹ جاری رکھیں", auto_add: "ملتی جلتی شامل کریں", clear_on_open: "کھولتے وقت صاف کریں", prompt_cleanup: "لمبی لسٹ پر صفائی تجویز کریں" }, hotkey: { title: "شارٹ کٹ", header_command: "کمانڈ", header_mouse: "ماؤس", header_key: "کی", header_action: "ایکشن", disable_swf: "SWF کے لیے بند", btn_modify: "تبدیل کریں", actions: { playPause: "چلائیں/روکیں", stop: "روکیں", fastForward: "آگے", rewind: "پیچھے", speedUp: "تیز", speedDown: "آہستہ", volumeUp: "والیوم +", volumeDown: "والیوم -", mute: "م یوٹ", fullscreen: "فل سکرین", exitFullscreen: "فل سکرین سے باہر" }, mouse_left: "بایاں کلک" }, screenshot: { title: "اسکرین شاٹس", path_label: "فولڈر", btn_change: "فولڈر بدلیں", format_label: "فارمیٹ", tool_label: "ٹول", popup_label: "کیپچر کے بعد دکھائیں" }, file_assoc: { title: "فائل ایسوسی ایشن", status_checking: "چیک ہو رہا ہے...", status_is_default: "ڈیفالٹ پلیئر", status_not_default: "ڈیفالٹ نہیں", status_check_failed: "چیک ناکام", btn_set_default: "ڈیفالٹ سیٹ کریں", btn_already_set: "پہلے سے سیٹ", btn_select_all: "سب منتخب", btn_select_none: "کوئی نہیں", btn_restore: "بحال کریں", always_assoc: "ہمیشہ ایسوسی ایٹ کریں", formats: { wmv: "Windows Media Video", real: "Real Media", vcd: "VCD/DVD", quicktime: "QuickTime", other_video: "دوسرا ویڈیو", other_audio: "دوسرا آڈیو", animation: "اینی میشن", playlist: "پلے لسٹ", subtitle: "سب ٹائٹل" } }, list: { title: "لسٹ ایریا", display_group: "ڈسپلے", always_expand: "ہمیشہ پھیلائیں", always_close: "ہمیشہ سکیڑیں", remember: "حالت یاد رکھیں", a11y: "رسائی", text_auto: "ٹیکسٹ سائز آٹو", text_manual: "دستی" } },
        context_menu: { play: "چلائیں", pause: "روکیں", stop: "روکیں", prev: "پچھلا", next: "اگلا", fullscreen: "فل سکرین", exit_fullscreen: "فل سکرین سے باہر", screenshot: "اسکرین شاٹ", picture: "تصویر", audio: "آڈیو", open: "فائل کھولیں...", properties: "پراپرٹیز", settings: "ترتیبات" },
        properties: { title: "پراپرٹیز", filename_empty: "کوئی ویڈیو نہیں", label_type: "قسم:", label_duration: "دورانیہ:", label_size: "سائز:", label_location: "لوکیشن:", section_video: "ویڈیو", label_resolution: "ریزولیوشن:", label_codec: "کوڈیک:", label_framerate: "FPS:", label_bitrate: "بٹ ریٹ:", btn_more: "مزید", type_video: "ویڈیو" },
        screenshot_preview: { title: "اسکرین شاٹ پیش نظارہ", label_no_popup: "پھر نہ دکھائیں", btn_save: "محفوظ کریں" },
        dlna: { title: "DLNA ڈیوائسز", subtitle: "آؤٹ پٹ ڈیوائس منتخب کریں", searching: "ڈیوائس تلاش ہو رہی ہے...", no_device: "کوئی ڈیوائس نہیں ملا", no_device_hint: "ریفریش کریں یا نیٹ ورک چیک کریں", select_device_first: "پہلے ڈیوائس منتخب کریں", device_ready: "تیار", help_guide_title: "DLNA گائیڈ", help_guide_content: "【ضروریات】\n• PC اور TV ایک ہی Wi-Fi/LAN پر۔\n• TV پر DLNA/Cast چالو کریں۔\n\n【اقدامات】\n1. نیچے [DLNA] کلک کریں۔\n2. تلاش کے لیے \"ریفریش\"۔\n3. TV منتخب کریں اور \"کنیکٹ\"۔\n\n【مدد】\n• کوئی ڈیوائس نہیں: فائروال یا Cast ری اسٹارٹ۔\n• لیگ: بٹ ریٹ کم کریں۔\n• نہیں چلتا: MP4/MKV استعمال کریں۔", connecting_msg: "کنیکٹ ہو رہا ہے: {{name}}\n\nDLNA سرور درکار۔ ڈیمو موڈ۔", connecting_title: "DLNA کنکشن" },
        update: {
            no_update_title: "تازہ کاریوں کی جانچ",
            no_update_message: "موجودہ ورژن V{{version}} پہلے ہی تازہ ترین ہے",
            no_update_detail: "کوئی نیا ورژن نہیں ملا۔ ایپ کے استعمال سے لطف اٹھائیں۔",
            check_failed_title: "تازہ کاریوں کی جانچ ناکام",
            check_failed_message: "تازہ کاری سرور سے رابطہ نہیں ہو سکا: {{error}}",
            check_not_available: "اس ماحول میں اپ ڈیٹ فیچر دستیاب نہیں",
            checking: "تازہ کاریوں کی جانچ ہو رہی ہے...",
            check_failed_toast: "تازہ کاریوں کی جانچ ناکام، براہ کرم بعد میں دوبارہ کوشش کریں"
        },
        recent: { title: "حالیہ", empty: "ابھی کوئی حالیہ پلے بیک نہیں", empty_tip: "چلائی گئی ویڈیوز یہاں دکھائی دیں گی", clear_all: "سب صاف کریں", remove_selected: "منتخب ہٹائیں" },
        favorites: { title: "پسندیدہ", add_to_favorites: "پسندیدہ میں شامل کریں", my_favorites: "میری پسندیدہ", empty: "ابھی کوئی پسندیدہ نہیں", empty_tip: "چلانے کے دوران رائٹ کلک کریں اور \"پسندیدہ میں شامل کریں\" منتخب کریں", no_video: "پہلے ایک ویڈیو منتخب یا چلائیں", cannot_save: "پسندیدہ میں شامل نہیں ہو سکتا", added: "پسندیدہ میں شامل ہو گیا", remove: "پسندیدہ سے ہٹائیں", invalid_entry: "غلط پسندیدہ انٹری" },
        dialog: { close_confirm: "KunQiong Player بند کریں؟", close_title: "بند کرنے کی تصدیق", notice: "نوٹس", logout_confirm: "لاگ آؤٹ کریں؟", ok: "ٹھیک", cancel: "منسوخ", help_doc_content: "KunQiong Player\n\nشارٹ کٹ:\nاسپیس - چلائیں/روکیں\n← / → - پیچھے/آگے\n↑ / ↓ - والیوم\nF - فل سکرین\nM - م یوٹ", shortcuts_content: "اسپیس - چلائیں/روکیں\n← - پیچھے\n→ - آگے\n↑/↓ - والیوم\nF - فل سکرین\nM - م یوٹ\nEsc - فل سکرین سے باہر\nCtrl+S - روکیں", about_content: "KunQiong Player\n\nAI ویڈیو پلیئر۔\n\n【فنکشنز】\n• کئی فارمیٹس\n• ہارڈ ویئر ڈیکوڈنگ\n• تصویر/آڈیو ایڈجسٹمنٹ\n• ڈبل سب ٹائٹل\n• DLNA\n• سنیما موڈ" }
    }
};
