/**
 * Tiếng Việt
 */
export default {
    translation: {
        app: { title: "KunQiong Player", subtitle: "Powered by KunQiong AI", custom_software: "Phần mềm tùy chỉnh", login: "Đăng nhập", not_logged_in: "Khách", logged_in: "Đã đăng nhập", login_tip: "Đăng nhập để dùng thêm tính năng", login_action: "Đăng nhập", redirecting: "Đang chuyển hướng...", login_in_browser: "Vui lòng đăng nhập trong trình duyệt.", relogin: "Đăng nhập lại", login_success_sync: "Đăng nhập thành công. Đang đồng bộ...", vip_user: "Thành viên", logout: "Đăng xuất", token_label: "Token:", welcome_tip: "Kéo thả video vào đây", loading: "Đang tải...", screenshot_path: "Đường dẫn ảnh chụp:", global_brightness: "Độ sáng", reset: "Đặt lại", reset_all: "Đặt lại tất cả", ok: "OK", cancel: "Hủy", apply: "Áp dụng", unit: { ms: "ms", s: "s", times: "x", items: "" } },
        menu: { file: "Tệp", open_file: "Mở tệp...", open_folder: "Mở thư mục...", open_url: "Mở URL...", exit: "Thoát", play: "Phát", play_pause: "Phát/Tạm dừng", stop: "Dừng", next: "Tiếp", prev: "Trước", fast_forward: "Tua nhanh", rewind: "Tua lùi", effects: "Hiệu ứng", splitter: "Splitter", video_decoder: "Giải mã video", audio_decoder: "Giải mã âm thanh", renderer: "Renderer", auto_select: "Tự động", control: "Điều khiển", subtitle: "Phụ đề", picture_quality: "Hình ảnh", audio_adjust: "Âm thanh", settings: "Cài đặt", help: "Trợ giúp", help_doc: "Tài liệu", shortcuts: "Phím tắt", licenses: "Giấy phép bên thứ ba", privacy: "Quyền riêng tư", check_update: "Kiểm tra cập nhật...", feedback: "Phản hồi", about: "Giới thiệu", language: "Ngôn ngữ", lang_zh: "简体中文", lang_en: "English" },
        playlist: { title: "Danh sách phát", add: "Thêm", clear: "Xóa", loop: "Lặp danh sách", loop_list: "Lặp danh sách", loop_list_title: "Lặp danh sách", loop_single: "Lặp một", loop_single_title: "Lặp một", random: "Ngẫu nhiên", random_title: "Ngẫu nhiên", empty: "Danh sách trống", empty_tip: "Nhấn \"Thêm\" hoặc kéo thả tệp", ad_placeholder: "Quảng cáo" },
        picture: { title: "Chỉnh hình ảnh", ratio: "Tỷ lệ", ratio_original: "Gốc", ratio_fill: "Phủ đầy", rotation: "Xoay", flip_h: "Ngang", flip_v: "Dọc", pan: "Pan", zoom: "Thu phóng", presets: { default: "Mặc định", bright: "Sáng", soft: "Mềm", retro: "Retro" } },
        audio: { title: "Âm thanh", volume: "Âm lượng", channel: "Kênh", channel_default: "Mặc định", channel_left: "Trái", channel_right: "Phải", sync: "Đồng bộ", track: "Track", track_default: "Mặc định", load_track: "Tải track" },
        subtitle: { title: "Phụ đề", main_tab: "Chính", sec_tab: "Phụ", select: "Chọn", hide: "Ẩn", load: "Tải", enable_sec: "Bật phụ đề phụ", style: "Kiểu", font_yahei: "Microsoft YaHei", font_hei: "SimHei", font_song: "SimSun", font_kai: "KaiTi", sync: "Đồng bộ", position: "Vị trí", pos_up: "Trên", pos_down: "Dưới", pos_left: "Trái", pos_right: "Phải", continue_effect: "Luôn áp dụng", color_title: "Màu", basic_color: "Màu cơ bản", custom_color: "Tùy chỉnh", cancel: "Hủy", confirm: "Xác nhận" },
        control: { title: "Điều khiển", left_eye: "Mắt trái", surround: "Surround", threed: "Chế độ 3D", settings: "Cài đặt" },
        lefteye: { title: "Mắt trái", view_angle: "Góc nhìn", brightness: "Độ sáng", contrast: "Độ tương phản" },
        surround: { title: "Surround", mode: "Chế độ", mode_off: "Tắt", mode_stereo: "Stereo", intensity: "Cường độ", bass: "Bass" },
        threed: { title: "3D", mode: "Chế độ", mode_off: "Tắt", mode_anaglyph: "Anaglyph", mode_sbs: "Cạnh nhau", mode_tb: "Trên/dưới", depth: "Độ sâu", eye_dist: "Khoảng cách mắt" },
        settings: { title: "Cài đặt nâng cao", tabs: { general: "Chung", playback: "Phát" }, sidebar: { list: "Khu vực danh sách", hotkey: "Phím tắt", screenshot: "Ảnh chụp", file_assoc: "Liên kết tệp", playback_basic: "Phát cơ bản" }, playback: { title: "Phát cơ bản", step_group: "Tua nhanh/Lùi", forward_once: "Tua nhanh một lần", rewind_once: "Tua lùi một lần", speed_group: "Tốc độ", speed_once: "Tốc độ", playlist_group: "Danh sách", continue_last: "Tiếp tục danh sách cuối", auto_add: "Tự thêm tệp tương tự", clear_on_open: "Xóa khi mở", prompt_cleanup: "Nhắc dọn khi danh sách dài" }, hotkey: { title: "Phím tắt", header_command: "Lệnh", header_mouse: "Chuột", header_key: "Phím", header_action: "Thao tác", disable_swf: "Tắt khi phát SWF", btn_modify: "Sửa", actions: { playPause: "Phát/Tạm dừng", stop: "Dừng", fastForward: "Tua nhanh", rewind: "Tua lùi", speedUp: "Tăng tốc", speedDown: "Giảm tốc", volumeUp: "Tăng âm lượng", volumeDown: "Giảm âm lượng", mute: "Tắt tiếng", fullscreen: "Toàn màn hình", exitFullscreen: "Thoát toàn màn hình" }, mouse_left: "Chuột trái" }, screenshot: { title: "Ảnh chụp", path_label: "Đường dẫn", btn_change: "Đổi đường dẫn", format_label: "Định dạng", tool_label: "Công cụ", popup_label: "Hiện sau khi chụp" }, file_assoc: { title: "Liên kết tệp", status_checking: "Đang kiểm tra...", status_is_default: "Trình phát mặc định", status_not_default: "Không phải mặc định", status_check_failed: "Kiểm tra thất bại", btn_set_default: "Đặt mặc định", btn_already_set: "Đã đặt", btn_select_all: "Chọn tất cả", btn_select_none: "Bỏ chọn", btn_restore: "Khôi phục", always_assoc: "Luôn liên kết", formats: { wmv: "Windows Media Video", real: "Real Media", vcd: "VCD/DVD", quicktime: "QuickTime", other_video: "Video khác", other_audio: "Âm thanh khác", animation: "Hoạt hình", playlist: "Danh sách", subtitle: "Phụ đề" } }, list: { title: "Khu vực danh sách", display_group: "Hiển thị", always_expand: "Luôn mở rộng", always_close: "Luôn thu gọn", remember: "Nhớ trạng thái", a11y: "Truy cập", text_auto: "Cỡ chữ tự động", text_manual: "Cỡ chữ thủ công" } },
        context_menu: { play: "Phát", pause: "Tạm dừng", stop: "Dừng", prev: "Trước", next: "Tiếp", fullscreen: "Toàn màn hình", exit_fullscreen: "Thoát toàn màn hình", screenshot: "Chụp màn hình", picture: "Hình ảnh", audio: "Âm thanh", open: "Mở tệp...", properties: "Thuộc tính", settings: "Cài đặt" },
        properties: { title: "Thuộc tính", filename_empty: "Chưa tải video", label_type: "Loại:", label_duration: "Thời lượng:", label_size: "Kích thước:", label_location: "Vị trí:", section_video: "Video", label_resolution: "Độ phân giải:", label_codec: "Codec:", label_framerate: "FPS:", label_bitrate: "Bitrate:", btn_more: "Thêm", type_video: "Video" },
        screenshot_preview: { title: "Xem trước ảnh chụp", label_no_popup: "Không hiện lại", btn_save: "Lưu" },
        dlna: { title: "Thiết bị DLNA", subtitle: "Chọn thiết bị xuất", searching: "Đang tìm thiết bị...", no_device: "Không tìm thấy thiết bị", no_device_hint: "Làm mới hoặc kiểm tra mạng", select_device_first: "Vui lòng chọn một thiết bị", device_ready: "Sẵn sàng", help_guide_title: "Hướng dẫn DLNA", help_guide_content: "【Yêu cầu】\n• PC và TV cùng Wi-Fi/LAN.\n• Bật DLNA/Cast trên TV.\n\n【Các bước】\n1. Nhấn [DLNA] ở dưới.\n2. \"Làm mới\" để tìm.\n3. Chọn TV và \"Kết nối\".\n\n【Trợ giúp】\n• Không có thiết bị: kiểm tra tường lửa hoặc khởi động lại Cast.\n• Giật: giảm bitrate.\n• Không phát: dùng MP4/MKV.", connecting_msg: "Đang kết nối: {{name}}\n\nCần máy chủ DLNA. Chế độ demo.", connecting_title: "Kết nối DLNA" },
        update: {
            no_update_title: "Kiểm tra cập nhật",
            no_update_message: "Phiên bản hiện tại V{{version}} là mới nhất",
            no_update_detail: "Không tìm thấy phiên bản mới hơn. Chúc bạn sử dụng vui vẻ.",
            check_failed_title: "Kiểm tra cập nhật thất bại",
            check_failed_message: "Không thể kết nối tới máy chủ cập nhật: {{error}}",
            check_not_available: "Chức năng cập nhật không khả dụng trong môi trường này",
            checking: "Đang kiểm tra cập nhật...",
            check_failed_toast: "Kiểm tra cập nhật thất bại, vui lòng thử lại sau"
        },
        recent: { title: "Gần đây", empty: "Chưa có phát gần đây", empty_tip: "Video đã phát sẽ hiển thị ở đây", clear_all: "Xóa tất cả", remove_selected: "Xóa đã chọn" },
        favorites: { title: "Yêu thích", add_to_favorites: "Thêm vào yêu thích", my_favorites: "Yêu thích của tôi", empty: "Chưa có yêu thích", empty_tip: "Nhấp chuột phải và chọn \"Thêm vào yêu thích\" khi đang phát", no_video: "Vui lòng chọn hoặc phát video trước", cannot_save: "Không thể thêm vào yêu thích", added: "Đã thêm vào yêu thích", remove: "Xóa khỏi yêu thích", invalid_entry: "Mục yêu thích không hợp lệ" },
        dialog: { close_confirm: "Đóng KunQiong Player?", close_title: "Xác nhận thoát", notice: "Thông báo", logout_confirm: "Đăng xuất?", ok: "OK", cancel: "Hủy", help_doc_content: "KunQiong Player\n\nPhím tắt:\nPhím cách - Phát/Tạm dừng\n← / → - Lùi/Tiến\n↑ / ↓ - Âm lượng\nF - Toàn màn hình\nM - Tắt tiếng", shortcuts_content: "Phím cách - Phát/Tạm dừng\n← - Lùi\n→ - Tiến\n↑/↓ - Âm lượng\nF - Toàn màn hình\nM - Tắt tiếng\nEsc - Thoát toàn màn hình\nCtrl+S - Dừng", about_content: "KunQiong Player\n\nTrình phát video với AI.\n\n【Tính năng】\n• Nhiều định dạng\n• Giải mã phần cứng\n• Chỉnh hình/âm thanh\n• Phụ đề kép\n• DLNA\n• Chế độ rạp" }
    }
};
